<div>
<img src="https://github.com/JanKolacek/figs/blob/main/logoJupyterR.png?raw=true"/>
</div>

# 4. přednáška

## Typická datová analýza v R

<div class="alert alert-block alert-info"> 

### 1. Jak vypadá typický životní cyklus datové analýzy

Datová analýza v R obvykle sleduje ucelený workflow (často vycházející z metodiky Tidyverse):

1. **Načtení a import dat:** Načtení dat z CSV, Excelu, databází nebo API (`readr`, `readxl`, `fromJSON`).
2. **Čištění a úprava:** Ošetření chybějících hodnot (`NA`), filtrace, tvorba nových sloupců a agregace (`dplyr`, `tidyr`).
3. **Průzkumová analýza a vizualizace:** Souhrnné statistiky, objevování vzorců a tvorba grafů (`ggplot2`).
4. **Modelování a statistika:** Regrese, klasifikace, testování hypotéz (`stats`, `tidymodels`).
5. **Export a prezentace:** Uložení výsledků do databáze/souboru, generování reportů (**Quarto**, **R Markdown**) nebo výstupů pro **Jupyter**.
</div>

<div class="alert alert-block alert-info"> 

### 2. Tvorba kapitol a sekcí ve skriptu (Document Outline)

Ve VS Code můžete R skript rozdělit na přehledné logické kapitoly. Rozhraní automaticky rozpozná speciální komentáře a vygeneruje z nich stromovou strukturu kódu (Outline).

Sekci v R vytvoříte tak, že za komentářový řádek přihodíte **nejméně 4 pomlčky (`----`), křížky (`####`) nebo rovnitka (`====`)**:

</div>

```R
# 1. NAČTENÍ KNIHOVEN A DAT ----
library(tidyverse)
library(data.table)

df <- fread("data.csv")


# 2. ČIŠTĚNÍ DAT ====
df_clean <- df %>%
  filter(!is.na(customer_id)) %>%
  mutate(amount = ifelse(amount < 0, 0, amount))


# 3. VIZUALIZACE A EDA ####
ggplot(df_clean, aes(x = category, y = amount)) +
  geom_boxplot()
```

<div class="alert alert-block alert-info"> 

### 3. Rychlá navigace v delším kódu ve VS Code

Pro efektivní práci s rozsáhlými skripty nabízí VS Code několik klíčových zkratek:

| Klávesová zkratka (Win/Linux) | Klávesová zkratka (Mac) | Funkce |
| :--- | :--- | :--- |
| **`Ctrl + Shift + O`** | **`Cmd + Shift + O`** | **Přechod na sekci/symbol:** Otevře seznam kapitol z přehledu kódů s možností vyhledávání. |
| **`Ctrl + G`** | **`Ctrl + G`** | **Skočit na řádek:** Zadáním čísla se rovnou přesunete na konkrétní řádek. |
| **`Ctrl + Shift + \`** | **`Cmd + Shift + \`** | **Skočit na párovou závorku:** Okamžitě najde odpovídající zavírací/otevírací závorku `()`, `{}` nebo `[]`. |
| **`Ctrl + F` / `Ctrl + H`** | **`Cmd + F` / `Cmd + H`** | Vyhledávání / Nahrazování v aktuálním souboru. |
| **`Ctrl + Click`** na funkci | **`Cmd + Click`** na funkci | **Přejít k definici:** Pokud kliknete na vlastní R funkci, VS Code vás přesune na místo, kde byla vytvořena. |  

</div>

<div class="alert alert-block alert-info"> 

### 4. Rozdělení kódu na více částí

Místo jednoho „obřího“ skriptu o tisících řádcích je osvědčenou praxí kód rozdělit do více menších souborů podle jejich účelu:

#### A. Struktura složek projektu
</div>

```text
muj_projekt/
├── 01_import.R          # Načtení dat z externích zdrojů
├── 02_cisteni.R         # Transformace a úprava typů
├── 03_vizualizace.R     # Grafy a reportování
├── R/
│   └── pomocne_funkce.R # Vlastní R funkce (Custom Functions)
└── main.R               # Hlavní skript, který spouští celý proces
```
<div class="alert alert-block alert-info"> 

#### B. Propojení skriptů pomocí **source**
V hlavním skriptu (`main.R`) nebo Jupyter notebooku pak jednotlivé části postupně spouštíte:

</div>

```R
# Načtení vlastních funkcí
source("R/pomocne_funkce.R")

# Postupné spuštění pipeline
source("01_import.R")
source("02_cisteni.R")
source("03_vizualizace.R")
```

## Datové tabulky

## Příklad 1
V tabulce jsou uvedeny informace o výsledcích testu pro pět vybraných studentů

| &nbsp; | obor | body |
| :--- | :---: | :---: |
| *Jiří* | AMV | 5,3 |
| *Tomáš* | STAT | 9 |
| *Helena* | OM | 2,3 |
| *Josef* | OM | 4,8 |
| *Veronika* | FINPOJ | 10 |

<div class="alert alert-block alert-success"> 

**1.** Jak uložit data do proměnných?
    
</div>

In [128]:
jmena <- c("Jiri", "Tomas", "Helena", "Josef", "Veronika")
obor_nazev <- c("AMV", "STAT", "OM", "OM", "FINPOJ")
body_hodnoty <- c(5.3, 9, 2.3, 4.8, 10)
# vytvorime tabulku
test_df <- data.frame(obor = obor_nazev, body = body_hodnoty)
test_df

  obor   body
1 AMV     5.3
2 STAT    9.0
3 OM      2.3
4 OM      4.8
5 FINPOJ 10.0

<div class="alert alert-block alert-danger"> 

Datová tabulka se definuje příkazem **data.frame**.
    
</div>

<div class="alert alert-block alert-success"> 

**2.** Jak pojmenovat řádky?
    
</div>

In [129]:
row.names(test_df) <- jmena
test_df

         obor   body
Jiri     AMV     5.3
Tomas    STAT    9.0
Helena   OM      2.3
Josef    OM      4.8
Veronika FINPOJ 10.0

<div class="alert alert-block alert-success"> 

**3.** Jak zjistit rozměr a strukturu tabulky?
    
</div>

In [130]:
dim(test_df)
str(test_df)

[1] 5 2

'data.frame':	5 obs. of  2 variables:
 $ obor: chr  "AMV" "STAT" "OM" "OM" ...
 $ body: num  5.3 9 2.3 4.8 10

<div class="alert alert-block alert-success"> 

**4.** Jak vypsat všechny údaje o Heleně? Jak vypsat všechny údaje o chlapcích?
    
</div>

In [131]:
test_df["Helena", ]

       obor body
Helena OM   2.3

In [132]:
test_df[c(1, 2, 4), ]

      obor body
Jiri  AMV  5.3
Tomas STAT 9.0
Josef OM   4.8

<div class="alert alert-block alert-success"> 

**5.** Jak vypsat pouze sloupec body? Jak zjistit průměrný počet získaných bodů?
    
</div>

In [133]:
test_df[ ,"body"]
mean(test_df[ ,"body"])
test_df$body

[1]  5.3  9.0  2.3  4.8 10.0

[1] 6.28

[1]  5.3  9.0  2.3  4.8 10.0

<div class="alert alert-block alert-warning"> 

Pozor! Sloupec tabulky lze vypsat několika způsoby. Výsledek nemusí být vždy stejného typu.

</div>

<div class="alert alert-block alert-success"> 

**6.** Jak přidat sloupec zapocteno, který bude nabývat hodnot TRUE v případě, že student získal alespoň 5 bodů a FALSE v opačném případě?
    
</div>

In [134]:
data.frame(test_df, zapocteno = (test_df$body >= 5))

         obor   body zapocteno
Jiri     AMV     5.3  TRUE
Tomas    STAT    9.0  TRUE
Helena   OM      2.3 FALSE
Josef    OM      4.8 FALSE
Veronika FINPOJ 10.0  TRUE

In [135]:
test_df$zapocteno <- (test_df$body >= 5)
test_df

         obor   body zapocteno
Jiri     AMV     5.3  TRUE
Tomas    STAT    9.0  TRUE
Helena   OM      2.3 FALSE
Josef    OM      4.8 FALSE
Veronika FINPOJ 10.0  TRUE

<div class="alert alert-block alert-success"> 

**7.** Jak přidat dalšího studenta Honzu, který studuje obor STAT a získal 7,5 bodů?
    
</div>

In [136]:
test_df[6, ] <- data.frame("STAT", 7.5)
test_df

         obor   body zapocteno
Jiri     AMV     5.3 TRUE
Tomas    STAT    9.0 TRUE
Helena   OM      2.3 FALSE
Josef    OM      4.8 FALSE
Veronika FINPOJ 10.0 TRUE
1        STAT    7.5 STAT

In [137]:
test_df <- test_df[1:5, ]
dalsi_df <- data.frame(obor = "STAT", body = 7.5, zapocteno = TRUE, row.names = "Honza")
test_df <- rbind(test_df, dalsi_df)
test_df

         obor   body zapocteno
Jiri     AMV     5.3 TRUE
Tomas    STAT    9.0 TRUE
Helena   OM      2.3 FALSE
Josef    OM      4.8 FALSE
Veronika FINPOJ 10.0 TRUE
Honza    STAT    7.5 TRUE

<div class="alert alert-block alert-success"> 

**8.** Josef uprosil opravujícího na 5 bodů. Jak změnit údaje v tabulce?
    
</div>

In [138]:
test_df$body[4] <- 5
test_df$zapocteno[4] <- TRUE
test_df

         obor   body zapocteno
Jiri     AMV     5.3 TRUE
Tomas    STAT    9.0 TRUE
Helena   OM      2.3 FALSE
Josef    OM      5.0 TRUE
Veronika FINPOJ 10.0 TRUE
Honza    STAT    7.5 TRUE

<div class="alert alert-block alert-success"> 

**9.** Jak seřadit tabulku podle počtu bodů?
    
</div>

In [139]:
test_df[order(test_df$body, decreasing = TRUE), ]

         obor   body zapocteno
Veronika FINPOJ 10.0 TRUE
Tomas    STAT    9.0 TRUE
Honza    STAT    7.5 TRUE
Jiri     AMV     5.3 TRUE
Josef    OM      5.0 TRUE
Helena   OM      2.3 FALSE

<div class="alert alert-block alert-success"> 

**10.** Jak seřadit podle oboru a pak podle počtu bodů?
    
</div>

In [140]:
test_df[order(test_df$obor, test_df$body,
              decreasing = c(FALSE, TRUE), 
              method = "radix"), ]

         obor   body zapocteno
Jiri     AMV     5.3 TRUE
Veronika FINPOJ 10.0 TRUE
Josef    OM      5.0 TRUE
Helena   OM      2.3 FALSE
Tomas    STAT    9.0 TRUE
Honza    STAT    7.5 TRUE

<div class="alert alert-block alert-success"> 

**11.** Jak zjistit nejúspěšnější ženu?
    
</div>

In [141]:
zeny <- test_df[c(3, 5), ]
zeny[which.max(zeny$body), ]
row.names(zeny)[which.max(zeny$body)]

         obor   body zapocteno
Veronika FINPOJ 10   TRUE

[1] "Veronika"

<div class="alert alert-block alert-success"> 

**12.** Máme tabulku s body z jiného testu. Jak obě tabulky sloučit dohromady?

 | | obor | body|
 | :- | :-: | :-: |
 |*Helena* | OM | 15|
 |*Veronika* | FINPOJ | 12|
 |*Honza* | STAT | 8|
 |*Jiří* | AMV | 11|
 |*Tomáš* | STAT | 3 |
 |*Josef* | OM | 14|

    
</div>

In [142]:
test_jiny_df <- test_df[c(3, 5, 6, 1, 2, 4), 1:2]
test_jiny_df$body <- c(15, 12, 8, 11, 3, 14)

In [143]:
test_jiny_df$jmeno <- row.names(test_jiny_df)
test_df$jmeno <- row.names(test_df)
test_df
test_jiny_df

         obor   body zapocteno jmeno
Jiri     AMV     5.3 TRUE      Jiri
Tomas    STAT    9.0 TRUE      Tomas
Helena   OM      2.3 FALSE     Helena
Josef    OM      5.0 TRUE      Josef
Veronika FINPOJ 10.0 TRUE      Veronika
Honza    STAT    7.5 TRUE      Honza

         obor   body jmeno
Helena   OM     15   Helena
Veronika FINPOJ 12   Veronika
Honza    STAT    8   Honza
Jiri     AMV    11   Jiri
Tomas    STAT    3   Tomas
Josef    OM     14   Josef

<div class="alert alert-block alert-warning"> 

Pro sloučení dvou tabulek se používá příkaz **merge**. Museli jsme kvůli tomu dodefinovat sloupec s názvem *jmeno*.
    
</div>

In [144]:
merge(test_df, test_jiny_df, by = c("obor", "jmeno"))

  obor   jmeno    body.x zapocteno body.y
1 AMV    Jiri      5.3   TRUE      11
2 FINPOJ Veronika 10.0   TRUE      12
3 OM     Helena    2.3   FALSE     15
4 OM     Josef     5.0   TRUE      14
5 STAT   Honza     7.5   TRUE       8
6 STAT   Tomas     9.0   TRUE       3

## Příklad 2

V tabulce jsou uvedeny informace o filmu

<style>
  table {
    margin: auto;
    width: 100%; /* Adjust the width as needed */
  }
  td {
    text-align: justify;
    padding: 8px; /* Adding padding for better readability */
  }
  th
  {
    text-align: center;
  }
</style>

<table>
    <tr>
    <td> název </td> 
    <td> Pelíšky </td>
    </tr>
    <tr>
    <td> herci </td> 
    <td> Miroslav Donutil, Jiří Kodet, Simona Stašová, Emília Vášáryová, Bolek Polévka, Jaroslav Dušek, Eva Holubová, Stella Zázvorková </td>
    </tr>
    <tr>
    <td>recenze</td>
    <td>
    <table>
    <tr>
        <th> skóre </th><th> zdroj </th><th> komentář </th>
    </tr>
    <tr>
        <td> 4,0 </td><td> csfd1 </td><td> Tenhle film mám rád, byť rozhodně není Hřebejkovým nejlepším.</td>
    </tr>
    <tr>
        <td> 3,5 </td><td> csfd2 </td><td> Nepochopitelným způsobem nadhodnocený film!</td>
    </tr>
    <tr>
        <td> 5,0 </td><td> csfd3 </td><td> Málokdy se vidí, aby se z něčeho stala skoro ihned klasika.</td>
    </tr>
    </table>
    </td>
    </tr>
    <tr>
    <td> rok </td> 
    <td> 1999 </td>
    </tr>
</table>

Zdroj: ČSFD

<div class="alert alert-block alert-success"> 

**19.** Jak uložit data do proměnné?
    
</div>

In [145]:
nazev_filmu <- "Pelíšky"
jmena_hercu <- c("Miroslav Donutil", "Jiří Kodet", "Simona Stašová", 
                 "Emília Vášáryová", "Bolek Polévka", "Jaroslav Dušek", "Eva Holubová", "Stella Zázvorková")
skore_recenze <- c(4, 3.5, 5)
zdroj_recenze <- c("csfd1", "csfd2", "csfd3")
komentare_recenze <- c("Tenhle film mám rád, byť rozhodně není Hřebejkovým nejlepším.",
                       "Nepochopitelným způsobem nadhodnocený film!", 
                       "Málokdy se vidí, aby se z něčeho stala skoro ihned klasika.")
rok_filmu <- 1999

recenze_filmu <- data.frame(skore = skore_recenze, zdroj = zdroj_recenze, komentar = komentare_recenze)
# vytvorime seznam
film <- list(nazev = nazev_filmu, herci = jmena_hercu, recenze = recenze_filmu, rok = rok_filmu)

film

$nazev
[1] "Pelíšky"

$herci
[1] "Miroslav Donutil"  "Jiří Kodet"        "Simona Stašová"
[4] "Emília Vášáryová"  "Bolek Polévka"     "Jaroslav Dušek"
[7] "Eva Holubová"      "Stella Zázvorková"

$recenze
  skore zdroj                                                      komentar
1   4.0 csfd1 Tenhle film mám rád, byť rozhodně není Hřebejkovým nejlepším.
2   3.5 csfd2                   Nepochopitelným způsobem nadhodnocený film!
3   5.0 csfd3   Málokdy se vidí, aby se z něčeho stala skoro ihned klasika.

$rok
[1] 1999

<div class="alert alert-block alert-danger"> 

Seznam se definuje příkazem **list**.
    
</div>

<div class="alert alert-block alert-success"> 

**20.** Jak přidat další položku "režie" Jan Hřebejk?
    
</div>

In [146]:
film$rezie <- "Jan Hrebejk"
film

$nazev
[1] "Pelíšky"

$herci
[1] "Miroslav Donutil"  "Jiří Kodet"        "Simona Stašová"
[4] "Emília Vášáryová"  "Bolek Polévka"     "Jaroslav Dušek"
[7] "Eva Holubová"      "Stella Zázvorková"

$recenze
  skore zdroj                                                      komentar
1   4.0 csfd1 Tenhle film mám rád, byť rozhodně není Hřebejkovým nejlepším.
2   3.5 csfd2                   Nepochopitelným způsobem nadhodnocený film!
3   5.0 csfd3   Málokdy se vidí, aby se z něčeho stala skoro ihned klasika.

$rok
[1] 1999

$rezie
[1] "Jan Hrebejk"

<div class="alert alert-block alert-success"> 

**21.** Herec Bolek Polívka má ve svém jménu chybu. Jak ji opravit?
    
</div>

In [147]:
film$herci[5] <- "Bolek Polívka"
film

$nazev
[1] "Pelíšky"

$herci
[1] "Miroslav Donutil"  "Jiří Kodet"        "Simona Stašová"
[4] "Emília Vášáryová"  "Bolek Polívka"     "Jaroslav Dušek"
[7] "Eva Holubová"      "Stella Zázvorková"

$recenze
  skore zdroj                                                      komentar
1   4.0 csfd1 Tenhle film mám rád, byť rozhodně není Hřebejkovým nejlepším.
2   3.5 csfd2                   Nepochopitelným způsobem nadhodnocený film!
3   5.0 csfd3   Málokdy se vidí, aby se z něčeho stala skoro ihned klasika.

$rok
[1] 1999

$rezie
[1] "Jan Hrebejk"

<div class="alert alert-block alert-success"> 

**22.** Jak zjistit průměrné hodnocení filmu?
    
</div>

In [148]:
mean(film$recenze$skore)

[1] 4.166667

<div class="alert alert-block alert-success"> 

**23.** Jak ke druhému komentáři ještě přidat větu "Ale přesto se mi líbí."?
    
</div>

In [149]:

text_recenze <- paste(film$recenze$komentar[2], "Ale presto se mi libi.")
film$recenze$komentar[2] <- text_recenze
film

$nazev
[1] "Pelíšky"

$herci
[1] "Miroslav Donutil"  "Jiří Kodet"        "Simona Stašová"
[4] "Emília Vášáryová"  "Bolek Polívka"     "Jaroslav Dušek"
[7] "Eva Holubová"      "Stella Zázvorková"

$recenze
  skore zdroj
1   4.0 csfd1
2   3.5 csfd2
3   5.0 csfd3
                                                            komentar
1      Tenhle film mám rád, byť rozhodně není Hřebejkovým nejlepším.
2 Nepochopitelným způsobem nadhodnocený film! Ale presto se mi libi.
3        Málokdy se vidí, aby se z něčeho stala skoro ihned klasika.

$rok
[1] 1999

$rezie
[1] "Jan Hrebejk"

<div class="alert alert-block alert-success"> 

**24.** Jak přidat další komentář recenzenta "csfd4" se skóre 2,5 a se slovním hodnocením "Nic moc!" ?
    
</div>

In [150]:
tab1 <- film$recenze
tab2 <- data.frame(skore = 2.5, zdroj = "csfd4", komentar = "Nic moc!")
film$recenze <- rbind(tab1, tab2)
film

$nazev
[1] "Pelíšky"

$herci
[1] "Miroslav Donutil"  "Jiří Kodet"        "Simona Stašová"
[4] "Emília Vášáryová"  "Bolek Polívka"     "Jaroslav Dušek"
[7] "Eva Holubová"      "Stella Zázvorková"

$recenze
  skore zdroj
1   4.0 csfd1
2   3.5 csfd2
3   5.0 csfd3
4   2.5 csfd4
                                                            komentar
1      Tenhle film mám rád, byť rozhodně není Hřebejkovým nejlepším.
2 Nepochopitelným způsobem nadhodnocený film! Ale presto se mi libi.
3        Málokdy se vidí, aby se z něčeho stala skoro ihned klasika.
4                                                           Nic moc!

$rok
[1] 1999

$rezie
[1] "Jan Hrebejk"

<div class="alert alert-block alert-success"> 

**25.** Jak vymazat položku "rok"?
    
</div>

In [151]:
film$rok <- NULL
film[c(1, 3, 4)]

$nazev
[1] "Pelíšky"

$recenze
  skore zdroj
1   4.0 csfd1
2   3.5 csfd2
3   5.0 csfd3
4   2.5 csfd4
                                                            komentar
1      Tenhle film mám rád, byť rozhodně není Hřebejkovým nejlepším.
2 Nepochopitelným způsobem nadhodnocený film! Ale presto se mi libi.
3        Málokdy se vidí, aby se z něčeho stala skoro ihned klasika.
4                                                           Nic moc!

$rezie
[1] "Jan Hrebejk"

<div class="alert alert-block alert-success"> 

**26.** Jak uložit data do souboru, abych jej mohl poslat kamarádovi?
    
</div>

In [152]:
save(file = "databaze.RData", list = "film")

In [154]:
load(file = "databaze.RData", verbose = TRUE)

Loading objects:
  film