<div>
<img src="https://github.com/JanKolacek/figs/blob/main/logoJupyterR.png?raw=true"/>
</div>

# 5. přednáška

## Knihovny v R

<div class="alert alert-block alert-info"> 

**CRAN** (*Comprehensive R Archive Network*) je oficiální centrální repozitář pro jazyk R. Slouží jako globální síť webových serverů, které ukládají a distribuují samotný softwarový balík R, dokumentaci a především tisíce rozšíření (balíčků/knihoven).
</div>

<div class="alert alert-block alert-info"> 

#### Vlastnosti CRANu:

* **Přísná kontrola kvality:** Každý balíček projde před publikací automatickými i manuálními testy. Musí obsahovat funkční kód, dokumentaci a příklady bez chyb.
* **Automatické řešení závislostí:** Při instalaci balíčku přes `install.packages()` CRAN automaticky doinstaluje i všechny ostatní knihovny, které požadovaný balíček potřebuje k fungování.
* **Verzování a archivace:** CRAN udržuje vždy nejnovější stabilní verze balíčků, ale zároveň uchovává i jejich starší verze pro zpětnou kompatibilitu.
* **Garantovaná dostupnost:** Jedná se o primární a nejbezpečnější zdroj knihoven pro R (na rozdíl od neověřených kódů např. z GitHubu).
</div>

### 1. Instalace knihovny

<div class="alert alert-block alert-info"> 

Knihovnu stačí nainstalovat z oficiálního repozitáře CRAN **pouze jednou**. Instaluje se pomocí příkazu `install.packages("nazev_knihovny")`
</div>

### 2. Načtení knihovny

<div class="alert alert-block alert-info"> 

Před každým použitím v novém skriptu nebo relaci musíte knihovnu **načíst do paměti** příkazem `library(nazev_knihovny)`
</div>

<div class="alert alert-block alert-warning"> 

Všimněte si zadání uvozovek v předchozích dvou příkazech.
</div>

### 3. Použití funkce bez načtení celé knihovny

<div class="alert alert-block alert-info"> 

Pokud potřebujete použít jen jednu konkrétní funkci, lze ji zavolat přímo pomocí operátoru `::` bez předchozího načtení balíčku přes `library()`, tj. ve formátu `nazev_knihovny::prikaz(parametry)`. Tento přístup zároveň řeší případné konflikty, kdy dvě různé knihovny obsahují funkce se stejným názvem.

</div>

### 4. Užitečné příkazy pro správu

<div class="alert alert-block alert-info"> 

- Aktualizace balíčků: `update.packages()`

- Nápověda ke knihovně: `help(package = "nazev_knihovny")`

- Seznam nainstalovaných balíčků: `installed.packages()`
</div>

## Dokumentace ke knihovnám

<div class="alert alert-block alert-info"> 

#### 1. README soubor
Podobně jako u jiných programovacích jazyků slouží `README.md` (nebo `README.Rmd`) jako hlavní vizitka balíčku v repozitáři.

* **Obsah:** Stručný popis, co balíček dělá, návod k instalaci a krátký ukázkový příklad použití.
* **Rozšíření v R (`README.Rmd`):** V R se často používá knitr/rmarkdown s příponou `.Rmd`. Tento soubor umožňuje vkládat živý R kód, který se při vyrenderování do `README.md` automaticky spustí a vloží aktuální výstupy či grafy.


#### 2. DESCRIPTION soubor
Pro definici závislostí má každý R balíček v kořenovém adresáři soubor `DESCRIPTION`. Závislosti se zapisují do specifických sekcí:

* **`Imports:`** Balíčky, které váš kód nutně potřebuje k fungování (nainstalují se automaticky).
* **`Suggests:`** Balíčky potřebné jen pro testování, tvorbu dokumentace nebo volitelné funkce.
* **`Depends:`** Starší způsob definování závislostí (dnes se preferuje `Imports`).

*Ukázka v souboru `DESCRIPTION`:*

```text
Imports:
    dplyr (>= 1.0.0),
    ggplot2,
    stringr
Suggests:
    testthat
```
</div>

## Knihovna *dplyr*

<div class="alert alert-block alert-danger"> 

Pro manipulaci s datovými tabulkami používáme knihovnu **dplyr**.
    
</div>

In [1]:
install.packages("dplyr")

Installing package into 'C:/Users/julza/AppData/Local/R/win-library/4.6'
(as 'lib' is unspecified)

package 'dplyr' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'dplyr'"
Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problem copying C:\Users\julza\AppData\Local\R\win-library\4.6\00LOCK\dplyr\libs\x64\dplyr.dll to C:\Users\julza\AppData\Local\R\win-library\4.6\dplyr\libs\x64\dplyr.dll: Permission denied"
Warning message:
"restored 'dplyr'"

The downloaded binary packages are in
	C:\Users\julza\AppData\Local\Temp\RtmpI5vnQG\downloaded_packages

<div class="alert alert-block alert-info"> 

Nejprve načteme knihovnu **dplyr**. Pokud ještě nemáte, nainstalujte pomocí příkazu **install.packages**.
    
</div>

In [2]:
library(dplyr) |> suppressPackageStartupMessages() |> suppressWarnings() # manipulace s datovymi tabulkami

## Příklad 1
V proměnné **mtcars** jsou uloženy informace o 32 automobilech z roku 1974 dle časopisu *Motor Trend*. Význam jednotlivých sloupců (proměnných) je v následující tabulce.

 | mpg | cyl | disp | hp | drat | wt | qsec | vs | am | gear | carb |
 |:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
 | spotřeba (míle/galon) | počet válců | objem válců (palce krychlové) | výkon (koně) | převodový poměr | hmotnost (1000 liber) | zrychlení (sec/1/4 míle) | motor (0 = válce do "V", 1 = válce přímo) | převodovka (0 = automat, 1 = manuál) | počet převodových stupňů | počet karburátorů |
 
 Zdroj: Henderson and Velleman (1981), *Building multiple regression models interactively.* Biometrics, 37, 391–411.

<div class="alert alert-block alert-danger"> 

Příkaz **glimpse** vypíše přehlednou strukturu datové tabulky.
    
</div>

<div class="alert alert-block alert-success"> 

Zkuste vypsat obsah tabulky **mtcars**.
    
</div>

In [3]:
glimpse(mtcars)

Rows: 32
Columns: 11
$ mpg  <dbl> 21.0, 21.0, 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 22.8, 19.2, 17.8,…
$ cyl  <dbl> 6, 6, 4, 6, 8, 6, 8, 4, 4, 6, 6, 8, 8, 8, 8, 8, 8, 4, 4, 4, 4, 8,…
$ disp <dbl> 160.0, 160.0, 108.0, 258.0, 360.0, 225.0, 360.0, 146.7, 140.8, 16…
$ hp   <dbl> 110, 110, 93, 110, 175, 105, 245, 62, 95, 123, 123, 180, 180, 180…
$ drat <dbl> 3.90, 3.90, 3.85, 3.08, 3.15, 2.76, 3.21, 3.69, 3.92, 3.92, 3.92,…
$ wt   <dbl> 2.620, 2.875, 2.320, 3.215, 3.440, 3.460, 3.570, 3.190, 3.150, 3.…
$ qsec <dbl> 16.46, 17.02, 18.61, 19.44, 17.02, 20.22, 15.84, 20.00, 22.90, 18…
$ vs   <dbl> 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,…
$ am   <dbl> 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,…
$ gear <dbl> 4, 4, 4, 3, 3, 3, 3, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3,…
$ carb <dbl> 4, 4, 1, 1, 2, 1, 4, 2, 2, 4, 4, 3, 3, 3, 4, 4, 4, 1, 2, 1, 1, 2,…

<div class="alert alert-block alert-success"> 

Jak vybrat všechny automobily, které mají výkon větší než 200 koní?
    
</div>

<div class="alert alert-block alert-danger"> 

Příkaz **filter** vybírá různé řádky podle zadaných pravidel a tvoří tak novou tabulku.
    
</div>

<div>
<img src="https://raw.githubusercontent.com/JanKolacek/figs/refs/heads/main/filter.png" width="500"/>
</div>

In [4]:
mtcars |> filter(hp > 200)

                    mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Duster 360          14.3 8   360  245 3.21 3.570 15.84 0  0  3    4
Cadillac Fleetwood  10.4 8   472  205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460  215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440  230 3.23 5.345 17.42 0  0  3    4
Camaro Z28          13.3 8   350  245 3.73 3.840 15.41 0  0  3    4
Ford Pantera L      15.8 8   351  264 4.22 3.170 14.50 0  1  5    4
Maserati Bora       15.0 8   301  335 3.54 3.570 14.60 0  1  5    8

In [5]:
filter(mtcars, hp > 200)

                    mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Duster 360          14.3 8   360  245 3.21 3.570 15.84 0  0  3    4
Cadillac Fleetwood  10.4 8   472  205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460  215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440  230 3.23 5.345 17.42 0  0  3    4
Camaro Z28          13.3 8   350  245 3.73 3.840 15.41 0  0  3    4
Ford Pantera L      15.8 8   351  264 4.22 3.170 14.50 0  1  5    4
Maserati Bora       15.0 8   301  335 3.54 3.570 14.60 0  1  5    8

<div class="alert alert-block alert-success"> 

Jak vyfiltrovat auta, jejichž hmotnost (*wt*) leží v rozmezí 2.5 až 3.5 (pomocí **between**)?
    
</div>

In [6]:
mtcars |> filter(between(wt, 2.5, 3.5))

                  mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag     21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Hornet 4 Drive    21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout 18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant           18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Merc 240D         24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230          22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280          19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C         17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
AMC Javelin       15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Ford Pantera L    15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino      19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Volvo 142E        21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

<div class="alert alert-block alert-success"> 

Jak vypsat jejich spotřebu a hmotnost?
    
</div>

<div class="alert alert-block alert-danger"> 

Příkaz **select** vybírá sloupce podle názvů a tvoří tak novou tabulku.
    
</div>

In [7]:
mtcars |> filter(hp > 200) |> select(mpg, wt)

                    mpg  wt
Duster 360          14.3 3.570
Cadillac Fleetwood  10.4 5.250
Lincoln Continental 10.4 5.424
Chrysler Imperial   14.7 5.345
Camaro Z28          13.3 3.840
Ford Pantera L      15.8 3.170
Maserati Bora       15.0 3.570

<div class="alert alert-block alert-success"> 

Jak vybrat sloupce začínající na 'c', končící na 't' a obsahující 'a'?
    
</div>

<div class="alert alert-block alert-danger"> 

Výběroví pomocníci **starts_with**, **ends_with**, **contains** definují podmínky pro začátek, konec a nebo obsah názvu sloupců.
    
</div>

In [8]:
mtcars  |> select(starts_with("c"), ends_with("t"), contains("a"))

                    cyl carb drat wt    am gear
Mazda RX4           6   4    3.90 2.620 1  4
Mazda RX4 Wag       6   4    3.90 2.875 1  4
Datsun 710          4   1    3.85 2.320 1  4
Hornet 4 Drive      6   1    3.08 3.215 0  3
Hornet Sportabout   8   2    3.15 3.440 0  3
Valiant             6   1    2.76 3.460 0  3
Duster 360          8   4    3.21 3.570 0  3
Merc 240D           4   2    3.69 3.190 0  4
Merc 230            4   2    3.92 3.150 0  4
Merc 280            6   4    3.92 3.440 0  4
Merc 280C           6   4    3.92 3.440 0  4
Merc 450SE          8   3    3.07 4.070 0  3
Merc 450SL          8   3    3.07 3.730 0  3
Merc 450SLC         8   3    3.07 3.780 0  3
Cadillac Fleetwood  8   4    2.93 5.250 0  3
Lincoln Continental 8   4    3.00 5.424 0  3
Chrysler Imperial   8   4    3.23 5.345 0  3
Fiat 128            4   1    4.08 2.200 1  4
Honda Civic         4   2    4.93 1.615 1  4
Toyota Corolla      4   1    4.22 1.835 1  4
Toyota Corona       4   1    3.70 2.465 0  3
Dodge Challenger    8   2    2.76 3.520 0  3
AMC Javelin         8   2    3.15 3.435 0  3
Camaro Z28          8   4    3.73 3.840 0  3
Pontiac Firebird    8   2    3.08 3.845 0  3
Fiat X1-9           4   1    4.08 1.935 1  4
Porsche 914-2       4   2    4.43 2.140 1  5
Lotus Europa        4   2    3.77 1.513 1  5
Ford Pantera L      8   4    4.22 3.170 1  5
Ferrari Dino        6   6    3.62 2.770 1  5
Maserati Bora       8   8    3.54 3.570 1  5
Volvo 142E          4   2    4.11 2.780 1  4

<div class="alert alert-block alert-success"> 

Jak zařadit sloupce *mpg* a *hp* na začátek a ostatní sloupce ponechat.
    
</div>

<div class="alert alert-block alert-danger"> 

Příkaz **everything** ponechává ostatní sloupce při přeuspořádání.
    
</div>

In [9]:
mtcars |> select(mpg, hp, everything())

                    mpg  hp  cyl disp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 110 6   160.0 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 110 6   160.0 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8  93 4   108.0 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 110 6   258.0 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 175 8   360.0 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 105 6   225.0 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 245 8   360.0 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4  62 4   146.7 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8  95 4   140.8 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 123 6   167.6 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 123 6   167.6 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 180 8   275.8 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 180 8   275.8 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 180 8   275.8 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 205 8   472.0 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 215 8   460.0 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 230 8   440.0 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4  66 4    78.7 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4  52 4    75.7 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9  65 4    71.1 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5  97 4   120.1 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 150 8   318.0 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 150 8   304.0 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 245 8   350.0 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 175 8   400.0 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3  66 4    79.0 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0  91 4   120.3 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 113 4    95.1 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 264 8   351.0 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 175 6   145.0 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 335 8   301.0 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 109 4   121.0 4.11 2.780 18.60 1  1  4    2

<div class="alert alert-block alert-success"> 

Jak vytáhnout hodnoty sloupce *hp* do samostatného vektoru?
    
</div>

<div class="alert alert-block alert-danger"> 

Příkaz **pull** extrahuje hodnoty sloupce do samostatného vektoru.
    
</div>

In [10]:
# vytahne podtabulku
mtcars |> select(hp)

                    hp
Mazda RX4           110
Mazda RX4 Wag       110
Datsun 710           93
Hornet 4 Drive      110
Hornet Sportabout   175
Valiant             105
Duster 360          245
Merc 240D            62
Merc 230             95
Merc 280            123
Merc 280C           123
Merc 450SE          180
Merc 450SL          180
Merc 450SLC         180
Cadillac Fleetwood  205
Lincoln Continental 215
Chrysler Imperial   230
Fiat 128             66
Honda Civic          52
Toyota Corolla       65
Toyota Corona        97
Dodge Challenger    150
AMC Javelin         150
Camaro Z28          245
Pontiac Firebird    175
Fiat X1-9            66
Porsche 914-2        91
Lotus Europa        113
Ford Pantera L      264
Ferrari Dino        175
Maserati Bora       335
Volvo 142E          109

In [11]:
#vytahne hodnoty
mtcars |> pull(hp)

 [1] 110 110  93 110 175 105 245  62  95 123 123 180 180 180 205 215 230  66  52
[20]  65  97 150 150 245 175  66  91 113 264 175 335 109

<div class="alert alert-block alert-success"> 

Jak vytvořit nový sloupec *p.ratio*, který bude popisovat poměr výkon/objem a sloupec *ecol.ratio*, který bude popisovat poměr výkon/spotřeba?
    
</div>

<div class="alert alert-block alert-danger"> 

Příkaz **mutate** mění některé proměnné nebo vytváří nové a přidává je do tabulky.
    
</div>

<div>
<img src="https://raw.githubusercontent.com/JanKolacek/figs/refs/heads/main/mutate.png" width="500"/>
</div>

In [ ]:
mtcars |> mutate(p.ratio = hp / disp, ecol.ratio = hp / mpg)

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2
                    p.ratio   ecol.ratio
Mazda RX4           0.6875000  5.238095
Mazda RX4 Wag       0.6875000  5.238095
Datsun 710          0.8611111  4.078947
Hornet 4 Drive      0.4263566  5.140187
Hornet Sportabout   0.4861111  9.358289
Valiant             0.4666667  5.801105
Duster 360          0.6805556 17.132867
Merc 240D           0.4226312  2.540984
Merc 230            0.6747159  4.166667
Merc 280            0.7338902  6.406250
Merc 280C           0.7338902  6.910112
Merc 450SE          0.6526468 10.975610
Merc 450SL          0.6526468 10.404624
Merc 450SLC         0.6526468 11.842105
Cadillac Fleetwood  0.4343220 19.711538
Lincoln Continental 0.4673913 20.673077
Chrysler Imperial   0.5227273 15.646259
Fiat 128            0.8386277  2.037037
Honda Civic         0.6869221  1.710526
Toyota Corolla      0.9142053  1.917404
Toyota Corona       0.8076603  4.511628
Dodge Challenger    0.4716981  9.677419
AMC Javelin         0.4934211  9.868421
Camaro Z28          0.7000000 18.421053
Pontiac Firebird    0.4375000  9.114583
Fiat X1-9           0.8354430  2.417582
Porsche 914-2       0.7564422  3.500000
Lotus Europa        1.1882229  3.717105
Ford Pantera L      0.7521368 16.708861
Ferrari Dino        1.2068966  8.883249
Maserati Bora       1.1129568 22.333333
Volvo 142E          0.9008264  5.093458

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

<div class="alert alert-block alert-success"> 

Jak vytvořit totéž, ale jen pro auta s výkonem větším než 200 koní?
    
</div>

In [13]:
mtcars |>  filter(hp > 200)  |>  mutate(p.ratio = hp / disp, ecol.ratio = hp / mpg)

                    mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Duster 360          14.3 8   360  245 3.21 3.570 15.84 0  0  3    4
Cadillac Fleetwood  10.4 8   472  205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460  215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440  230 3.23 5.345 17.42 0  0  3    4
Camaro Z28          13.3 8   350  245 3.73 3.840 15.41 0  0  3    4
Ford Pantera L      15.8 8   351  264 4.22 3.170 14.50 0  1  5    4
Maserati Bora       15.0 8   301  335 3.54 3.570 14.60 0  1  5    8
                    p.ratio   ecol.ratio
Duster 360          0.6805556 17.13287
Cadillac Fleetwood  0.4343220 19.71154
Lincoln Continental 0.4673913 20.67308
Chrysler Imperial   0.5227273 15.64626
Camaro Z28          0.7000000 18.42105
Ford Pantera L      0.7521368 16.70886
Maserati Bora       1.1129568 22.33333

<div class="alert alert-block alert-success"> 

Přejmenujte sloupec *hp* na *horse_power* pomocí **rename**.
    
</div>

In [14]:
mtcars  |> rename(horse_power = hp)

                    mpg  cyl disp  horse_power drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110         3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110         3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93         3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110         3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175         3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105         2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245         3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62         3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95         3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123         3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123         3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180         3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180         3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180         3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205         2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215         3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230         3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66         4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52         4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65         4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97         3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150         2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150         3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245         3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175         3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66         4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91         4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113         3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264         4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175         3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335         3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109         4.11 2.780 18.60 1  1  4    2

<div class="alert alert-block alert-success"> 

Vytvořte nový sloupec *kategorie_vykonu*, který bude mít hodnoty *Weak* pro výkon menší než 100, *Medium* pro výkon mezi 100 a 200 a *Strong* pro výkon větší než 200. Použijte funkci **case_when**.
    
</div>

In [15]:
mtcars  |>  mutate(kategorie_vykonu = case_when(hp < 100 ~ "weak", between(hp, 100, 200) ~ "medium", TRUE ~ "strong"))

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2
                    kategorie_vykonu
Mazda RX4           medium
Mazda RX4 Wag       medium
Datsun 710          weak
Hornet 4 Drive      medium
Hornet Sportabout   medium
Valiant             medium
Duster 360          strong
Merc 240D           weak
Merc 230            weak
Merc 280            medium
Merc 280C           medium
Merc 450SE          medium
Merc 450SL          medium
Merc 450SLC         medium
Cadillac Fleetwood  strong
Lincoln Continental strong
Chrysler Imperial   strong
Fiat 128            weak
Honda Civic         weak
Toyota Corolla      weak
Toyota Corona       weak
Dodge Challenger    medium
AMC Javelin         medium
Camaro Z28          strong
Pontiac Firebird    medium
Fiat X1-9           weak
Porsche 914-2       weak
Lotus Europa        medium
Ford Pantera L      strong
Ferrari Dino        medium
Maserati Bora       strong
Volvo 142E          medium

<div class="alert alert-block alert-success"> 

Jak zjistit průměrné *ecol.ratio* pro automobily s příslušným počtem válců?
    
</div>

<div class="alert alert-block alert-danger"> 

Parametr **.by** rozdělí data do příslušných skupin a provede se operace v těchto skupinách.
    
</div>

In [16]:
mtcars |> mutate(ecol.ratio = hp / mpg) |> mutate(mean.ecol.ratio = mean(ecol.ratio), .by = cyl)  |> select(cyl, ecol.ratio, mean.ecol.ratio)

                    cyl ecol.ratio mean.ecol.ratio
Mazda RX4           6    5.238095   6.231013
Mazda RX4 Wag       6    5.238095   6.231013
Datsun 710          4    4.078947   3.244667
Hornet 4 Drive      6    5.140187   6.231013
Hornet Sportabout   8    9.358289  14.419146
Valiant             6    5.801105   6.231013
Duster 360          8   17.132867  14.419146
Merc 240D           4    2.540984   3.244667
Merc 230            4    4.166667   3.244667
Merc 280            6    6.406250   6.231013
Merc 280C           6    6.910112   6.231013
Merc 450SE          8   10.975610  14.419146
Merc 450SL          8   10.404624  14.419146
Merc 450SLC         8   11.842105  14.419146
Cadillac Fleetwood  8   19.711538  14.419146
Lincoln Continental 8   20.673077  14.419146
Chrysler Imperial   8   15.646259  14.419146
Fiat 128            4    2.037037   3.244667
Honda Civic         4    1.710526   3.244667
Toyota Corolla      4    1.917404   3.244667
Toyota Corona       4    4.511628   3.244667
Dodge Challenger    8    9.677419  14.419146
AMC Javelin         8    9.868421  14.419146
Camaro Z28          8   18.421053  14.419146
Pontiac Firebird    8    9.114583  14.419146
Fiat X1-9           4    2.417582   3.244667
Porsche 914-2       4    3.500000   3.244667
Lotus Europa        4    3.717105   3.244667
Ford Pantera L      8   16.708861  14.419146
Ferrari Dino        6    8.883249   6.231013
Maserati Bora       8   22.333333  14.419146
Volvo 142E          4    5.093458   3.244667

<div class="alert alert-block alert-danger"> 

Alternativa k **.by** je příkaz **group_by** v kombinaci s **ungroup**.
    
</div>

In [17]:
mtcars |> mutate(ecol.ratio = hp / mpg) |> 
    group_by(cyl) |> 
    mutate(mean.ecol.ratio = mean(ecol.ratio))  |> 
    ungroup() |> 
    select(cyl, ecol.ratio, mean.ecol.ratio)

   cyl ecol.ratio mean.ecol.ratio
1  6    5.238095   6.231013
2  6    5.238095   6.231013
3  4    4.078947   3.244667
4  6    5.140187   6.231013
5  8    9.358289  14.419146
6  6    5.801105   6.231013
7  8   17.132867  14.419146
8  4    2.540984   3.244667
9  4    4.166667   3.244667
10 6    6.406250   6.231013
11 6    6.910112   6.231013
12 8   10.975610  14.419146
13 8   10.404624  14.419146
14 8   11.842105  14.419146
15 8   19.711538  14.419146
16 8   20.673077  14.419146
17 8   15.646259  14.419146
18 4    2.037037   3.244667
19 4    1.710526   3.244667
20 4    1.917404   3.244667
21 4    4.511628   3.244667
22 8    9.677419  14.419146
23 8    9.868421  14.419146
24 8   18.421053  14.419146
25 8    9.114583  14.419146
26 4    2.417582   3.244667
27 4    3.500000   3.244667
28 4    3.717105   3.244667
29 8   16.708861  14.419146
30 6    8.883249   6.231013
31 8   22.333333  14.419146
32 4    5.093458   3.244667

<div class="alert alert-block alert-warning"> 

Porovnejte výsledky obou předchozích příkazů.
    
</div>

<div class="alert alert-block alert-success"> 

Jak spočítat průměr pro každý řádek mezi sloupci *disp* a *hp*?
    
</div>

<div class="alert alert-block alert-danger"> 

Příkaz **rowwise** přepíná výpočty ze sloupcového režimu na řádkový. Opět musíme zrušit řádkové seskupení pomocí **ungroup**.
    
</div>

In [18]:
head(mtcars)

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

<div class="alert alert-block alert-warning"> 

Místo posledního příkazu **mutate** zadejte **reframe** a porovnejte rozdíl.
    
</div>

<div class="alert alert-block alert-danger"> 

Příkaz **reframe** vytváří úplně novou tabulku. V dřívějších verzích je ekvivalentní příkaz **summarise**.
    
</div>

<div>
<img src="https://raw.githubusercontent.com/JanKolacek/figs/refs/heads/main/reframe.png" width="500"/>
</div>

<div class="alert alert-block alert-success"> 

Jak vytvořit novou tabulku, která bude mít sloupce *mean.disp* - průměrný objem válců a *count* - počet automobilů pro daný počet válců?
    
</div>

<div class="alert alert-block alert-danger"> 

Parametr **.by** lze nahradit příkazem **group_by**.
    
</div>

<div>
<img src="https://raw.githubusercontent.com/JanKolacek/figs/refs/heads/main/group_by.png" width="500"/>
</div>

<div class="alert alert-block alert-success"> 

Jak provést totéž, ale abychom měli údaje rozdělené ještě podle typu převodovky?
    
</div>

<div class="alert alert-block alert-success"> 

Jak spočítat průměr pro více sloupců najednou (např. *mpg*, *hp*, *wt*) podle počtu válců?
    
</div>

<div class="alert alert-block alert-danger"> 

Funkce **accross** slouží k aplikování jedné nebo více funkcí na více sloupců najednou.
    
</div>

<div class="alert alert-block alert-success"> 

Jak vybrat pouze auta s automatickou převodovkou a seřadit je vzestupně podle počtu válců a sestupně podle spotřeby?
    
</div>

<div class="alert alert-block alert-danger"> 

Pořadí řádků v tabulce dle různých proměnných lze určit příkazem **arrange**.
    
</div>

<div>
<img src="https://raw.githubusercontent.com/JanKolacek/figs/refs/heads/main/arrange.png" width="500"/>
</div>