# Cvičení 4

## Načtení dat

In [169]:
university_rankings = read.csv("QS_world_university_ranking_2027.csv")

## Průzkum tabulky

<div class="alert alert-block alert-success">

Zjistěte počet řádků a sloupců v tabulce.

<details>
<summary></summary>

1504 řádků, 30 sloupců

<details>
<summary></summary>

```r
nrow(university_rankings)
ncol(university_rankings)
```

*Alternativa:*

```r
dim(university_rankings)
```

</details>
</details>

In [170]:
nrow(university_rankings)
ncol(university_rankings)

[1] 1504

[1] 30

<div class="alert alert-block alert-success">

Vypište několik prvních řádků tabulky.

<details>
<summary></summary>

```r
head(university_rankings)
```

</details>

In [171]:
head(university_rankings)

  Index Rank Previous.Rank Name
1 1     1    1             Massachusetts Institute of Technology (MIT)
2 2     2    2             Imperial College London
3 3     2    3             Stanford University
4 4     4    4             University of Oxford
5 5     5    5             Harvard University
6 6     6    6             University of Cambridge
  Country.Territory        Region   Size Focus Research Status
1 United States of America Americas M    FO    VH       Private not for Profit
2 United Kingdom           Europe   L    CO    VH       Public
3 United States of America Americas L    FC    VH       Private not for Profit
4 United Kingdom           Europe   L    FC    VH       Public
5 United States of America Americas L    FC    VH       Private not for Profit
6 United Kingdom           Europe   L    FC    VH       Public
  ⋯ ISR.SCORE ISR.RANK IRN.SCORE IRN.RANK EO.SCORE EO.RANK SUS.SCORE SUS.RANK
1 ⋯  91.1     170       94.4     105      100.0    4       93.2      43=
2 ⋯ 100.0     44        98.8     16        96.4    57      98.0      7=
3 ⋯  75.1     258       96.8     50       100.0    2       97.6      14
4 ⋯  98.6     87       100.0     1        100.0    3       97.4      15
5 ⋯  73.2     271       99.5     8        100.0    1       75.6      285=
6 ⋯  96.3     125       99.6     6        100.0    6       77.0      264=
  Overall.SCORE City
1 100           Cambridge
2 99.2          London
3 99.2          Stanford
4 98.6          Oxford
5 97.4          Cambridge
6 97.1          Cambridge

<div class="alert alert-block alert-success">

Vypište poslední tři řádky tabulky. Použijte funkci `tail()` se správným argumentem.

<details>
<summary></summary>

```r
tail(university_rankings, 3)
```

</details>

In [172]:
tail(university_rankings, n = 3)

     Index Rank  Previous.Rank Name                  Country.Territory Region
1502 1502  1401+ 1401+         Walailak University   Thailand          Asia
1503 1503  1401+ 1201-1400     Yessenov University   Kazakhstan        Asia
1504 1504  1401+ 1201-1400     Zarqa University (ZU) Jordan            Asia
     Size Focus Research Status                 ⋯ ISR.SCORE ISR.RANK IRN.SCORE
1502 L    FC    MD       Public                 ⋯  2.6      801+     33.9
1503 M    CO    MD       Public                 ⋯ 22.6      700       2.4
1504 M    FC    HI       Private not for Profit ⋯ 60.1      361      27.3
     IRN.RANK EO.SCORE EO.RANK SUS.SCORE SUS.RANK Overall.SCORE City
1502 801+     4.4      801+    56.3      719=     -             Thasala
1503 801+     6.2      801+    23.8      801+     -             Aktau
1504 801+     6.9      801+    27.0      801+     -             Zarqa

<div class="alert alert-block alert-success">

Vypište souhrnné informace o prvních 10 sloupcích tabulky pomocí funkce `summary()`.

<details>
<summary></summary>

```r
summary(university_rankings[, 1:10])
```

</details>

In [173]:
summary(university_rankings[, 1:10])

     Index               Rank        Previous.Rank         Name
 Min.   :   1.0   Length   :1504   Length   :1504   Length   :1504
 1st Qu.: 376.8   N.unique : 399   N.unique : 398   N.unique :1504
 Median : 752.5   N.blank  :   0   N.blank  :  98   N.blank  :   0
 Mean   : 752.5   Min.nchar:   1   Min.nchar:   0   Min.nchar:   3
 3rd Qu.:1128.2   Max.nchar:   9   Max.nchar:   9   Max.nchar: 117
 Max.   :1504.0
 Country.Territory       Region            Size            Focus
 Length   :1504    Length   :1504   Length   :1504   Length   :1504
 N.unique : 106    N.unique :   5   N.unique :   5   N.unique :   5
 N.blank  :   0    N.blank  :   0   N.blank  :   5   N.blank  :   1
 Min.nchar:   4    Min.nchar:   4   Min.nchar:   0   Min.nchar:   0
 Max.nchar:  34    Max.nchar:   8   Max.nchar:   2   Max.nchar:   2

      Research          Status
 Length   :1504   Length   :1504
 N.unique :   5   N.unique :   4
 N.blank  :   7   N.blank  :  56
 Min.nchar:   0   Min.nchar:   0
 Max.nchar:   2   Max.nchar:  22

<div class="alert alert-block alert-success">

Vypište datové typy všech sloupců v tabulce. Použijte funkci `str()`.

<details>
<summary></summary>

```r
str(university_rankings)
```

</details>

In [174]:
str(university_rankings)

'data.frame':	1504 obs. of  30 variables:
 $ Index            : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Rank             : chr  "1" "2" "2" "4" ...
 $ Previous.Rank    : chr  "1" "2" "3" "4" ...
 $ Name             : chr  "Massachusetts Institute of Technology (MIT)" "Imperial College London" "Stanford University" "University of Oxford" ...
 $ Country.Territory: chr  "United States of America" "United Kingdom" "United States of America" "United Kingdom" ...
 $ Region           : chr  "Americas" "Europe" "Americas" "Europe" ...
 $ Size             : chr  "M" "L" "L" "L" ...
 $ Focus            : chr  "FO" "CO" "FC" "FC" ...
 $ Research         : chr  "VH" "VH" "VH" "VH" ...
 $ Status           : chr  "Private not for Profit" "Public" "Private not for Profit" "Public" ...
 $ AR.SCORE         : num  100 99.6 100 100 100 100 97.4 99.8 99.9 100 ...
 $ AR.RANK          : chr  "4" "22" "5" "2" ...
 $ ER.SCORE         : num  100 100 100 100 100 100 99.6 97.7 99.7 99.1 ...
 $ ER.RANK          : chr  "2" "9" "3" "4" ...
 $ FSR.SCORE        : num  100 98.9 100 100 97.4 100 100 65 90.3 75.3 ...
 $ FSR.RANK         : chr  "17" "44" "13" "8" ...
 $ CPF.SCORE        : num  100 93.8 98.8 89 100 87.4 100 98.8 86.1 93.5 ...
 $ CPF.RANK         : chr  "14" "81" "39" "113" ...
 $ IFR.SCORE        : num  100 100 97.9 98.7 86.1 100 100 100 99.3 100 ...
 $ IFR.RANK         : chr  "65" "86" "147" "138" ...
 $ ISR.SCORE        : num  91.1 100 75.1 98.6 73.2 96.3 92.2 99.5 100 98.5 ...
 $ ISR.RANK         : chr  "170" "44" "258" "87" ...
 $ IRN.SCORE        : num  94.4 98.8 96.8 100 99.5 99.6 64.1 96.7 99.9 92.5 ...
 $ IRN.RANK         : chr  "105" "16" "50" "1" ...
 $ EO.SCORE         : num  100 96.4 100 100 100 100 95.4 95.2 85.6 100 ...
 $ EO.RANK          : chr  "4" "57" "2" "3" ...
 $ SUS.SCORE        : num  93.2 98 97.6 97.4 75.6 77 77 97.7 98.9 91.6 ...
 $ SUS.RANK         : chr  "43=" "7=" "14" "15" ...
 $ Overall.SCORE    : chr  "100" "99.2" "99.2" "98.6" ...
 $ City             : chr  "Cambridge" "London" "Stanford" "Oxford" ...

<div class="alert alert-block alert-warning">

Jaký datový typ byste očekávali u sloupce **Rank**?

<details>
<summary></summary>

numeric

</details>

num

<div class="alert alert-block alert-warning">

Jaký datový typ byste očekávali u sloupce **Overall.Score**?

<details>
<summary></summary>

numeric

</details>

num

<div class="alert alert-block alert-warning">

Jaký datový typ byste očekávali u sloupce **Status**?

<details>
<summary></summary>

factor

</details>

faktor

<div class="alert alert-block alert-warning">

Jaký datový typ byste očekávali u sloupce **Size**?

<details>
<summary></summary>

ordered factor

</details>

ordered faktor

<div class="alert alert-block alert-success">

Změňte vhodné sloupce na datový typ **faktor**, příp. **ordered factor**.

<details>
<summary></summary>


**Country.Territory**, **Region**, **Focus**, **Research**, **Status**, **City** → factor

**Size** → ordered factor

<details>
<summary></summary>

```r
university_rankings$Country.Territory <- factor(university_rankings$Country.Territory)

university_rankings$Region <- factor(university_rankings$Region)

university_rankings$Size <- factor(university_rankings$Size, ordered = TRUE, levels = c("S", "M", "L", "XL"))

university_rankings$Focus <- factor(university_rankings$Focus)

university_rankings$Research <- factor(university_rankings$Research)

university_rankings$Status <- factor(university_rankings$Status)

university_rankings$City <- factor(university_rankings$City)
```

*Elegantnější řešení pomocí funkce `lapply()`:*

```r
col_names_to_factor <- c("Country.Territory", "Region", "Size", "Focus", "Research", "Status", "City")

university_rankings[, col_names_to_factor] <- lapply(university_rankings[, col_names_to_factor] , factor)

university_rankings$Size <- factor(university_rankings$Size, ordered = TRUE, levels = c("S", "M", "L", "XL"))
```

</details>
</details>

In [175]:
head(university_rankings, n = 2)
university_rankings$Country.Territory <- factor(university_rankings$Country.Territory)
university_rankings$Region <- factor(university_rankings$Region)
university_rankings$Focus <- factor(university_rankings$Focus)
university_rankings$Research <- factor(university_rankings$Research)
university_rankings$Status <- factor(university_rankings$Status)
university_rankings$City <- factor(university_rankings$City)
university_rankings$Focus <- factor(university_rankings$Focus)

university_rankings$Size <- factor(university_rankings$Size, ordered = TRUE, levels = c("S", "M", "L", "XL"))

  Index Rank Previous.Rank Name
1 1     1    1             Massachusetts Institute of Technology (MIT)
2 2     2    2             Imperial College London
  Country.Territory        Region   Size Focus Research Status
1 United States of America Americas M    FO    VH       Private not for Profit
2 United Kingdom           Europe   L    CO    VH       Public
  ⋯ ISR.SCORE ISR.RANK IRN.SCORE IRN.RANK EO.SCORE EO.RANK SUS.SCORE SUS.RANK
1 ⋯  91.1     170      94.4      105      100.0    4       93.2      43=
2 ⋯ 100.0     44       98.8      16        96.4    57      98.0      7=
  Overall.SCORE City
1 100           Cambridge
2 99.2          London

<div class="alert alert-block alert-success">

Proč se sloupce **Rank**, **Overall.SCORE**, apod. načetly jako **character** namísto **numeric**?

<details>
<summary></summary>

Ve sloupcích existují nenumerické hodnoty.

<details>
<summary></summary>

```
tail(university_rankings)

rev(sort(table(university_rankings$Rank)))
```

</details>
</details>

In [176]:
#protoze ve sloupcich jsou i nenumericke hodnoty

<div class="alert alert-block alert-success">

Převeďte sloupce **Rank**, **Previous.Rank** a **Overall.SCORE** na datový typ **numeric**.

<details>
<summary></summary>

```r
university_rankings$Rank <- as.numeric(university_rankings$Rank)

university_rankings$Previous.Rank <- as.numeric(university_rankings$Previous.Rank)

university_rankings$Overall.SCORE <- as.numeric(university_rankings$Overall.SCORE)
```

</details>

In [177]:
university_rankings$Rank <- as.numeric(university_rankings$Rank)
university_rankings$Previous.Rank <- as.numeric(university_rankings$Previous.Rank)
university_rankings$Overell.SCORE <- as.numeric(university_rankings$Overell.SCORE)

Warning message:
"NAs introduced by coercion"
Warning message:
"NAs introduced by coercion"

ERROR: Error in `$<-.data.frame`(`*tmp*`, Overell.SCORE, value = numeric(0)): replacement has 0 rows, data has 1504

<div class="alert alert-block alert-warning">

Proč kód vypisuje warning?

<details>
<summary></summary>

Kvůli převodu některých hodnot na NA.

</details>

protoze tam jsou i NA

## Chybějící pozorování

<div class="alert alert-block alert-success">

Chybí nějaká data v tabulce? Pokud ano, v kolika buňkách?

<details>
<summary></summary>

Ano, v 2 580 buňkách.

<details>
<summary></summary>

```r
sum(is.na(university_rankings))
```

</details>
</details>

In [ ]:
sum(is.na(university_rankings))

[1] 1776

<div class="alert alert-block alert-success">

Ve kterých řádcích data chybějí? O kolik řádků se jedná?

<details>
<summary></summary>

839 řádků

65, 97, 239, 361, 507, 516, 533, 542, 560, 564, ..., 1502, 1503, 1504

<details>
<summary></summary>

```r
which(rowSums(is.na(university_rankings)) > 0)

sum(rowSums(is.na(university_rankings)) > 0)
```

</details>
</details>

In [ ]:
which(rowSums(is.na(university_rankings)) > 0)
sum(rowSums(is.na(university_rankings)) > 0)

  [1]   65   97  239  361  507  516  533  542  560  564  569  583  627  635  638
 [16]  641  643  647  648  649  652  658  659  666  668  669  675  677  679  680
 [31]  686  692  697  699  700  701  702  703  704  705  706  707  708  709  710
 [46]  711  712  713  714  715  716  717  718  719  720  721  722  723  724  725
 [61]  726  727  728  729  730  731  732  733  734  735  736  737  738  739  740
 [76]  741  742  743  744  745  746  747  748  749  750  751  752  753  754  755
 [91]  756  757  758  759  760  761  762  763  764  765  766  767  768  769  770
[106]  771  772  773  774  775  776  777  778  779  780  781  782  783  784  785
[121]  786  787  788  789  790  791  792  793  794  795  796  797  798  799  800
[136]  801  802  803  804  805  806  807  808  809  810  811  812  813  814  815
[151]  816  817  818  819  820  821  822  823  824  825  826  827  828  829  830
[166]  831  832  833  834  835  836  837  838  839  840  841  842  843  844  845
[181]  846  847  848  849  850  851  852  853  854  855  856  857  858  859  860
[196]  861  862  863  864  865  866  867  868  869  870  871  872  873  874  875
[211]  876  877  878  879  880  881  882  883  884  885  886  887  888  889  890
[226]  891  892  893  894  895  896  897  898  899  900  901  902  903  904  905
[241]  906  907  908  909  910  911  912  913  914  915  916  917  918  919  920
[256]  921  922  923  924  925  926  927  928  929  930  931  932  933  934  935
[271]  936  937  938  939  940  941  942  943  944  945  946  947  948  949  950
[286]  951  952  953  954  955  956  957  958  959  960  961  962  963  964  965
[301]  966  967  968  969  970  971  972  973  974  975  976  977  978  979  980
[316]  981  982  983  984  985  986  987  988  989  990  991  992  993  994  995
[331]  996  997  998  999 1000 1001 1002 1003 1004 1005 1006 1007 1008 1009 1010
[346] 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025
[361] 1026 1027 1028 1029 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040
[376] 1041 1042 1043 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055
[391] 1056 1057 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070
[406] 1071 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084 1085
[421] 1086 1087 1088 1089 1090 1091 1092 1093 1094 1095 1096 1097 1098 1099 1100
[436] 1101 1102 1103 1104 1105 1106 1107 1108 1109 1110 1111 1112 1113 1114 1115
[451] 1116 1117 1118 1119 1120 1121 1122 1123 1124 1125 1126 1127 1128 1129 1130
[466] 1131 1132 1133 1134 1135 1136 1137 1138 1139 1140 1141 1142 1143 1144 1145
[481] 1146 1147 1148 1149 1150 1151 1152 1153 1154 1155 1156 1157 1158 1159 1160
[496] 1161 1162 1163 1164 1165 1166 1167 1168 1169 1170 1171 1172 1173 1174 1175
[511] 1176 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190
[526] 1191 1192 1193 1194 1195 1196 1197 1198 1199 1200 1201 1202 1203 1204 1205
[541] 1206 1207 1208 1209 1210 1211 1212 1213 1214 1215 1216 1217 1218 1219 1220
[556] 1221 1222 1223 1224 1225 1226 1227 1228 1229 1230 1231 1232 1233 1234 1235
[571] 1236 1237 1238 1239 1240 1241 1242 1243 1244 1245 1246 1247 1248 1249 1250
[586] 1251 1252 1253 1254 1255 1256 1257 1258 1259 1260 1261 1262 1263 1264 1265
[601] 1266 1267 1268 1269 1270 1271 1272 1273 1274 1275 1276 1277 1278 1279 1280
[616] 1281 1282 1283 1284 1285 1286 1287 1288 1289 1290 1291 1292 1293 1294 1295
[631] 1296 1297 1298 1299 1300 1301 1302 1303 1304 1305 1306 1307 1308 1309 1310
[646] 1311 1312 1313 1314 1315 1316 1317 1318 1319 1320 1321 1322 1323 1324 1325
[661] 1326 1327 1328 1329 1330 1331 1332 1333 1334 1335 1336 1337 1338 1339 1340
[676] 1341 1342 1343 1344 1345 1346 1347 1348 1349 1350 1351 1352 1353 1354 1355
[691] 1356 1357 1358 1359 1360 1361 1362 1363 1364 1365 1366 1367 1368 1369 1370
[706] 1371 1372 1373 1374 1375 1376 1377 1378 1379 1380 1381 1382 1383 1384 1385
[721] 1386 1387 1388 1389 1390 1391 1392 1393 1394 1395 1396 1397 1398 1399 1400
[736] 1401 1402 1403 1404 1405 1406 1407 1408 1409 1410 1411 1412 1413 1414 1415
[751] 1416 1417 1418 1419 1420 1421 1422 1423 1424 1425 1426 1427 1428 1429 1430
[766] 1431 1432 1433 1434 1435 1436 1437 1438 1439 1440 1441 1442 1443 1444 1445
[781] 1446 1447 1448 1449 1450 1451 1452 1453 1454 1455 1456 1457 1458 1459 1460
[796] 1461 1462 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1473 1474 1475
[811] 1476 1477 1478 1479 1480 1481 1482 1483 1484 1485 1486 1487 1488 1489 1490
[826] 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502 1503 1504

[1] 839

<div class="alert alert-block alert-success">

Odstraňte řádky s chybějícími hodnotami. Použijte funkci `na.omit()`.

<details>
<summary></summary>

```r
university_rankings_clean <- na.omit(university_rankings)
```

</details>

In [ ]:
university_rankings_clean <- na.omit(university_rankings)

<div class="alert alert-block alert-danger">

Pokud tabulku výrazně upravujeme - například z ní mažeme data - není vhodné ji uložit pod stejným jménem jako původní tabulku a tím přepsat původní data.

<div class="alert alert-block alert-success">

Odstraňte z tabulky sloupce **.Rank** kromě **Previous.Rank**.

<details>
<summary></summary>

```r
university_rankings_clean[
    , c(
        "AR.RANK",
        "ER.RANK",
        "FSR.RANK",
        "CPF.RANK",
        "ISR.RANK",
        "IFR.RANK",
        "IRN.RANK",
        "EO.RANK",
        "SUS.RANK"
    )
] <- NULL
```

</details>

In [ ]:
university_rankings_clean[ c("AR.RANK", "ER.RANK", "FSR.RANK", "CPF.RANK", "ISR.RANK", "IRN.RANK", "EO.RANK", "SUS.RANK")] <- NULL

<div class="alert alert-block alert-success">

Zkontrolujte, zda je v tabulce opravdu méně sloupců.

<details>
<summary></summary>

```r
ncol(university_rankings)
ncol(university_rankings_clean)
```

</details>

In [ ]:
ncol(university_rankings_clean)
ncol(university_rankings)

[1] 22

[1] 30

[1] 665

<div class="alert alert-block alert-success">

Chybějí v tabulce ještě nějaké hodnoty? Co například textové buňky obsahující prázdný string?

<details>
<summary></summary>

2 buňky obsahují prázdný string `""`

<details>
<summary></summary>

```r
sum(university_rankings_clean == "")
```

</details>
</details>

In [ ]:
sum(is.na(university_rankings_clean))
sum(university_rankings_clean == "")

[1] 0

[1] 2

<div class="alert alert-block alert-success">

Odstraňte řádky obsahující prázdný string. Kolik řádků zbývá?

<details>
<summary></summary>

633 řádků

<details>
<summary></summary>

```r
rows_without_empty_string <- rowSums(university_rankings_clean == "") == 0
university_rankings_clean <- university_rankings_clean[rows_without_empty_string, ]
sum(university_rankings_clean == "")

nrow(university_rankings_clean)
```

</details>
</details>

In [ ]:
rows_without_empty_string <- rowSums(university_rankings_clean == "") == 0
university_rankings_clean <- university_rankings_clean[rows_without_empty_string, ]

nrow(university_rankings_clean)

[1] 663

<div class="alert alert-block alert-success">

Opakují se v datech některé řádky? Použijte funkci `duplicated()`.

<details>
<summary></summary>

Ne.

<details>
<summary></summary>

```r
sum(duplicated(university_rankings_clean))

sum(duplicated(university_rankings_clean)) == 0
```

</details>
</details>

In [ ]:
sum(duplicated(university_rankings_clean))

[1] 0

<div class="alert alert-block alert-success">

Jaké je zastoupení univerzit v rámci proměnné **Status**?

<details>
<summary></summary>

Private for Profit: 11

Private not for Profit: 105

Public: 547

<details>
<summary></summary>

```r
table(university_rankings_clean$Region)
```

</details>
</details>

In [ ]:
table(university_rankings_clean$Status)

                           Private for Profit Private not for Profit
                     0                     11                    105
                Public
                   547

<div class="alert alert-block alert-warning">

Proč se ve výsledku funkce `table()` v prvním elementu vyskytuje prázdný string s počtem výskytů 0?

<details>
<summary></summary>

Artefakt převodu na faktor. Při převodu sloupce **Status** na faktor v datech existovala chybějící pozorování (NA). Faktor pro ně tedy vytvořil novou kategorii, kterou uchovává, i když tyto řádky byly později odstraněny.
</details>

<div class="alert alert-block alert-success">

Odstraňte nepoužívané kategorie ze sloupce **Status**. Využít můžete funkce `droplevels()`. Zkontrolujte, zda odstranění kategorie proběhlo úspěšně.

<details>
<summary></summary>

```r
university_rankings_clean$Status <- droplevels(university_rankings_clean$Status)

levels(university_rankings_clean$Status)
```

</details>

In [ ]:
university_rankings_clean$Status <- droplevels(university_rankings_clean$Status)

levels(university_rankings_clean$Status)

[1] "Private for Profit"     "Private not for Profit" "Public"

<div class="alert alert-block alert-success">

Uložte vyčištěná data jako nový `.csv` soubor.

<details>
<summary></summary>

```r
write.csv(university_rankings_clean, "QS_world_university_ranking_2027_cleaned.csv")
```

</details>

In [ ]:
write.csv(university_rankings_clean, "QS_world_university_rankings_2027_cleaned.csv")

<div class="alert alert-block alert-danger">

Uložená vyčištěná data se Vám budou hodit při přípravě na písemku nebo při procvičování. Nemusíte při každém znovuotevření souboru data čistit a můžete pokračovat libovolným příkladem z následujících kapitol.

</details>

In [ ]:
university_rankings_clean <- read.csv("QS_world_university_rankings_2027_cleaned.csv")

## Tvorba nových sloupců

<div class="alert alert-block alert-success">

Vytvořte nový sloupec **Sum.Score**, který bude sumou všech **.SCORE** sloupců kromě **Overall.SCORE**. Můžete využít funkci `transform()`.

<details>
<summary></summary>

Pokud tvoříme nový sloupec, můžeme zachovat styl názvu ostatních sloupců, i když nejsou vhodně pojmenované.

```r
university_rankings_clean$Sum.SCORE <- university_rankings_clean$AR.SCORE +
    university_rankings_clean$ER.SCORE +
    university_rankings_clean$FSR.SCORE +
    university_rankings_clean$CPF.SCORE +
    university_rankings_clean$IFR.SCORE +
    university_rankings_clean$ISR.SCORE +
    university_rankings_clean$IRN.SCORE +
    university_rankings_clean$EO.SCORE +
    university_rankings_clean$SUS.SCORE
```

*Alternativa:*

```
university_rankings_clean <- transform(
    university_rankings_clean,
    Sum.SCORE = AR.SCORE + ER.SCORE + FSR.SCORE + CPF.SCORE + IFR.SCORE + ISR.SCORE + IRN.SCORE + EO.SCORE + SUS.SCORE
)
```

</details>

In [ ]:
colnames(university_rankings_clean)
uninversity_rankings_clean <- transform(university_rankings_clean, Sum.SCORE = AR.SCORE + ER.SCORE + FSR.SCORE + CPF.SCORE + IFR.SCORE + ISR.SCORE + IRN.SCORE + EO.SCORE + SUS.SCORE)

 [1] "X"                 "Index"             "Rank"
 [4] "Previous.Rank"     "Name"              "Country.Territory"
 [7] "Region"            "Size"              "Focus"
[10] "Research"          "Status"            "AR.SCORE"
[13] "ER.SCORE"          "FSR.SCORE"         "CPF.SCORE"
[16] "IFR.SCORE"         "IFR.RANK"          "ISR.SCORE"
[19] "IRN.SCORE"         "EO.SCORE"          "SUS.SCORE"
[22] "Overall.SCORE"     "City"

<div class="alert alert-block alert-success">

Zkontrolujte, zda pořadí univerzit seřazených dle **Overall.SCORE** a **Sum.SCORE** souhlasí. Využít můžete funkce `order()`.

<details>
<summary></summary>

Nesouhlasí.

<details>
<summary></summary>

```r
sum(order(university_rankings_clean$Sum.SCORE) != order(university_rankings_clean$Overall.SCORE)) == 0
```

*Alternativa:*

```r
sum(order(university_rankings_clean$Sum.SCORE) == order(university_rankings_clean$Overall.SCORE)) == nrow(university_rankings_clean)
```

*Alternativa:*

```r
all(order(university_rankings_clean$Sum.SCORE) == order(university_rankings_clean$Overall.SCORE))
```

</details>
</details>

In [ ]:
sum(ordered(uninversity_rankings_clean$Sum.SCORE) != order(university_rankings_clean$Overall.SCORE)) == 0

[1] FALSE

## Výběr řádků a sloupců

<div class="alert alert-block alert-success">

Vypište názvy všech univerzit.

<details>
<summary></summary>

```r
university_rankings_clean$Name
```

</details>

In [ ]:
university_rankings_clean$Name

  [1] "Massachusetts Institute of Technology (MIT)"
  [2] "Imperial College London"
  [3] "Stanford University"
  [4] "University of Oxford"
  [5] "Harvard University"
  [6] "University of Cambridge"
  [7] "California Institute of Technology (Caltech)"
  [8] "ETH Zurich"
  [9] "UCL"
 [10] "National University of Singapore (NUS)"
 [11] "The University of Hong Kong"
 [12] "Nanyang Technological University, Singapore (NTU Singapore)"
 [13] "Peking University"
 [14] "Tsinghua University"
 [15] "University of Pennsylvania"
 [16] "Cornell University"
 [17] "Yale University"
 [18] "The Chinese University of Hong Kong (CUHK)"
 [19] "The University of New South Wales (UNSW Sydney)"
 [20] "Johns Hopkins University"
 [21] "University of California, Berkeley (UCB)"
 [22] "EPFL – École polytechnique fédérale de Lausanne"
 [23] "The University of Melbourne"
 [24] "University of Chicago"
 [25] "Technical University of Munich"
 [26] "Fudan University"
 [27] "Princeton University"
 [28] "The University of Sydney"
 [29] "Australian National University (ANU)"
 [30] "McGill University"
 [31] "Monash University"
 [32] "University of Toronto"
 [33] "The Hong Kong University of Science and Technology"
 [34] "Université PSL"
 [35] "The University of Edinburgh"
 [36] "Shanghai Jiao Tong University"
 [37] "King's College London"
 [38] "Seoul National University"
 [39] "The University of Tokyo"
 [40] "The University of Manchester"
 [41] "The University of Queensland"
 [42] "Yonsei University"
 [43] "Columbia University"
 [44] "Institut Polytechnique de Paris"
 [45] "Northwestern University"
 [46] "University of British Columbia"
 [47] "Zhejiang University"
 [48] "Delft University of Technology"
 [49] "University of California, Los Angeles (UCLA)"
 [50] "The Hong Kong Polytechnic University"
 [51] "University of Michigan-Ann Arbor"
 [52] "City University of Hong Kong (CityUHK)"
 [53] "Korea University"
 [54] "National Taiwan University (NTU)"
 [55] "Carnegie Mellon University"
 [56] "Universiti Malaya (UM)"
 [57] "University of Bristol"
 [58] "New York University (NYU)"
 [59] "KU Leuven"
 [60] "University of Amsterdam"
 [61] "Ludwig-Maximilians-Universität München"
 [62] "The London School of Economics and Political Science (LSE)"
 [63] "KFUPM"
 [64] "Kyoto University"
 [65] "Brown University"
 [66] "The University of Auckland"
 [67] "The University of Warwick"
 [68] "University of Birmingham"
 [69] "Duke University"
 [70] "Lund University"
 [71] "University of Texas at Austin"
 [72] "Sorbonne University"
 [73] "University of Illinois Urbana-Champaign"
 [74] "Trinity College Dublin, The University of Dublin"
 [75] "Université Paris-Saclay"
 [76] "The University of Western Australia"
 [77] "University of Leeds"
 [78] "University of Glasgow"
 [79] "University of California, San Diego (UCSD)"
 [80] "KTH Royal Institute of Technology"
 [81] "The University of Sheffield"
 [82] "Universidad de Buenos Aires (UBA)"
 [83] "Durham University"
 [84] "Universität Heidelberg"
 [85] "Politecnico di Milano"
 [86] "University of Technology Sydney"
 [87] "Uppsala University"
 [88] "Nanjing University"
 [89] "University of Copenhagen"
 [90] "Pennsylvania State University"
 [91] "University of Washington"
 [92] "Boston University"
 [93] "The University of Osaka"
 [94] "University of Alberta"
 [95] "University of Nottingham"
 [96] "Freie Universitaet Berlin"
 [97] "University of Zurich"
 [98] "Purdue University"
 [99] "University College Dublin"
[100] "Tohoku University"
[101] "Queen Mary University of London"
[102] "RWTH Aachen University"
[103] "Technical University of Denmark"
[104] "Pohang University of Science And Technology (POSTECH)"
[105] "King Saud University"
[106] "Sungkyunkwan University (SKKU)"
[107] "Qatar University"
[108] "KIT, Karlsruhe Institute of Technology"
[109] "Sapienza University of Rome"
[110] "University of Southampton"
[111] "University of Waterloo"
[112] "Utrecht University"
[113] "Lomonosov Moscow State University"
[114] "University of St Andrews"
[115] "Indian Institute of Technology Delhi (IITD)"
[116] "Leiden University"
[117] "Pontificia Universidad Católica de Chile (UC)"
[118] "RMIT University"
[119] "Rice University"
[120] "Alma Mater Studiorum - Università di Bologna"
[121] "University of Helsinki"
[122] "University of Bath"
[123] "Aalto University"
[124] "Macquarie University (Sydney, Australia)"
[125] "Aarhus University"
[126] "Universiti Sains Malaysia (USM)"
[127] "Universiti Kebangsaan Malaysia (UKM)"
[128] "University of Oslo"
[129] "University of Wisconsin-Madison"
[130] "Universidade de São Paulo"
[131] "Indian Institute of Technology Bombay (IITB)"
[132] "University of Science and Technology of China"
[133] "University of Exeter"
[134] "University of California, Davis"
[135] "Universiti Putra Malaysia (UPM)"
[136] "University of Liverpool"
[137] "Humboldt-Universität zu Berlin"
[138] "University of Vienna"
[139] "Georgia Institute of Technology"
[140] "National Tsing Hua University - NTHU"
[141] "Western University"
[142] "Universidad Nacional Autónoma de México  (UNAM)"
[143] "Tongji University"
[144] "Khalifa University"
[145] "Erasmus University Rotterdam"
[146] "Newcastle University"
[147] "Ghent University"
[148] "University of Basel"
[149] "Eindhoven University of Technology"
[150] "University of Southern California"
[151] "Wageningen University & Research"
[152] "Hanyang University"
[153] "Nagoya University"
[154] "University of Groningen"
[155] "Technische Universität Berlin (TU Berlin)"
[156] "Universiti Teknologi Malaysia"
[157] "University of North Carolina at Chapel Hill"
[158] "University of York"
[159] "Université de Montréal"
[160] "Washington University in St. Louis"
[161] "Lancaster University"
[162] "Universitat de Barcelona"
[163] "Wuhan University"
[164] "Stockholm University"
[165] "University of Geneva"
[166] "Texas A&M University"
[167] "Indian Institute of Technology Madras (IITM)"
[168] "Kyushu University"
[169] "Arizona State University"
[170] "University of California, Santa Barbara (UCSB)"
[171] "Chalmers University of Technology"
[172] "McMaster University"
[173] "Queen's University Belfast"
[174] "Al-Farabi Kazakh National University"
[175] "National Yang Ming Chiao Tung University (NYCU Taiwan)"
[176] "Cardiff University"
[177] "Hokkaido University"
[178] "Queen's University at Kingston"
[179] "Michigan State University"
[180] "Emory University"
[181] "University of Cape Town"
[182] "Technische Universität Dresden"
[183] "Universidad de Chile"
[184] "Vrije Universiteit Amsterdam"
[185] "Tecnológico de Monterrey"
[186] "Curtin University"
[187] "Harbin Institute of Technology"
[188] "National Cheng Kung University (NCKU)"
[189] "Technische Universität Wien"
[190] "Universitas Indonesia"
[191] "University of Bern"
[192] "University of Wollongong"
[193] "Université catholique de Louvain (UCLouvain)"
[194] "University of Reading"
[195] "University of Otago"
[196] "Complutense University of Madrid"
[197] "King Abdulaziz University (KAU)"
[198] "The Ohio State University"
[199] "Waseda University"
[200] "Loughborough University"
[201] "Università di Padova"
[202] "Indian Institute of Technology Kharagpur (IIT-KGP)"
[203] "Gadjah Mada University"
[204] "Politecnico di Torino"
[205] "Tel Aviv University"
[206] "Rheinische Friedrich-Wilhelms-Universität Bonn"
[207] "Universität Hamburg"
[208] "Universitat Autònoma de Barcelona"
[209] "Chulalongkorn University"
[210] "Hamad Bin Khalifa University (HBKU)"
[211] "Keio University"
[212] "Massey University"
[213] "Hong Kong Baptist University"
[214] "United Arab Emirates University"
[215] "Friedrich-Alexander-Universität Erlangen-Nürnberg"
[216] "The Hebrew University of Jerusalem"
[217] "University College Cork"
[218] "Indian Institute of Science (IISc) Bangalore"
[219] "Indian Institute of Technology Kanpur (IITK)"
[220] "American University of Beirut (AUB)"
[221] "University of Twente"
[222] "University of Gothenburg"
[223] "Universidad Autónoma de Madrid"
[224] "Deakin University"
[225] "University of Florida"
[226] "University of Ottawa"
[227] "Eberhard Karls Universität Tübingen"
[228] "Griffith University"
[229] "University of Strathclyde"
[230] "Universidad de los Andes"
[231] "University of Lausanne"
[232] "École Normale Supérieure de Lyon"
[233] "Tianjin University"
[234] "Beijing Normal University"
[235] "University of Lisbon"
[236] "Queensland University of Technology (QUT)"
[237] "La Trobe University"
[238] "Victoria University of Wellington"
[239] "Beijing Institute of Technology"
[240] "The University of Newcastle, Australia (UON)"
[241] "Albert-Ludwigs-Universitaet Freiburg"
[242] "Université Paris 1 Panthéon-Sorbonne"
[243] "University of Surrey"
[244] "Universite libre de Bruxelles"
[245] "University of Calgary"
[246] "Technical University of Darmstadt"
[247] "University of Rochester"
[248] "University of California, Irvine"
[249] "University of Maryland, College Park"
[250] "Maastricht University"
[251] "University of Minnesota (System)"
[252] "University of Porto"
[253] "University of Canterbury | Te Whare Wānanga o Waitaha"
[254] "American University of Sharjah"
[255] "Sun Yat-sen University"
[256] "University of Massachusetts Amherst"
[257] "Universiti Teknologi PETRONAS (UTP)"
[258] "University of Göttingen"
[259] "Universitat Pompeu Fabra (Barcelona)"
[260] "Norwegian University of Science And Technology"
[261] "Vanderbilt University"
[262] "Singapore University of Technology and Design"
[263] "University of Macau"
[264] "University of Virginia"
[265] "University of Cologne"
[266] "Dartmouth College"
[267] "University of Milan"
[268] "Taylor's University"
[269] "Charles University"
[270] "University of Sussex"
[271] "University of Galway"
[272] "Universitas Airlangga"
[273] "Universidade Estadual de Campinas (Unicamp)"
[274] "University of Antwerp"
[275] "Istanbul Technical University"
[276] "University of Navarra"
[277] "University of Pittsburgh"
[278] "UCSI University"
[279] "Radboud University"
[280] "University of Bergen"
[281] "University of Sharjah"
[282] "University of Southern Denmark (SDU)"
[283] "Institut Teknologi Bandung (ITB)"
[284] "University of Aberdeen"
[285] "Georgetown University"
[286] "University of Warsaw"
[287] "Swinburne University of Technology"
[288] "University of Johannesburg"
[289] "Universidad Nacional de Colombia"
[290] "University of Waikato"
[291] "Vrije Universiteit Brussel (VUB)"
[292] "Stellenbosch University"
[293] "Xi’an Jiaotong University"
[294] "Dalhousie University"
[295] "Ulsan National Institute of Science and Technology (UNIST)"
[296] "Sichuan University"
[297] "University of Notre Dame"
[298] "University of Witwatersrand"
[299] "Université Paris Cité"
[300] "Xiamen University"
[301] "Middle East Technical University"
[302] "Sultan Qaboos University"
[303] "Huazhong University of Science and Technology"
[304] "Linköping University"
[305] "Kyung Hee University"
[306] "Shandong University"
[307] "University of Tasmania"
[308] "Simon Fraser University"
[309] "The University of Arizona"
[310] "Rutgers University–New Brunswick"
[311] "Universidad Carlos III de Madrid (UC3M)"
[312] "University of Leicester"
[313] "Southern University of Science and Technology (SUSTech)"
[314] "Bauman Moscow State Technical University"
[315] "Universität Stuttgart"
[316] "North Carolina State University"
[317] "University of Colorado Boulder"
[318] "Swansea University"
[319] "University of Delhi"
[320] "York University"
[321] "Heriot-Watt University"
[322] "Case Western Reserve University"
[323] "University of Jordan"
[324] "University of Pretoria"
[325] "Aalborg University"
[326] "Jagiellonian University"
[327] "Koç University"
[328] "Nankai University"
[329] "Universität Innsbruck"
[330] "Technion - Israel Institute of Technology"
[331] "Indian Institute of Technology Roorkee (IITR)"
[332] "Southeast University"
[333] "Universidade Nova de Lisboa"
[334] "L.N. Gumilyov Eurasian National University (ENU)"
[335] "Tufts University"
[336] "University of Miami"
[337] "University of Pisa"
[338] "South China University of Technology"
[339] "University of Coimbra"
[340] "University of Rome \"Tor Vergata\""
[341] "Boğaziçi University"
[342] "Mahidol University"
[343] "Universiti Brunei Darussalam (UBD)"
[344] "Abu Dhabi University"
[345] "Beihang University (former BUAA)"
[346] "Indian Institute of Technology Guwahati (IITG)"
[347] "Satbayev University"
[348] "University of Tsukuba"
[349] "Brunel University of London"
[350] "Birkbeck, University of London"
[351] "Sciences Po"
[352] "Sunway University"
[353] "Pontificia Universidad Catolica del Peru (PUCP)"
[354] "Sabanci University"
[355] "RUDN University"
[356] "Indiana University Bloomington"
[357] "University of Oulu"
[358] "Cairo University"
[359] "Universidad Politécnica de Madrid (UPM)"
[360] "Université de Liège"
[361] "Virginia Polytechnic Institute and State University"
[362] "Universidade Federal do Rio de Janeiro"
[363] "University of Tartu"
[364] "University of Tehran"
[365] "University of Illinois Chicago (UIC)"
[366] "University of Münster"
[367] "University of Victoria (UVic)"
[368] "Western Sydney University"
[369] "Flinders University"
[370] "Goethe-University Frankfurt am Main"
[371] "University of Luxembourg"
[372] "National Technical University of Athens"
[373] "Gwangju Institute of Science and Technology (GIST)"
[374] "National Taiwan University of Science and Technology (Taiwan Tech)"
[375] "George Washington University"
[376] "Quaid-i-Azam University"
[377] "University of East Anglia (UEA)"
[378] "National University of Sciences & Technology (NUST) Islamabad"
[379] "Daegu Gyeongbuk Institute of Science and Technology (DGIST)"
[380] "Northeastern University"
[381] "Université Grenoble Alpes"
[382] "Università Cattolica del Sacro Cuore"
[383] "University of Limerick"
[384] "LUT University"
[385] "Saint Petersburg State University"
[386] "Sharif University of Technology"
[387] "The American University in Cairo"
[388] "East China Normal University"
[389] "Pontificia Universidad Javeriana"
[390] "Università degli Studi di Pavia"
[391] "Ajman University"
[392] "Macau University of Science and Technology"
[393] "Sejong University"
[394] "University of California, Riverside"
[395] "University of Turku"
[396] "University of Naples - Federico II"
[397] "National and Kapodistrian University of Athens"
[398] "Ruhr-Universität Bochum"
[399] "University of the Philippines"
[400] "University of Turin"
[401] "INTI International University"
[402] "The Education University of Hong Kong"
[403] "Dublin City University"
[404] "Graz University of Technology"
[405] "University of Florence"
[406] "Oxford Brookes University"
[407] "Singapore Management University"
[408] "University of Saskatchewan"
[409] "University of Southern Queensland"
[410] "University of Kent"
[411] "Aston University"
[412] "Shenzhen University"
[413] "University at Buffalo SUNY"
[414] "IPB University (aka Bogor Agricultural University)"
[415] "Lincoln University"
[416] "Prince Mohammad Bin Fahd university"
[417] "Murdoch University"
[418] "HSE University"
[419] "National Taiwan Normal University (NTNU)"
[420] "Northwestern Polytechnical University"
[421] "Universität Konstanz"
[422] "Universität Mannheim"
[423] "University of Aveiro"
[424] "Tilburg University"
[425] "Julius-Maximilians-Universität Würzburg"
[426] "Auckland University of Technology (AUT)"
[427] "Chung-Ang University (CAU)"
[428] "Czech Technical University in Prague"
[429] "Universitat Politècnica de Catalunya · BarcelonaTech (UPC)"
[430] "Universitat Politecnica de Valencia"
[431] "Central Queensland University (CQUniversity Australia)"
[432] "Tampere University"
[433] "Essex, University of"
[434] "James Cook University"
[435] "National Sun Yat-sen University (NSYSU)"
[436] "Umea University"
[437] "University of Trento"
[438] "Aix-Marseille University"
[439] "Shanghai University"
[440] "University of Science and Technology Beijing"
[441] "IE University"
[442] "University of Dundee"
[443] "University of Granada"
[444] "Jordan University of Science & Technology"
[445] "Pusan National University"
[446] "Universitat de Valencia"
[447] "Central South University"
[448] "Shoolini University of Biotechnology and Management Sciences"
[449] "Bilkent University"
[450] "Masaryk University"
[451] "Université de Strasbourg"
[452] "USI - Università della Svizzera italiana"
[453] "Johannes Kepler University Linz"
[454] "SOAS University of London"
[455] "Tashkent Institute of Irrigation and Agricultural Mechanization Engineers - National Research University (TIIAME-NRU)"
[456] "University of California, Santa Cruz"
[457] "University of Connecticut"
[458] "Dalian University of Technology"
[459] "Universidad de Costa Rica"
[460] "Chongqing University"
[461] "Università Vita-Salute San Raffaele"
[462] "Vilnius University"
[463] "Kazan (Volga region) Federal University"
[464] "Stony Brook University, State University of New York"
[465] "Anna University"
[466] "Leibniz University Hannover"
[467] "University of Bayreuth"
[468] "Université de Montpellier"
[469] "Imam Abdulrahman Bin Faisal University (IAU)"
[470] "Universidad Nacional de La Plata (UNLP)"
[471] "Universitat Ramon Llull"
[472] "China Agricultural University"
[473] "Hunan University"
[474] "Lebanese American University"
[475] "University of Canberra"
[476] "Hiroshima University"
[477] "Kyungpook National University"
[478] "Amirkabir University of Technology"
[479] "Jinan University (China)"
[480] "Royal Holloway, University of London"
[481] "Universidad de Sevilla"
[482] "University of Bordeaux"
[483] "Ewha Womans University"
[484] "Jilin University"
[485] "Novosibirsk State University"
[486] "Prince Sultan University"
[487] "University of Electronic Science and Technology of China"
[488] "National Taipei University of Technology"
[489] "Sogang University"
[490] "Universitas Padjadjaran (UNPAD)"
[491] "Concordia University"
[492] "Institut Teknologi Sepuluh Nopember (ITS Surabaya)"
[493] "University of Bradford"
[494] "Johannes Gutenberg Universität Mainz"
[495] "Universität Potsdam"
[496] "Aristotle University of Thessaloniki"
[497] "University of Genoa"
[498] "Duy Tan University"
[499] "Iran University of Science and Technology"
[500] "Kobe University"
[501] "Ural Federal University - UrFU"
[502] "Warsaw University of Technology"
[503] "Indian Institute of Technology BHU Varanasi (IIT BHU Varanasi)"
[504] "Tomsk State University"
[505] "Washington State University"
[506] "UNESP"
[507] "King Khalid University"
[508] "China Medical University"
[509] "University of Kansas"
[510] "Bond University"
[511] "Universiti Tenaga Nasional (UNITEN)"
[512] "Dongguk University"
[513] "Justus-Liebig-University Giessen"
[514] "Renmin (People's) University of China"
[515] "University of Huddersfield"
[516] "University of Jyväskylä"
[517] "University of Cyprus (UCY)"
[518] "Chandigarh University"
[519] "Université Laval"
[520] "Asia Pacific University of Technology and Innovation (APU) Malaysia"
[521] "Northumbria University at Newcastle"
[522] "Pontificia Universidad Católica Argentina"
[523] "Universidad Austral"
[524] "University of Ljubljana"
[525] "Ben-Gurion University of The Negev"
[526] "University of Utah"
[527] "The University of Georgia"
[528] "Saint Joseph University of Beirut (USJ)"
[529] "University of Iceland"
[530] "University of Windsor"
[531] "Colorado State University"
[532] "Iowa State University"
[533] "Universiti Utara Malaysia (UUM)"
[534] "University of Milano-Bicocca"
[535] "Edith Cowan University"
[536] "Florida State University"
[537] "Indian Institute of Technology Indore"
[538] "University of Guelph"
[539] "Boston College"
[540] "Universiti Teknologi MARA - UiTM"
[541] "Ain Shams University in Cairo (ASU, Cairo)"
[542] "Charles Darwin University"
[543] "Universidad de Santiago de Chile (USACH)"
[544] "University of Houston"
[545] "Chiang Mai University"
[546] "Inha University"
[547] "Jawaharlal Nehru University"
[548] "Thammasat University"
[549] "Al Ain University"

<div class="alert alert-block alert-success">

Vyberte sloupec `Country.Territory` pomocí hranatých závorek tak, aby výsledkem byla stále tabulka.

<details>
<summary></summary>

```r
university_rankings_clean["Country.Territory"]
```

</details>

In [ ]:
university_rankings_clean["Country.Territory"]

    Country.Territory
1   United States of America
2   United Kingdom
3   United States of America
4   United Kingdom
5   United States of America
6   United Kingdom
7   United States of America
8   Switzerland
9   United Kingdom
10  Singapore
11  Hong Kong SAR, China
12  Singapore
13  China (Mainland)
14  China (Mainland)
15  United States of America
16  United States of America
17  United States of America
18  Hong Kong SAR, China
19  Australia
20  United States of America
21  United States of America
22  Switzerland
23  Australia
24  United States of America
25  Germany
26  China (Mainland)
27  United States of America
28  Australia
29  Australia
30  Canada
⋮   ⋮
634 Chile
635 United States of America
636 Taiwan
637 Taiwan
638 Slovakia
639 Indonesia
640 Chile
641 United Kingdom
642 Finland
643 Lebanon
644 China (Mainland)
645 United States of America
646 Switzerland
647 United States of America
648 United States of America
649 Canada
650 Spain
651 Republic of Korea
652 Japan
653 Austria
654 United Kingdom
655 France
656 Iran (Islamic Republic of)
657 United States of America
658 Northern Cyprus
659 Malaysia
660 Germany
661 United Kingdom
662 Austria
663 Germany

<div class="alert alert-block alert-success">

Vyberte sloupec `Country.Territory` pomocí hranatých závorek tak, aby výsledkem byl vektor.

<details>
<summary></summary>

```r
university_rankings_clean[ ,"Country.Territory"]
```

</details>

In [ ]:
university_rankings_clean[, "Country.Territory"]

  [1] "United States of America"   "United Kingdom"
  [3] "United States of America"   "United Kingdom"
  [5] "United States of America"   "United Kingdom"
  [7] "United States of America"   "Switzerland"
  [9] "United Kingdom"             "Singapore"
 [11] "Hong Kong SAR, China"       "Singapore"
 [13] "China (Mainland)"           "China (Mainland)"
 [15] "United States of America"   "United States of America"
 [17] "United States of America"   "Hong Kong SAR, China"
 [19] "Australia"                  "United States of America"
 [21] "United States of America"   "Switzerland"
 [23] "Australia"                  "United States of America"
 [25] "Germany"                    "China (Mainland)"
 [27] "United States of America"   "Australia"
 [29] "Australia"                  "Canada"
 [31] "Australia"                  "Canada"
 [33] "Hong Kong SAR, China"       "France"
 [35] "United Kingdom"             "China (Mainland)"
 [37] "United Kingdom"             "Republic of Korea"
 [39] "Japan"                      "United Kingdom"
 [41] "Australia"                  "Republic of Korea"
 [43] "United States of America"   "France"
 [45] "United States of America"   "Canada"
 [47] "China (Mainland)"           "Netherlands"
 [49] "United States of America"   "Hong Kong SAR, China"
 [51] "United States of America"   "Hong Kong SAR, China"
 [53] "Republic of Korea"          "Taiwan"
 [55] "United States of America"   "Malaysia"
 [57] "United Kingdom"             "United States of America"
 [59] "Belgium"                    "Netherlands"
 [61] "Germany"                    "United Kingdom"
 [63] "Saudi Arabia"               "Japan"
 [65] "United States of America"   "New Zealand"
 [67] "United Kingdom"             "United Kingdom"
 [69] "United States of America"   "Sweden"
 [71] "United States of America"   "France"
 [73] "United States of America"   "Ireland"
 [75] "France"                     "Australia"
 [77] "United Kingdom"             "United Kingdom"
 [79] "United States of America"   "Sweden"
 [81] "United Kingdom"             "Argentina"
 [83] "United Kingdom"             "Germany"
 [85] "Italy"                      "Australia"
 [87] "Sweden"                     "China (Mainland)"
 [89] "Denmark"                    "United States of America"
 [91] "United States of America"   "United States of America"
 [93] "Japan"                      "Canada"
 [95] "United Kingdom"             "Germany"
 [97] "Switzerland"                "United States of America"
 [99] "Ireland"                    "Japan"
[101] "United Kingdom"             "Germany"
[103] "Denmark"                    "Republic of Korea"
[105] "Saudi Arabia"               "Republic of Korea"
[107] "Qatar"                      "Germany"
[109] "Italy"                      "United Kingdom"
[111] "Canada"                     "Netherlands"
[113] "Russian Federation"         "United Kingdom"
[115] "India"                      "Netherlands"
[117] "Chile"                      "Australia"
[119] "United States of America"   "Italy"
[121] "Finland"                    "United Kingdom"
[123] "Finland"                    "Australia"
[125] "Denmark"                    "Malaysia"
[127] "Malaysia"                   "Norway"
[129] "United States of America"   "Brazil"
[131] "India"                      "China (Mainland)"
[133] "United Kingdom"             "United States of America"
[135] "Malaysia"                   "United Kingdom"
[137] "Germany"                    "Austria"
[139] "United States of America"   "Taiwan"
[141] "Canada"                     "Mexico"
[143] "China (Mainland)"           "United Arab Emirates"
[145] "Netherlands"                "United Kingdom"
[147] "Belgium"                    "Switzerland"
[149] "Netherlands"                "United States of America"
[151] "Netherlands"                "Republic of Korea"
[153] "Japan"                      "Netherlands"
[155] "Germany"                    "Malaysia"
[157] "United States of America"   "United Kingdom"
[159] "Canada"                     "United States of America"
[161] "United Kingdom"             "Spain"
[163] "China (Mainland)"           "Sweden"
[165] "Switzerland"                "United States of America"
[167] "India"                      "Japan"
[169] "United States of America"   "United States of America"
[171] "Sweden"                     "Canada"
[173] "United Kingdom"             "Kazakhstan"
[175] "Taiwan"                     "United Kingdom"
[177] "Japan"                      "Canada"
[179] "United States of America"   "United States of America"
[181] "South Africa"               "Germany"
[183] "Chile"                      "Netherlands"
[185] "Mexico"                     "Australia"
[187] "China (Mainland)"           "Taiwan"
[189] "Austria"                    "Indonesia"
[191] "Switzerland"                "Australia"
[193] "Belgium"                    "United Kingdom"
[195] "New Zealand"                "Spain"
[197] "Saudi Arabia"               "United States of America"
[199] "Japan"                      "United Kingdom"
[201] "Italy"                      "India"
[203] "Indonesia"                  "Italy"
[205] "Israel"                     "Germany"
[207] "Germany"                    "Spain"
[209] "Thailand"                   "Qatar"
[211] "Japan"                      "New Zealand"
[213] "Hong Kong SAR, China"       "United Arab Emirates"
[215] "Germany"                    "Israel"
[217] "Ireland"                    "India"
[219] "India"                      "Lebanon"
[221] "Netherlands"                "Sweden"
[223] "Spain"                      "Australia"
[225] "United States of America"   "Canada"
[227] "Germany"                    "Australia"
[229] "United Kingdom"             "Colombia"
[231] "Switzerland"                "France"
[233] "China (Mainland)"           "China (Mainland)"
[235] "Portugal"                   "Australia"
[237] "Australia"                  "New Zealand"
[239] "China (Mainland)"           "Australia"
[241] "Germany"                    "France"
[243] "United Kingdom"             "Belgium"
[245] "Canada"                     "Germany"
[247] "United States of America"   "United States of America"
[249] "United States of America"   "Netherlands"
[251] "United States of America"   "Portugal"
[253] "New Zealand"                "United Arab Emirates"
[255] "China (Mainland)"           "United States of America"
[257] "Malaysia"                   "Germany"
[259] "Spain"                      "Norway"
[261] "United States of America"   "Singapore"
[263] "Macao SAR, China"           "United States of America"
[265] "Germany"                    "United States of America"
[267] "Italy"                      "Malaysia"
[269] "Czechia"                    "United Kingdom"
[271] "Ireland"                    "Indonesia"
[273] "Brazil"                     "Belgium"
[275] "Türkiye"                    "Spain"
[277] "United States of America"   "Malaysia"
[279] "Netherlands"                "Norway"
[281] "United Arab Emirates"       "Denmark"
[283] "Indonesia"                  "United Kingdom"
[285] "United States of America"   "Poland"
[287] "Australia"                  "South Africa"
[289] "Colombia"                   "New Zealand"
[291] "Belgium"                    "South Africa"
[293] "China (Mainland)"           "Canada"
[295] "Republic of Korea"          "China (Mainland)"
[297] "United States of America"   "South Africa"
[299] "France"                     "China (Mainland)"
[301] "Türkiye"                    "Oman"
[303] "China (Mainland)"           "Sweden"
[305] "Republic of Korea"          "China (Mainland)"
[307] "Australia"                  "Canada"
[309] "United States of America"   "United States of America"
[311] "Spain"                      "United Kingdom"
[313] "China (Mainland)"           "Russian Federation"
[315] "Germany"                    "United States of America"
[317] "United States of America"   "United Kingdom"
[319] "India"                      "Canada"
[321] "United Kingdom"             "United States of America"
[323] "Jordan"                     "South Africa"
[325] "Denmark"                    "Poland"
[327] "Türkiye"                    "China (Mainland)"
[329] "Austria"                    "Israel"
[331] "India"                      "China (Mainland)"
[333] "Portugal"                   "Kazakhstan"
[335] "United States of America"   "United States of America"
[337] "Italy"                      "China (Mainland)"
[339] "Portugal"                   "Italy"
[341] "Türkiye"                    "Thailand"
[343] "Brunei Darussalam"          "United Arab Emirates"
[345] "China (Mainland)"           "India"
[347] "Kazakhstan"                 "Japan"
[349] "United Kingdom"             "United Kingdom"
[351] "France"                     "Malaysia"
[353] "Peru"                       "Türkiye"
[355] "Russian Federation"         "United States of America"
[357] "Finland"                    "Egypt"
[359] "Spain"                      "Belgium"
[361] "United States of America"   "Brazil"
[363] "Estonia"                    "Iran (Islamic Republic of)"
[365] "United States of America"   "Germany"
[367] "Canada"                     "Australia"
[369] "Australia"                  "Germany"
[371] "Luxembourg"                 "Greece"
[373] "Republic of Korea"          "Taiwan"
[375] "United States of America"   "Pakistan"
[377] "United Kingdom"             "Pakistan"
[379] "Republic of Korea"          "United States of America"
[381] "France"                     "Italy"
[383] "Ireland"                    "Finland"
[385] "Russian Federation"         "Iran (Islamic Republic of)"
[387] "Egypt"                      "China (Mainland)"
[389] "Colombia"                   "Italy"
[391] "United Arab Emirates"       "Macao SAR, China"
[393] "Republic of Korea"          "United States of America"
[395] "Finland"                    "Italy"
[397] "Greece"                     "Germany"
[399] "Philippines"                "Italy"
[401] "Malaysia"                   "Hong Kong SAR, China"
[403] "Ireland"                    "Austria"
[405] "Italy"                      "United Kingdom"
[407] "Singapore"                  "Canada"
[409] "Australia"                  "United Kingdom"
[411] "United Kingdom"             "China (Mainland)"
[413] "United States of America"   "Indonesia"
[415] "New Zealand"                "Saudi Arabia"
[417] "Australia"                  "Russian Federation"
[419] "Taiwan"                     "China (Mainland)"
[421] "Germany"                    "Germany"
[423] "Portugal"                   "Netherlands"
[425] "Germany"                    "New Zealand"
[427] "Republic of Korea"          "Czechia"
[429] "Spain"                      "Spain"
[431] "Australia"                  "Finland"
[433] "United Kingdom"             "Australia"
[435] "Taiwan"                     "Sweden"
[437] "Italy"                      "France"
[439] "China (Mainland)"           "China (Mainland)"
[441] "Spain"                      "United Kingdom"
[443] "Spain"                      "Jordan"
[445] "Republic of Korea"          "Spain"
[447] "China (Mainland)"           "India"
[449] "Türkiye"                    "Czechia"
[451] "France"                     "Switzerland"
[453] "Austria"                    "United Kingdom"
[455] "Uzbekistan"                 "United States of America"
[457] "United States of America"   "China (Mainland)"
[459] "Costa Rica"                 "China (Mainland)"
[461] "Italy"                      "Lithuania"
[463] "Russian Federation"         "United States of America"
[465] "India"                      "Germany"
[467] "Germany"                    "France"
[469] "Saudi Arabia"               "Argentina"
[471] "Spain"                      "China (Mainland)"
[473] "China (Mainland)"           "Lebanon"
[475] "Australia"                  "Japan"
[477] "Republic of Korea"          "Iran (Islamic Republic of)"
[479] "China (Mainland)"           "United Kingdom"
[481] "Spain"                      "France"
[483] "Republic of Korea"          "China (Mainland)"
[485] "Russian Federation"         "Saudi Arabia"
[487] "China (Mainland)"           "Taiwan"
[489] "Republic of Korea"          "Indonesia"
[491] "Canada"                     "Indonesia"
[493] "United Kingdom"             "Germany"
[495] "Germany"                    "Greece"
[497] "Italy"                      "Viet Nam"
[499] "Iran (Islamic Republic of)" "Japan"
[501] "Russian Federation"         "Poland"
[503] "India"                      "Russian Federation"
[505] "United States of America"   "Brazil"
[507] "Saudi Arabia"               "Taiwan"
[509] "United States of America"   "Australia"
[511] "Malaysia"                   "Republic of Korea"
[513] "Germany"                    "China (Mainland)"
[515] "United Kingdom"             "Finland"
[517] "Cyprus"                     "India"
[519] "Canada"                     "Malaysia"
[521] "United Kingdom"             "Argentina"
[523] "Argentina"                  "Slovenia"
[525] "Israel"                     "United States of America"
[527] "United States of America"   "Lebanon"
[529] "Iceland"                    "Canada"
[531] "United States of America"   "United States of America"
[533] "Malaysia"                   "Italy"
[535] "Australia"                  "United States of America"
[537] "India"                      "Canada"
[539] "United States of America"   "Malaysia"
[541] "Egypt"                      "Australia"
[543] "Chile"                      "United States of America"
[545] "Thailand"                   "Republic of Korea"
[547] "India"                      "Thailand"
[549] "United Arab Emirates"       "Canada"
[551] "Spain"                      "United Kingdom"
[553] "Azerbaijan"                 "France"
[555] "United Kingdom"             "Saudi Arabia"
[557] "Republic of Korea"          "Türkiye"
[559] "Austria"                    "Portugal"
[561] "Italy"                      "India"
[563] "United States of America"   "Japan"
[565] "Germany"                    "United States of America"
[567] "United Kingdom"             "Philippines"
[569] "United Kingdom"             "United States of America"
[571] "Germany"                    "Italy"
[573] "China (Mainland)"           "Czechia"
[575] "India"                      "Germany"
[577] "Malaysia"                   "Pakistan"
[579] "United Arab Emirates"       "Germany"
[581] "Hungary"                    "United Kingdom"
[583] "United States of America"   "United States of America"
[585] "India"                      "Italy"
[587] "China (Mainland)"           "Brazil"
[589] "United Kingdom"             "Estonia"
[591] "Hungary"                    "Bangladesh"
[593] "South Africa"               "United Arab Emirates"
[595] "Italy"                      "Pakistan"
[597] "Malaysia"                   "Taiwan"
[599] "Taiwan"                     "France"
[601] "Brunei Darussalam"          "Kuwait"
[603] "United Arab Emirates"       "Indonesia"
[605] "Russian Federation"         "United Arab Emirates"
[607] "Germany"                    "Republic of Korea"
[609] "United States of America"   "Iran (Islamic Republic of)"
[611] "Brazil"                     "Lebanon"
[613] "Finland"                    "Türkiye"
[615] "Spain"                      "Pakistan"
[617] "Norway"                     "Hungary"
[619] "Kazakhstan"                 "Taiwan"
[621] "Australia"                  "Pakistan"
[623] "Belgium"                    "United Kingdom"
[625] "Spain"                      "United States of America"
[627] "United States of America"   "China (Mainland)"
[629] "Greece"                     "Uruguay"
[631] "Czechia"                    "Bahrain"
[633] "India"                      "Chile"
[635] "United States of America"   "Taiwan"
[637] "Taiwan"                     "Slovakia"
[639] "Indonesia"                  "Chile"
[641] "United Kingdom"             "Finland"
[643] "Lebanon"                    "China (Mainland)"
[645] "United States of America"   "Switzerland"
[647] "United States of America"   "United States of America"
[649] "Canada"                     "Spain"
[651] "Republic of Korea"          "Japan"
[653] "Austria"                    "United Kingdom"
[655] "France"                     "Iran (Islamic Republic of)"
[657] "United States of America"   "Northern Cyprus"
[659] "Malaysia"                   "Germany"
[661] "United Kingdom"             "Austria"
[663] "Germany"

<div class="alert alert-block alert-success">

Vyberte sloupec `Country.Territory` pomocí dvojitých hranatých závorek. Jak se výsledek liší od předchozích?

<details>
<summary></summary>

```r
university_rankings_clean[["Country.Territory"]]
```

</details>

In [ ]:
university_rankings_clean[["Country.Territory"]]

  [1] "United States of America"   "United Kingdom"
  [3] "United States of America"   "United Kingdom"
  [5] "United States of America"   "United Kingdom"
  [7] "United States of America"   "Switzerland"
  [9] "United Kingdom"             "Singapore"
 [11] "Hong Kong SAR, China"       "Singapore"
 [13] "China (Mainland)"           "China (Mainland)"
 [15] "United States of America"   "United States of America"
 [17] "United States of America"   "Hong Kong SAR, China"
 [19] "Australia"                  "United States of America"
 [21] "United States of America"   "Switzerland"
 [23] "Australia"                  "United States of America"
 [25] "Germany"                    "China (Mainland)"
 [27] "United States of America"   "Australia"
 [29] "Australia"                  "Canada"
 [31] "Australia"                  "Canada"
 [33] "Hong Kong SAR, China"       "France"
 [35] "United Kingdom"             "China (Mainland)"
 [37] "United Kingdom"             "Republic of Korea"
 [39] "Japan"                      "United Kingdom"
 [41] "Australia"                  "Republic of Korea"
 [43] "United States of America"   "France"
 [45] "United States of America"   "Canada"
 [47] "China (Mainland)"           "Netherlands"
 [49] "United States of America"   "Hong Kong SAR, China"
 [51] "United States of America"   "Hong Kong SAR, China"
 [53] "Republic of Korea"          "Taiwan"
 [55] "United States of America"   "Malaysia"
 [57] "United Kingdom"             "United States of America"
 [59] "Belgium"                    "Netherlands"
 [61] "Germany"                    "United Kingdom"
 [63] "Saudi Arabia"               "Japan"
 [65] "United States of America"   "New Zealand"
 [67] "United Kingdom"             "United Kingdom"
 [69] "United States of America"   "Sweden"
 [71] "United States of America"   "France"
 [73] "United States of America"   "Ireland"
 [75] "France"                     "Australia"
 [77] "United Kingdom"             "United Kingdom"
 [79] "United States of America"   "Sweden"
 [81] "United Kingdom"             "Argentina"
 [83] "United Kingdom"             "Germany"
 [85] "Italy"                      "Australia"
 [87] "Sweden"                     "China (Mainland)"
 [89] "Denmark"                    "United States of America"
 [91] "United States of America"   "United States of America"
 [93] "Japan"                      "Canada"
 [95] "United Kingdom"             "Germany"
 [97] "Switzerland"                "United States of America"
 [99] "Ireland"                    "Japan"
[101] "United Kingdom"             "Germany"
[103] "Denmark"                    "Republic of Korea"
[105] "Saudi Arabia"               "Republic of Korea"
[107] "Qatar"                      "Germany"
[109] "Italy"                      "United Kingdom"
[111] "Canada"                     "Netherlands"
[113] "Russian Federation"         "United Kingdom"
[115] "India"                      "Netherlands"
[117] "Chile"                      "Australia"
[119] "United States of America"   "Italy"
[121] "Finland"                    "United Kingdom"
[123] "Finland"                    "Australia"
[125] "Denmark"                    "Malaysia"
[127] "Malaysia"                   "Norway"
[129] "United States of America"   "Brazil"
[131] "India"                      "China (Mainland)"
[133] "United Kingdom"             "United States of America"
[135] "Malaysia"                   "United Kingdom"
[137] "Germany"                    "Austria"
[139] "United States of America"   "Taiwan"
[141] "Canada"                     "Mexico"
[143] "China (Mainland)"           "United Arab Emirates"
[145] "Netherlands"                "United Kingdom"
[147] "Belgium"                    "Switzerland"
[149] "Netherlands"                "United States of America"
[151] "Netherlands"                "Republic of Korea"
[153] "Japan"                      "Netherlands"
[155] "Germany"                    "Malaysia"
[157] "United States of America"   "United Kingdom"
[159] "Canada"                     "United States of America"
[161] "United Kingdom"             "Spain"
[163] "China (Mainland)"           "Sweden"
[165] "Switzerland"                "United States of America"
[167] "India"                      "Japan"
[169] "United States of America"   "United States of America"
[171] "Sweden"                     "Canada"
[173] "United Kingdom"             "Kazakhstan"
[175] "Taiwan"                     "United Kingdom"
[177] "Japan"                      "Canada"
[179] "United States of America"   "United States of America"
[181] "South Africa"               "Germany"
[183] "Chile"                      "Netherlands"
[185] "Mexico"                     "Australia"
[187] "China (Mainland)"           "Taiwan"
[189] "Austria"                    "Indonesia"
[191] "Switzerland"                "Australia"
[193] "Belgium"                    "United Kingdom"
[195] "New Zealand"                "Spain"
[197] "Saudi Arabia"               "United States of America"
[199] "Japan"                      "United Kingdom"
[201] "Italy"                      "India"
[203] "Indonesia"                  "Italy"
[205] "Israel"                     "Germany"
[207] "Germany"                    "Spain"
[209] "Thailand"                   "Qatar"
[211] "Japan"                      "New Zealand"
[213] "Hong Kong SAR, China"       "United Arab Emirates"
[215] "Germany"                    "Israel"
[217] "Ireland"                    "India"
[219] "India"                      "Lebanon"
[221] "Netherlands"                "Sweden"
[223] "Spain"                      "Australia"
[225] "United States of America"   "Canada"
[227] "Germany"                    "Australia"
[229] "United Kingdom"             "Colombia"
[231] "Switzerland"                "France"
[233] "China (Mainland)"           "China (Mainland)"
[235] "Portugal"                   "Australia"
[237] "Australia"                  "New Zealand"
[239] "China (Mainland)"           "Australia"
[241] "Germany"                    "France"
[243] "United Kingdom"             "Belgium"
[245] "Canada"                     "Germany"
[247] "United States of America"   "United States of America"
[249] "United States of America"   "Netherlands"
[251] "United States of America"   "Portugal"
[253] "New Zealand"                "United Arab Emirates"
[255] "China (Mainland)"           "United States of America"
[257] "Malaysia"                   "Germany"
[259] "Spain"                      "Norway"
[261] "United States of America"   "Singapore"
[263] "Macao SAR, China"           "United States of America"
[265] "Germany"                    "United States of America"
[267] "Italy"                      "Malaysia"
[269] "Czechia"                    "United Kingdom"
[271] "Ireland"                    "Indonesia"
[273] "Brazil"                     "Belgium"
[275] "Türkiye"                    "Spain"
[277] "United States of America"   "Malaysia"
[279] "Netherlands"                "Norway"
[281] "United Arab Emirates"       "Denmark"
[283] "Indonesia"                  "United Kingdom"
[285] "United States of America"   "Poland"
[287] "Australia"                  "South Africa"
[289] "Colombia"                   "New Zealand"
[291] "Belgium"                    "South Africa"
[293] "China (Mainland)"           "Canada"
[295] "Republic of Korea"          "China (Mainland)"
[297] "United States of America"   "South Africa"
[299] "France"                     "China (Mainland)"
[301] "Türkiye"                    "Oman"
[303] "China (Mainland)"           "Sweden"
[305] "Republic of Korea"          "China (Mainland)"
[307] "Australia"                  "Canada"
[309] "United States of America"   "United States of America"
[311] "Spain"                      "United Kingdom"
[313] "China (Mainland)"           "Russian Federation"
[315] "Germany"                    "United States of America"
[317] "United States of America"   "United Kingdom"
[319] "India"                      "Canada"
[321] "United Kingdom"             "United States of America"
[323] "Jordan"                     "South Africa"
[325] "Denmark"                    "Poland"
[327] "Türkiye"                    "China (Mainland)"
[329] "Austria"                    "Israel"
[331] "India"                      "China (Mainland)"
[333] "Portugal"                   "Kazakhstan"
[335] "United States of America"   "United States of America"
[337] "Italy"                      "China (Mainland)"
[339] "Portugal"                   "Italy"
[341] "Türkiye"                    "Thailand"
[343] "Brunei Darussalam"          "United Arab Emirates"
[345] "China (Mainland)"           "India"
[347] "Kazakhstan"                 "Japan"
[349] "United Kingdom"             "United Kingdom"
[351] "France"                     "Malaysia"
[353] "Peru"                       "Türkiye"
[355] "Russian Federation"         "United States of America"
[357] "Finland"                    "Egypt"
[359] "Spain"                      "Belgium"
[361] "United States of America"   "Brazil"
[363] "Estonia"                    "Iran (Islamic Republic of)"
[365] "United States of America"   "Germany"
[367] "Canada"                     "Australia"
[369] "Australia"                  "Germany"
[371] "Luxembourg"                 "Greece"
[373] "Republic of Korea"          "Taiwan"
[375] "United States of America"   "Pakistan"
[377] "United Kingdom"             "Pakistan"
[379] "Republic of Korea"          "United States of America"
[381] "France"                     "Italy"
[383] "Ireland"                    "Finland"
[385] "Russian Federation"         "Iran (Islamic Republic of)"
[387] "Egypt"                      "China (Mainland)"
[389] "Colombia"                   "Italy"
[391] "United Arab Emirates"       "Macao SAR, China"
[393] "Republic of Korea"          "United States of America"
[395] "Finland"                    "Italy"
[397] "Greece"                     "Germany"
[399] "Philippines"                "Italy"
[401] "Malaysia"                   "Hong Kong SAR, China"
[403] "Ireland"                    "Austria"
[405] "Italy"                      "United Kingdom"
[407] "Singapore"                  "Canada"
[409] "Australia"                  "United Kingdom"
[411] "United Kingdom"             "China (Mainland)"
[413] "United States of America"   "Indonesia"
[415] "New Zealand"                "Saudi Arabia"
[417] "Australia"                  "Russian Federation"
[419] "Taiwan"                     "China (Mainland)"
[421] "Germany"                    "Germany"
[423] "Portugal"                   "Netherlands"
[425] "Germany"                    "New Zealand"
[427] "Republic of Korea"          "Czechia"
[429] "Spain"                      "Spain"
[431] "Australia"                  "Finland"
[433] "United Kingdom"             "Australia"
[435] "Taiwan"                     "Sweden"
[437] "Italy"                      "France"
[439] "China (Mainland)"           "China (Mainland)"
[441] "Spain"                      "United Kingdom"
[443] "Spain"                      "Jordan"
[445] "Republic of Korea"          "Spain"
[447] "China (Mainland)"           "India"
[449] "Türkiye"                    "Czechia"
[451] "France"                     "Switzerland"
[453] "Austria"                    "United Kingdom"
[455] "Uzbekistan"                 "United States of America"
[457] "United States of America"   "China (Mainland)"
[459] "Costa Rica"                 "China (Mainland)"
[461] "Italy"                      "Lithuania"
[463] "Russian Federation"         "United States of America"
[465] "India"                      "Germany"
[467] "Germany"                    "France"
[469] "Saudi Arabia"               "Argentina"
[471] "Spain"                      "China (Mainland)"
[473] "China (Mainland)"           "Lebanon"
[475] "Australia"                  "Japan"
[477] "Republic of Korea"          "Iran (Islamic Republic of)"
[479] "China (Mainland)"           "United Kingdom"
[481] "Spain"                      "France"
[483] "Republic of Korea"          "China (Mainland)"
[485] "Russian Federation"         "Saudi Arabia"
[487] "China (Mainland)"           "Taiwan"
[489] "Republic of Korea"          "Indonesia"
[491] "Canada"                     "Indonesia"
[493] "United Kingdom"             "Germany"
[495] "Germany"                    "Greece"
[497] "Italy"                      "Viet Nam"
[499] "Iran (Islamic Republic of)" "Japan"
[501] "Russian Federation"         "Poland"
[503] "India"                      "Russian Federation"
[505] "United States of America"   "Brazil"
[507] "Saudi Arabia"               "Taiwan"
[509] "United States of America"   "Australia"
[511] "Malaysia"                   "Republic of Korea"
[513] "Germany"                    "China (Mainland)"
[515] "United Kingdom"             "Finland"
[517] "Cyprus"                     "India"
[519] "Canada"                     "Malaysia"
[521] "United Kingdom"             "Argentina"
[523] "Argentina"                  "Slovenia"
[525] "Israel"                     "United States of America"
[527] "United States of America"   "Lebanon"
[529] "Iceland"                    "Canada"
[531] "United States of America"   "United States of America"
[533] "Malaysia"                   "Italy"
[535] "Australia"                  "United States of America"
[537] "India"                      "Canada"
[539] "United States of America"   "Malaysia"
[541] "Egypt"                      "Australia"
[543] "Chile"                      "United States of America"
[545] "Thailand"                   "Republic of Korea"
[547] "India"                      "Thailand"
[549] "United Arab Emirates"       "Canada"
[551] "Spain"                      "United Kingdom"
[553] "Azerbaijan"                 "France"
[555] "United Kingdom"             "Saudi Arabia"
[557] "Republic of Korea"          "Türkiye"
[559] "Austria"                    "Portugal"
[561] "Italy"                      "India"
[563] "United States of America"   "Japan"
[565] "Germany"                    "United States of America"
[567] "United Kingdom"             "Philippines"
[569] "United Kingdom"             "United States of America"
[571] "Germany"                    "Italy"
[573] "China (Mainland)"           "Czechia"
[575] "India"                      "Germany"
[577] "Malaysia"                   "Pakistan"
[579] "United Arab Emirates"       "Germany"
[581] "Hungary"                    "United Kingdom"
[583] "United States of America"   "United States of America"
[585] "India"                      "Italy"
[587] "China (Mainland)"           "Brazil"
[589] "United Kingdom"             "Estonia"
[591] "Hungary"                    "Bangladesh"
[593] "South Africa"               "United Arab Emirates"
[595] "Italy"                      "Pakistan"
[597] "Malaysia"                   "Taiwan"
[599] "Taiwan"                     "France"
[601] "Brunei Darussalam"          "Kuwait"
[603] "United Arab Emirates"       "Indonesia"
[605] "Russian Federation"         "United Arab Emirates"
[607] "Germany"                    "Republic of Korea"
[609] "United States of America"   "Iran (Islamic Republic of)"
[611] "Brazil"                     "Lebanon"
[613] "Finland"                    "Türkiye"
[615] "Spain"                      "Pakistan"
[617] "Norway"                     "Hungary"
[619] "Kazakhstan"                 "Taiwan"
[621] "Australia"                  "Pakistan"
[623] "Belgium"                    "United Kingdom"
[625] "Spain"                      "United States of America"
[627] "United States of America"   "China (Mainland)"
[629] "Greece"                     "Uruguay"
[631] "Czechia"                    "Bahrain"
[633] "India"                      "Chile"
[635] "United States of America"   "Taiwan"
[637] "Taiwan"                     "Slovakia"
[639] "Indonesia"                  "Chile"
[641] "United Kingdom"             "Finland"
[643] "Lebanon"                    "China (Mainland)"
[645] "United States of America"   "Switzerland"
[647] "United States of America"   "United States of America"
[649] "Canada"                     "Spain"
[651] "Republic of Korea"          "Japan"
[653] "Austria"                    "United Kingdom"
[655] "France"                     "Iran (Islamic Republic of)"
[657] "United States of America"   "Northern Cyprus"
[659] "Malaysia"                   "Germany"
[661] "United Kingdom"             "Austria"
[663] "Germany"

<div class="alert alert-block alert-success">

Vypište prvních 10 univerzit, ale pouze jejich název, zemi a město.

<details>
<summary></summary>

```r
university_rankings_clean[1:10, c("Name", "Country.Territory", "City")]
```

*Alternativa:*

```r
head(university_rankings_clean[, c("Name", "Country.Territory", "City")], 10)
```

</details>

In [ ]:
head(university_rankings_clean[, c("Name", "Country.Territory", "City")], 10)

   Name                                         Country.Territory
1  Massachusetts Institute of Technology (MIT)  United States of America
2  Imperial College London                      United Kingdom
3  Stanford University                          United States of America
4  University of Oxford                         United Kingdom
5  Harvard University                           United States of America
6  University of Cambridge                      United Kingdom
7  California Institute of Technology (Caltech) United States of America
8  ETH Zurich                                   Switzerland
9  UCL                                          United Kingdom
10 National University of Singapore (NUS)       Singapore
   City
1  Cambridge
2  London
3  Stanford
4  Oxford
5  Cambridge
6  Cambridge
7  Pasadena
8  Zurich
9  London
10 Singapore

<div class="alert alert-block alert-success">

Vypište 20. až 30. univerzitu v pořadí. Zobrazte pouze pořadí a název univerzity.

<details>
<summary></summary>

```r
university_rankings_clean[20:30, c("Rank", "Name")]
```

</details>

In [ ]:
university_rankings_clean[20:30, c("Rank", "Name")]

   Rank Name
20 20   Johns Hopkins University
21 20   University of California, Berkeley (UCB)
22 22   EPFL – École polytechnique fédérale de Lausanne
23 22   The University of Melbourne
24 24   University of Chicago
25 25   Technical University of Munich
26 26   Fudan University
27 27   Princeton University
28 28   The University of Sydney
29 29   Australian National University (ANU)
30 30   McGill University

<div class="alert alert-block alert-success">

Vypište všechny informace o univerzitě na 100. řádku.

<details>
<summary></summary>

103	103	102	109	Tohoku University    Japan		Asia	....

<details>
<summary></summary>

```r
university_rankings_clean[100, ]
```

</details>
</details>

In [ ]:
university_rankings_clean[100, ]

    X   Index Rank Previous.Rank Name              Country.Territory Region
100 103 103   102  109           Tohoku University Japan             Asia
    Size Focus Research ⋯ FSR.SCORE CPF.SCORE IFR.SCORE IFR.RANK ISR.SCORE
100 L    FC    VH       ⋯ 96.2      38.4      26.1      649      18.4
    IRN.SCORE EO.SCORE SUS.SCORE Overall.SCORE City
100 73.9      36       86.8      68.4          Sendai City

<div class="alert alert-block alert-success">

Zjistěte, kolik univerzit z jednotlivých zemí se nachází v datasetu.

<details>
<summary></summary>

Argentina: 4

Australia: 30

...

Uzbekistan: 1

Viet Nam: 1

<details>
<summary></summary>

```r
table(university_rankings_clean$Country.Territory)
```

</details>

In [ ]:
table(university_rankings_clean$Country.Territory)

                 Argentina                  Australia
                         4                         30
                   Austria                 Azerbaijan
                         8                          1
                   Bahrain                 Bangladesh
                         1                          1
                   Belgium                     Brazil
                         8                          6
         Brunei Darussalam                     Canada
                         2                         22
                  Colombia                 Costa Rica
                         3                          1
                    Cyprus                    Czechia
                         1                          5
                   Denmark                      Egypt
                         5                          3
                   Estonia                    Finland
                         2                          9
                    France                    Germany
                        16                         36
                    Greece       Hong Kong SAR, China
                         4                          7
                   Hungary                      Chile
                         3                          5
          China (Mainland)                    Iceland
                        42                          1
                     India                  Indonesia
                        19                          9
Iran (Islamic Republic of)                    Ireland
                         6                          6
                    Israel                      Italy
                         4                         21
                     Japan                     Jordan
                        14                          2
                Kazakhstan                     Kuwait
                         4                          1
                   Lebanon                  Lithuania
                         5                          1
                Luxembourg           Macao SAR, China
                         1                          2
                  Malaysia                     Mexico
                        17                          2
               Netherlands                New Zealand
                        13                          8
           Northern Cyprus                     Norway
                         1                          4
                      Oman                   Pakistan
                         1                          6
                      Peru                Philippines
                         1                          2
                    Poland                   Portugal
                         3                          6
                     Qatar          Republic of Korea
                         2                         21
        Russian Federation               Saudi Arabia
                        10                          8
                 Singapore                   Slovakia
                         4                          1
                  Slovenia               South Africa
                         1                          6
                     Spain                     Sweden
                        19                          8
               Switzerland                     Taiwan
                         9                         14
                  Thailand                    Türkiye
                         4                          8
      United Arab Emirates             United Kingdom
                        11                         59
  United States of America                    Uruguay
                        90                          1
                Uzbekistan                   Viet Nam
                         1                          1

<div class="alert alert-block alert-success">

Kolik univerzit pochází z České republiky?

<details>
<summary></summary>

16

<details>
<summary></summary>

```r
sum(university_rankings$Country.Territory == "Czechia")
```

*Alternativa:*

```r
table(university_rankings$Country.Territory)["Czechia"]
```

</details>
</details>

In [ ]:
sum(university_rankings_clean$Country.Territory == "Czechia")

[1] 5

<div class="alert alert-block alert-success">

Ze které země pochází nejvíce univerzit v datasetu?

<details>
<summary></summary>

United States of America

<details>
<summary></summary>

```r
university_countries_counts = table(university_rankings_clean$Country.Territory)
names(university_countries_counts)[which.max(university_countries_counts)]
```

*Alternativa:*

```r
sort(table(university_rankings_clean$Country.Territory), decreasing = TRUE)[1]
```

*Alternativa:*

```r
rev(sort(table(university_rankings_clean$Country.Territory)))[1]
```

*Alternativa:*

```r
university_rankings_clean$Country.Territory |> table() |> sort() |> rev() |> head(1) |> names()
```

*Alternativa:*

```r
university_rankings_clean$Country.Territory |> table() |> sort(decreasing = TRUE) |> head(1) |> names()
```

</details>
</details>

In [ ]:
sort(table(university_rankings_clean$Country.Territory), decreasing = TRUE)[1]

United States of America
                      90

<div class="alert alert-block alert-success">

Kolik je v datasetu regionů?

<details>
<summary></summary>

5

<details>
<summary></summary>

```r
length(unique(university_rankings_clean$Region))
```

*Alternativa:*

```r
length(table(university_rankings_clean$Region))
```

</details>
</details>

In [ ]:
length(unique(university_rankings_clean$Region))

[1] 5

<div class="alert alert-block alert-success">

Která velikost univerzity (sloupec **Size**) je nejčastější a která nejméně častá?

<details>
<summary></summary>

Nejméně častá: S (40)

Nejvíce častá: L (292)

<details>
<summary></summary>

```r
sort(table(university_rankings_clean$Size))
```

</details>
</details>

In [ ]:
sort(table(university_rankings_clean$Size), decreasing = TRUE)[1]
sort(table(university_rankings_clean$Size), decreasing = TRUE)[4]

  L
291

 S
40

## Filtrování a indexování

<div class="alert alert-block alert-success">

Vyberte všechny univerzity z České republiky.

<details>
<summary></summary>

Charles University; Czech Technical University in Prague; Masaryk University; Brno University of Technology; University of Chemistry and Technology, Prague

<details>
<summary></summary>

```r
university_rankings_clean[
    university_rankings_clean$Country.Territory == "Czechia",
    "Name"
]
```

</details>
</details>

In [ ]:
university_rankings_clean[university_rankings_clean$Country.Territory == "Czechia", "Name"]

[1] "Charles University"
[2] "Czech Technical University in Prague"
[3] "Masaryk University"
[4] "Brno University of Technology"
[5] "University of Chemistry and Technology, Prague"

<div class="alert alert-block alert-success">

Vyberte všechny univerzity z České republiky nebo Slovenska.

<details>
<summary></summary>

Charles University; Czech Technical University in Prague; Masaryk University; Brno University of Technology; University of Chemistry and Technology, Prague; Comenius University Bratislava

<details>
<summary></summary>

```r
university_rankings_clean[
    university_rankings_clean$Country.Territory %in% c("Czechia", "Slovakia"),
    "Name"
]
```

</details>
</details>

In [ ]:
university_rankings_clean[university_rankings_clean$Country.Territory %in% c("Czechia", "Slovakia"), "Name"]

[1] "Charles University"
[2] "Czech Technical University in Prague"
[3] "Masaryk University"
[4] "Brno University of Technology"
[5] "University of Chemistry and Technology, Prague"
[6] "Comenius University Bratislava"

<div class="alert alert-block alert-success">

Vyberte všechny evropské univerzity, které jsou veřejné. Kolik jich je?

<details>
<summary></summary>

251

<details>
<summary></summary>

```r
university_rankings_clean[
    university_rankings_clean$Region == "Europe" &
    university_rankings_clean$Status == "Public",
] |> nrow()
```

*Alternativa:*

```
nrow(
    university_rankings_clean[
        university_rankings_clean$Region == "Europe" &
        university_rankings_clean$Status == "Public",
    ]
)
```

</details>
</details>

In [ ]:
nrow(university_rankings_clean[uninversity_rankings_clean$Region == "Europe" & university_rankings_clean$Status == "Public", ])

[1] 251

<div class="alert alert-block alert-success">

Předchozí úlohu vyřešte pomocí funkce `subset()`.

<details>
<summary></summary>

```r
nrow(
    subset(
        university_rankings_clean,
        Region == "Europe" & Status == "Public"
    )
)
```

</details>

In [ ]:
nrow(subset(university_rankings_clean, Region == "Europe" & Status == "Public"))

[1] 251

<div class="alert alert-block alert-success">

Vyberte evropské univerzity a ve výsledku ponechte pouze jejich název, zemi a město.

<details>
<summary></summary>

```r
subset(
    university_rankings_clean,
    Region == "Europe",
    select = c(Name, Country.Territory, City)
)
```

*Alternativa:*

```r
university_rankings_clean[
    university_rankings_clean$Region == "Europe",
    c("Name", "Country.Territory", "City")
]
```

</details>

In [ ]:
uninversity_rankings_clean[university_rankings_clean$Region == "Europe", c("Name", "Country.Territory", "City")]

    Name
2   Imperial College London
4   University of Oxford
6   University of Cambridge
8   ETH Zurich
9   UCL
22  EPFL – École polytechnique fédérale de Lausanne
25  Technical University of Munich
34  Université PSL
35  The University of Edinburgh
37  King's College London
40  The University of Manchester
44  Institut Polytechnique de Paris
48  Delft University of Technology
57  University of Bristol
59  KU Leuven
60  University of Amsterdam
61  Ludwig-Maximilians-Universität München
62  The London School of Economics and Political Science (LSE)
67  The University of Warwick
68  University of Birmingham
70  Lund University
72  Sorbonne University
74  Trinity College Dublin, The University of Dublin
75  Université Paris-Saclay
77  University of Leeds
78  University of Glasgow
80  KTH Royal Institute of Technology
81  The University of Sheffield
83  Durham University
84  Universität Heidelberg
⋮   ⋮
586 Ca' Foscari University of Venice
589 Manchester Metropolitan University
590 Tallinn University of Technology (TalTech)
591 University of Debrecen
595 Free University of Bozen-Bolzano
600 Université Claude Bernard Lyon 1
605 Peter the Great St. Petersburg Polytechnic University
607 Christian-Albrechts-University zu Kiel
613 University of Eastern Finland
615 Universidade de Santiago de Compostela
617 University of Tromsø The Arctic University of Norway
618 University of Szeged
623 Hasselt University
624 Nottingham Trent University
625 Comillas Pontifical University
629 University of Crete
631 University of Chemistry and Technology, Prague
638 Comenius University Bratislava
641 University of Portsmouth
642 Abo Akademi University
646 University of Fribourg
650 University of the Basque Country
653 University of Klagenfurt
654 Kingston University, London
655 Université de Lille
658 Eastern Mediterranean University
660 TU Dortmund University
661 University of Plymouth
662 Karl-Franzens-Universitaet Graz
663 Universität Regensburg
    Country.Territory  City
2   United Kingdom     London
4   United Kingdom     Oxford
6   United Kingdom     Cambridge
8   Switzerland        Zurich
9   United Kingdom     London
22  Switzerland        Lausanne
25  Germany            Munich
34  France             Paris
35  United Kingdom     Edinburgh
37  United Kingdom     London
40  United Kingdom     Manchester
44  France             Paris
48  Netherlands        Delft
57  United Kingdom     Bristol
59  Belgium            Leuven
60  Netherlands        Amsterdam
61  Germany            Munich
62  United Kingdom     London
67  United Kingdom     England
68  United Kingdom     Birmingham
70  Sweden             Lund
72  France             Paris
74  Ireland            Dublin
75  France             Paris
77  United Kingdom     Leeds
78  United Kingdom     Glasgow
80  Sweden             Stockholm
81  United Kingdom     Sheffield
83  United Kingdom     Durham
84  Germany            Heidelberg
⋮   ⋮                  ⋮
586 Italy              Venice
589 United Kingdom     Manchester
590 Estonia            Tallinn
591 Hungary            Debrecen
595 Italy              Bolzano
600 France             Villeurbanne
605 Russian Federation St. Petersburg
607 Germany            Kiel
613 Finland            Kuopio
615 Spain              Santiago de Compostela
617 Norway             Tromso
618 Hungary            Szeged
623 Belgium            Diepenbeek
624 United Kingdom     Nottingham
625 Spain              Madrid
629 Greece             Heraklion
631 Czechia            Prague
638 Slovakia           Bratislava
641 United Kingdom     Portsmouth
642 Finland            Turku
646 Switzerland        Fribourg
650 Spain              Leioa
653 Austria            Klagenfurt
654 United Kingdom     Kingston upon Thames
655 France             Lille
658 Northern Cyprus    Famagusta
660 Germany            Dortmund
661 United Kingdom     Plymouth
662 Austria            Graz
663 Germany            Regensburg

<div class="alert alert-block alert-success">

Jaké je průměrné skóre akademické reputace (`AR.SCORE`) univerzit v datasetu?

<details>
<summary></summary>

43.67 (zaokrouhleno)

<details>
<summary></summary>

```r
mean(university_rankings_clean$AR.SCORE, na.rm = TRUE)
```

*Alternativa:*

```r
round(mean(university_rankings_clean$AR.SCORE, na.rm = TRUE), 2)
```

*Alternativa:*

```r
university_rankings_clean$AR.SCORE |> mean(na.rm = TRUE)
```

*Alternativa:*

```r
university_rankings_clean$AR.SCORE |> mean(na.rm = TRUE) |> round(2)
```

</details>
</details>

In [ ]:
mean(university_rankings_clean$AR.SCORE)

[1] 43.66968

<div class="alert alert-block alert-success">

Která univerzita má nejvyšší hodnotu `Overall.SCORE`?

<details>
<summary></summary>

Massachusetts Institute of Technology (MIT)

<details>
<summary></summary>

```r
university_rankings_clean$Name[
    university_rankings_clean$Overall.SCORE == max(university_rankings_clean$Overall.SCORE, na.rm = TRUE)
]
```

</details>
</details>

In [ ]:
university_rankings_clean[university_rankings_clean$Overall.SCORE ==max(university_rankings_clean$Overall.SCORE), "Name"]

[1] "Massachusetts Institute of Technology (MIT)"

<div class="alert alert-block alert-success">

Ve kterém městě je nejvíce univerzit?

<details>
<summary></summary>

Seoul: 13

<details>
<summary></summary>

```r
city_counts <- table(university_rankings_clean$City)
city_counts[city_counts == max(city_counts)]
```

</details>
</details>

In [ ]:
sort(table(university_rankings_clean$City), decreasing = TRUE)[1]

Seoul
   13

<div class="alert alert-block alert-success">

Je město s nejvíce univerzitami i městem s nejlépe hodnocenými univerzitami (**Overall.SCORE**)?

<details>
<summary></summary>

Ne. Město s nejlépe hodnocenými univerzitami je Stanford.

<details>
<summary></summary>

```r
city_mean_scores <- aggregate(
    Overall.SCORE ~ City,
    data = university_rankings_clean,
    FUN = mean
)

city_mean_scores[city_mean_scores$Overall.SCORE == max(city_mean_scores$Overall.SCORE), ]
```

*Alternativa:*

```r
city_mean_scores <- aggregate(
    Overall.SCORE ~ City,
    data = university_rankings_clean,
    FUN = mean
)

head(city_mean_scores[order(city_mean_scores$Overall.SCORE, decreasing = TRUE), ])
```

</details>
</details>

In [ ]:
sort(table(university_rankings_clean$Overall.SCORE), decreasing = TRUE)[1] == sort(table(university_rankings_clean$City), decreasing = TRUE)[1]

 28.3
FALSE

<div class="alert alert-block alert-success">

Jsou české univerzity v průměru lépe hodnocené (**Overall.SCORE**) než německé?

<details>
<summary></summary>

Ne. České univerzity mají průměrné skóre 34.74, zatímco německé 46.41.

<details>
<summary></summary>

```r
mean(
    university_rankings_clean$Overall.SCORE[
        university_rankings_clean$Country.Territory == "Czechia"
    ]
)

mean(
    university_rankings_clean$Overall.SCORE[
        university_rankings_clean$Country.Territory == "Germany"
    ]
)
```

*Alternativa:*

```r
country_mean_scores <- aggregate(
    Overall.SCORE ~ Country.Territory,
    data = university_rankings_clean,
    FUN = mean
)

country_mean_scores[country_mean_scores$Country.Territory %in% c("Czechia", "Germany"), ]
```

</details>
</details>

In [181]:
mean_scores <- aggregate(Overall.SCORE ~ Country.Territory, university_rankings_clean, FUN = mean)

mean_scores[mean_scores$Country.Territory %in% c("Czechia", "Germany"), ]

mean_scores[mean_scores$Country.Territory == "Czechia", "Overall.SCORE"] > mean_scores[mean_scores$Country.Territory == "Germany", "Overall.SCORE"]

   Country.Territory Overall.SCORE
14 Czechia           34.74000
20 Germany           46.40833

[1] FALSE

<div class="alert alert-block alert-success">

Kolik z 10 nejlépe hodnocených (**Rank**) univerzit je neveřejných?

<details>
<summary></summary>

4

<details>
<summary></summary>

```r
sum(university_rankings_clean$Rank <= 10 & university_rankings_clean$Status != "Public")
```

*Alternativa:*

```r
sorted_universities <- university_rankings_clean[
    order(
        university_rankings_clean$Rank
    ),
]

sum(sorted_universities$Status[1:10] != "Public")
```


</details>
</details>

In [183]:
sum(university_rankings_clean$Rank <= 10 & university_rankings_clean$Status != "Public")

[1] 4

<div class="alert alert-block alert-success">

V jakém regionu je nejvíce velkých (**L**) a extrémně velkých univerzit (**XL**)?

<details>
<summary></summary>

Europe: 210

<details>
<summary></summary>

```
large_universities <- subset(
    university_rankings_clean,
    Size %in% c("L", "XL")
)

sort(table(large_universities$Region))
```

</details>
</details>

In [192]:
L_XL <- subset(university_rankings_clean, Size %in% c("L", "XL"), select = "Region")
sort(table(L_XL), decreasing =  TRUE)[1]

Europe
   210

<div class="alert alert-block alert-success">

Ve které zemi (**Country.Territory**) jsou v průměru nejlépe hodnocené univerzity (**Overall.SCORE**)?

<details>
<summary></summary>

Hong Kong SAR, China

<details>
<summary></summary>

```r
country_mean_scores <- aggregate(
    Overall.SCORE ~ Country.Territory,
    data = university_rankings_clean,
    FUN = mean
)

country_mean_scores[
    country_mean_scores$Overall.SCORE == max(country_mean_scores$Overall.SCORE),
]
```

</details>
</details>

In [198]:
bla <- aggregate(Overall.SCORE ~ Country.Territory, university_rankings_clean, FUN = mean)
bla[bla$Overall.SCORE == max(bla$Overall.SCORE), ]

   Country.Territory    Overall.SCORE
22 Hong Kong SAR, China 75.44286

<div class="alert alert-block alert-success">

Je velikost univerzity (**Size**) spjata s jejím hodnocením (**Overall.SCORE**)? Vypočítejte průměrné hodnocení pro každou možnou velikost univerzity.

<details>
<summary></summary>

Zdánlivě ano.

<details>
<summary></summary>

```r
aggregate(
    Overall.SCORE ~ Size,
    data = university_rankings_clean,
    FUN = mean
)
```

</details>
</details>

<div class="alert alert-block alert-success">

Která univerzita si nejlépe přilepšila v žebříčku (sloupce **Rank** a **Previous.Rank**)? Která se naopak nejvíce propadla?

<details>
<summary></summary>

Nejvíce si polepšila Singapore University of Technology and Design o 253 míst.

Nejvíce se propadla Lebanese University a to o 111 míst.

<details>
<summary></summary>

```
rank_change <- university_rankings_clean$Previous.Rank - university_rankings_clean$Rank

university_rankings_clean$Name[rank_change == max(rank_change)]
max(rank_change)

university_rankings_clean$Name[rank_change == min(rank_change)]
min(rank_change)
```

</details>
</details>

<div class="alert alert-block alert-success">

Ve kterém typu skóre (**AR.SCORE**, **ER.SCORE**, **FSR.SCORE**, **CPF.SCORE**, **IFR.SCORE**, **ISR.SCORE**, **IRN.SCORE**, **EO.SCORE**) si univerzity v průměru vedou nejhůře?

<details>
<summary></summary>

FSR.SCORE

<details>
<summary></summary>

```r
score_means <- colMeans(
    university_rankings_clean[
        , c(
            "AR.SCORE",
            "ER.SCORE",
            "FSR.SCORE",
            "CPF.SCORE",
            "IFR.SCORE",
            "ISR.SCORE",
            "IRN.SCORE",
            "EO.SCORE"
        )
    ]
)

names(score_means)[score_means == min(score_means)]
```

</details>
</details>

<div class="alert alert-block alert-success">

Které univerzity mají největší proporci zahraničních studentů (**ISR.SCORE**)?

<details>
<summary></summary>

Imperial College London; UCL; The University of Hong Kong; The University of New South Wales (UNSW Sydney); EPFL – École polytechnique fédérale de Lausanne; The University of Melbourne; The University of Sydney; Monash University; The University of Queensland; City University of Hong Kong (CityUHK); The London School of Economics and Political Science (LSE); The University of Western Australia; Queen Mary University of London; University of St Andrews; Hamad Bin Khalifa University (HBKU); Hong Kong Baptist University; Maastricht University; American University of Sharjah; University of Macau; Taylor\'s University; UCSI University; Universität Innsbruck; University of Luxembourg; Ajman University; Macau University of Science and Technology; INTI International University; Auckland University of Technology (AUT); Central Queensland University (CQUniversity Australia); IE University; USI - Università della Svizzera italiana; Asia Pacific University of Technology and Innovation (APU) Malaysia; Al Ain University; Technische Universität Bergakademie Freiberg; American University of Ras Al Khaimah; Management and Science University; Canadian University Dubai; American University in Dubai; Illinois Institute of Technology; Eastern Mediterranean University

<details>
<summary></summary>

```r
university_rankings_clean$Name[
    university_rankings_clean$ISR.SCORE == max(university_rankings_clean$ISR.SCORE)
]
```


</details>
</details>

# Příklady k procvičení

<div class="alert alert-block alert-success">

Zjistěte zastoupení veřejných a soukromých univerzit (sloupec **Status**).

<details>
<summary></summary>

Private for Profit: 11

Private not for Profit: 105

Public: 547

</details>

<div class="alert alert-block alert-success">

Jsou soukromé univerzity v průměru lépe hodnoceny než ty veřejné?

<details>
<summary></summary>

Ne. Veřejné univerzity jsou v průměru nejlépe hodnocené.

</details>

<div class="alert alert-block alert-success">

Kolik zemí má alespoň jednu univerzitu s celkovým hodnocením (**Overall.SCORE**) větší než 90?

<details>
<summary></summary>

6

</details>

<div class="alert alert-block alert-success">

Které univerzity mají nejlepší, a které naopak nejhorší, skóre zaměstnání absolventů (**EO.SCORE**)?

<details>
<summary></summary>

Nejlepší: Massachusetts Institute of Technology (MIT); Stanford University; University of Oxford; Harvard University; University of Cambridge; National University of Singapore (NUS); University of Pennsylvania; Seoul National University; The University of Tokyo; Columbia University; National Taiwan University (NTU); The London School of Economics and Political Science (LSE)

Nejhorší: Beijing University of Chemical Technology

</details>

<div class="alert alert-block alert-success">

Mají české univerzity nadprůměrné skóre zaměstnání absolventů?

<details>
<summary></summary>

Ne.

</details>

<div class="alert alert-block alert-success">

V kolika městech je pouze jedna univerzita? Jaké procento měst v žebříčku má pouze jednu univerzitu?

<details>
<summary></summary>

366; 78.21 %

</details>

<div class="alert alert-block alert-success">

# Shrnutí

Průzkum tabulky: `dim()`, `ncol()`, `nrow()`, `str()`, `summary()`, `head()`, `tail()`

Čištění dat: `na.omit()`, `duplicated()`

Ukládání dat: `write.csv()`

Výpočty nad tabulkou: `table()`, `aggregate()`

# Bonus

<div class="alert alert-block alert-success">

Pracujte s datovým souborem **titanic.csv**. Pasažéry se stejným příjmením (**surname**), kteří nastoupili ve steném přístavu (**embarked**) považujte za rodinu. 

> Zjistěte, kolik rodin přežilo celých a kolik rodin celých zemřelo. 

> Jaká velikost rodiny měla největší šanci na přežití?

In [ ]:
titanic <- read.csv("titanic.csv")
head(titanic)

  id  survived class name                                         sex    age
1 892 0        3     Kelly, Mr. James                             male   34.5
2 893 1        3     Wilkes, Mrs. James (Ellen Needs)             female 47.0
3 894 0        2     Myles, Mr. Thomas Francis                    male   62.0
4 895 0        3     Wirz, Mr. Albert                             female 27.0
5 896 1        3     Hirvonen, Mrs. Alexander (Helga E Lindqvist) female 22.0
6 897 0        3     Svensson, Mr. Johan Cervin                   male   14.0
  ticket  fare    embarked surname
1 330911   7.8292 Q        Kelly
2 363272   7.0000 S        Wilkes
3 240276   9.6875 Q        Myles
4 315154   8.6625 S        Wirz
5 3101298 12.2875 S        Hirvonen
6 7538     9.2250 S        Svensson