# Cvičení 2

## Pokročilá práce se vektory

<div class="alert alert-block alert-success">
    
Vytvořte vektor čísel od 1 do 7 a pojmenujte jej **days**.

<details>
<summary></summary>

```r
days <- 1:7
```

*Alternativa:*

```r
days <- seq(from = 1, to = 7, by = 1)
```

</details>

In [138]:
days <- 1:7
days

[1] 1 2 3 4 5 6 7

<div class="alert alert-block alert-success">
    
Zobrazte si atributy vektoru days pomocí funkce `attributes()`.

<details>
<summary></summary>

```r
attributes(days)
```

</details>

In [139]:
attributes(days)

NULL

<div class="alert alert-block alert-success">
    
Elementům přidejte jména (názvy) pomocí funkce `names()`. Názvy budou dny v týdnu.

<details>
<summary></summary>

```r
names(days) <- c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")
```

</details>

In [140]:
names(days) <- c("pondeli", "utery", "streda", "ctvrtek", "patek", "sobota", "nedele")
print(days)

pondeli   utery  streda ctvrtek   patek  sobota  nedele
      1       2       3       4       5       6       7

<div class="alert alert-block alert-success">
    
Znovu zobrazte atributy vektoru days pomocí funkce `attributes()`.

<details>
<summary></summary>

```r
attributes(days)
```

</details>

In [141]:
attributes(days)

$names
[1] "pondeli" "utery"   "streda"  "ctvrtek" "patek"   "sobota"  "nedele"

<div class="alert alert-block alert-success">
    
Extrahujte názvy vektoru **days** pomocí funkce `names()` a uložte je do vektoru **day_names**.

<details>
<summary></summary>

```r
day_names <- names(days)
```

</details>

In [142]:
day_names <- names(days)
day_names

[1] "pondeli" "utery"   "streda"  "ctvrtek" "patek"   "sobota"  "nedele"

## Matice

<div class="alert alert-block alert-success">
    
Zkontrolujte, zda jsou proměnné **days** a **day_names** skutečně vektory funkcí `is.vector()`.

<details>
<summary></summary>

```r
is.vector(days)

is.vector(day_names)
```

</details>

In [143]:
is.vector(days)
is.vector(day_names)

[1] TRUE

[1] TRUE

<div class="alert alert-block alert-success">
    
Vytvořte z vektoru **days** a **day_names** matice, které uložte do nových proměnných. Použijte funkci `matrix()`.

<details>
<summary></summary>

```r
days_matrix <- matrix(days)

day_names_matrix <- matrix(day_names)
```

</details>

In [144]:
days_matrix <- matrix(days)
day_names_matrix <- matrix(day_names)

<div class="alert alert-block alert-success">
    
Zkontrolujte, zda jsou nové proměnné skutečně maticemi funkcí `is.matrix()`.

<details>
<summary></summary>

```r
is.matrix(days_matrix)

is.matrix(day_names_matrix)
```

</details>

In [145]:
is.matrix(days_matrix)
is.matrix(day_names_matrix)

[1] TRUE

[1] TRUE

<div class="alert alert-block alert-success">
    
Vypočítejte délku vektorů **days** a **day_names**. Zkuste to stejné provést i s maticemi.

<details>
<summary></summary>

```r
length(days)

length(day_names)

length(days_matrix)

length(day_names_matrix)
```

</details>

In [146]:
length(days)
length(day_names)

length(days_matrix)
length(day_names_matrix)

[1] 7

[1] 7

[1] 7

[1] 7

<div class="alert alert-block alert-success">
    
Zjistěte dimenze matic(e) pomocí funkce `dim()`. Vyzkoušejte také funkce `nrow()` a `ncol()`.

<details>
<summary></summary>

```r
dim(days_matrix)

nrow(days_matrix)

ncol(days_matrix)
```

</details>

In [147]:
dim(days_matrix)
nrow(days_matrix)
ncol(days_matrix)

[1] 7 1

[1] 7

[1] 1

<div class="alert alert-block alert-success">
    
Vytvořte matici o jednom řádku z vektoru **days**. Použite funkci `matrix()` nebo funkci `t()`.

<details>
<summary></summary>

```r
matrix(days, nrow = 1)
```

*Alternativa:*

```r
t(days_matrix)
```

</details>

In [148]:
matrix(days, nrow = 1)
t(days_matrix)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1    2    3    4    5    6    7

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1    2    3    4    5    6    7

<div class="alert alert-block alert-success">
    
Přidejte matici **days_matrix** jména pomocí funkcí `colnames()` a `rownames()`.

<details>
<summary></summary>

```r
rownames(days_matrix) <- day_names
colnames(days_matrix) <- "week"
```

</details>

In [149]:
colnames(days_matrix) <- "week"
rownames(days_matrix) <- day_names

<div class="alert alert-block alert-success">
    
Vytvořte matici náhodných celých čísel z intervalu $[-50, 40]$ o dimenzích $3 \times 8$.

<details>
<summary></summary>

```r
round(matrix(runif(3 * 8, min = -50, max = 40), nrow = 3))
```

*Alternativa:*

```r
runif(3 * 8, min = -50, max = 40) |> matrix(nrow = 3) |> round()
```

</details>

In [150]:
round(matrix(runif(3 * 8, min = -50, max = 40), nrow = 3))

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] -25   8   -33   25  -8   -16  -4   -12
[2,]  24  17    13  -21  34   -39  -8   -48
[3,]   6   5   -12   37   7    25  33    19

<div class="alert alert-block alert-success">
    
Vytvořte matici rozměru $4 \times 5$ obsahující čísla od 1 do 20 seřazených sestupně po řádcích.

<details>
<summary></summary>

```r
20:1 |> matrix(nrow = 4, byrow = TRUE)
```

*Alternativa:*

```r
1:20 |> rev() |> matrix(nrow = 4, byrow = TRUE)
```

</details>

In [151]:
matrix(20:1, nrow = 4, byrow = TRUE)

     [,1] [,2] [,3] [,4] [,5]
[1,] 20   19   18   17   16
[2,] 15   14   13   12   11
[3,] 10    9    8    7    6
[4,]  5    4    3    2    1

<div class="alert alert-block alert-success">

## Logické operátory a indexování vektorů

|  operátor | syntax v R  |
|---|---|
|rovná se | == |
|nerovná se| != |
|menší|<|
|větší|>|
|menší nebo rovno| <=|
|větší nebo rovno| >=|
|je uvnitř| %in%|
| a | & |
| a které uvažuje pouze první element | && |
| nebo | \| |
| nebo které uvažuje pouze první element | \| \| |
| negace | ! |



| množinová operace | syntax v R  |
|---|---|
| průnik | intersect |
| sjednocení | union |
| množinový rozdíl | setdiff |

In [152]:
seminar_01_names = c(
  "Jan", "Adéla", "Mojmír", "Karel", "Ladislav",
  "Marek", "Adéla", "Karolína", "Přemysl", "Tomáš",
  "Martin", "Lucie", "Ondřej", "Tereza", "David",
  "Petra", "Jakub", "Veronika", "Filip", "Anna",
  "Michal", "Barbora", "Dominik", "Kristýna", "Jan",
  "Vojtěch", "Nikola", "Roman", "Monika", "Jiří",
  "Kateřina", "Adam", "Eliška", "Josef", "Hana",
  "Radek", "Alena", "Patrik", "Lenka", "Marek"
)

seminar_02_names = c(
  "Jan", "Adéla", "Radek", "Daniel", "Pavel",
  "Jindřich", "Pavla", "Ivana", "Radim", "Tomáš",
  "Martin", "Lucie", "Jakub", "Eva", "David",
  "Klára", "Filip", "Anna", "Michal", "Barbora",
  "Ondřej", "Petra", "Dominika", "Kristýna", "Jan",
  "Vojtěch", "Nikola", "Roman", "Monika", "Jiří",
  "Kateřina", "Adam", "Eliška", "Josef", "Hana",
  "Lukáš", "Zuzana", "Patrik", "Lenka", "Pavel"
)

seminar_01_surnames = c(
  "Novák", "Svobodová", "Dvořák", "Černý", "Procházka",
  "Kučera", "Veselá", "Horáková", "Němec", "Pospíšil",
  "Hájek", "Jelínková", "Král", "Růžičková", "Beneš",
  "Fialová", "Sedláček", "Navrátilová", "Pokorný", "Mareková",
  "Novotný", "Krejčová", "Šimek", "Kratochvílová", "Novák",
  "Malý", "Urbanová", "Blažek", "Křížová", "Doležal",
  "Zemanová", "Kolář", "Kopecká", "Vaněk", "Čermáková",
  "Holub", "Bartošová", "Soukup", "Dušková", "Horák"
)

seminar_02_surnames = c(
  "Novák", "Svobodová", "Dvořák", "Malý", "Černý",
  "Kučera", "Veselá", "Němcová", "Pospíšil", "Hájek",
  "Jelínek", "Králová", "Růžička", "Benešová", "Fiala",
  "Sedláček", "Navrátil", "Pokorná", "Marek", "Novotný",
  "Krejčí", "Šimková", "Kratochvíl", "Malá", "Urban",
  "Blažková", "Kříž", "Doležalová", "Zeman", "Kolář",
  "Kopecká", "Vaněk", "Čermák", "Holub", "Bartoš",
  "Soukupová", "Dušek", "Procházková", "Horák", "Novák"
)

<div class="alert alert-block alert-success">
    
Kolik Adél je v každé ze seminárních skupin?

<details>
<summary></summary>

seminář 1: 2

seminář 2: 1

<details>
<summary></summary>

```r
sum(seminar_01_names == "Adéla")
sum(seminar_02_names == "Adéla")
```

</details>
</details>

In [153]:
sum(seminar_01_names == "Adéla")
sum(seminar_02_names == "Adéla")

[1] 2

[1] 1

<div class="alert alert-block alert-success">

Kolik studentů v první seminární skupině se jmenuje Jan nebo Marek?

<details>
<summary></summary>

4

<details>
<summary></summary>

```r
sum(seminar_01_names %in% c("Jan", "Marek"))
```

</details>
</details>

In [154]:
sum(seminar_01_names == "Jan" | seminar_01_names == "Marek")

[1] 4

<div class="alert alert-block alert-success">

Na kterých pozicích v první seminární skupině se nachází studentka Adéla?

<details>
<summary></summary>

2, 7

<details>
<summary></summary>

```r
which(seminar_01_names == "Adéla")
```

</details>
</details>

In [155]:
which(seminar_01_names == "Adéla")

[1] 2 7

<div class="alert alert-block alert-success">

Vypište všechna příjmení studentů, kteří se jmenují Jan, v první seminární skupině.

<details>
<summary></summary>

Novák, Novák

<details>
<summary></summary>

```r
seminar_01_surnames[seminar_01_names == "Jan"]
```

</details>
</details>

In [156]:
seminar_01_surnames[seminar_01_names == "Jan"]

[1] "Novák" "Novák"

<div class="alert alert-block alert-success">
    
Která příjmení z první seminární skupiny se objevují i v druhé seminární skupině?

<details>
<summary></summary>

Novák, Svobodová, Dvořák, Malý, Černý, Kučera, Veselá, Pospíšil, Hájek, Sedláček, Novotný, Kolář, Kopecká, Vaněk, Holub, Horák

<details>
<summary></summary>

```r
unique(seminar_02_surnames[seminar_02_surnames %in% seminar_01_surnames])
```

</details>

In [157]:
unique(intersect(seminar_01_surnames, seminar_02_surnames))

 [1] "Novák"     "Svobodová" "Dvořák"    "Černý"     "Kučera"    "Veselá"
 [7] "Pospíšil"  "Hájek"     "Sedláček"  "Novotný"   "Malý"      "Kolář"
[13] "Kopecká"   "Vaněk"     "Holub"     "Horák"

<div class="alert alert-block alert-success">

Kolik studentů v první seminární skupině má příjmení Novák?

<details>
<summary></summary>

2

<details>
<summary></summary>

```r
table(seminar_01_surnames)["Novák"]
```

*Alternativa:*

```r
sum(seminar_01_surnames == "Novák")
```

</details>
</details>

In [158]:
table(seminar_01_surnames)["Novák"]
sum(seminar_01_surnames == "Novák")

Novák
    2

[1] 2

<div class="alert alert-block alert-success">

Kolik studentů v druhé seminární skupině nemá příjmení Novák?

<details>
<summary></summary>

38

<details>
<summary></summary>

```r
sum(seminar_02_surnames != "Novák")
```

</details>
</details>

In [159]:
sum(seminar_02_surnames != "Novák")

[1] 38

<div class="alert alert-block alert-success">

Vypište jména studentů, jejichž příjmení je Horák nebo Horáková.

<details>
<summary></summary>

Karolína, Marek, Lenka

<details>
<summary></summary>

```r
seminar_01_names[seminar_01_surnames %in% c("Horák", "Horáková")]
seminar_02_names[seminar_02_surnames %in% c("Horák", "Horáková")]
```

</details>
</details>

In [160]:
seminar_01_names[seminar_01_surnames %in% c("Horák", "Horáková")]
seminar_02_names[seminar_02_surnames %in% c("Horák", "Horáková")]

[1] "Karolína" "Marek"

[1] "Lenka"

<div class="alert alert-block alert-success">
    
Jaké je nejčastější příjmení v každé seminární skupině?

<details>
<summary></summary>

seminář 1: Novák

seminář 2: Novák

<details>
<summary></summary>

```r
table(seminar_01_surnames)[table(seminar_01_surnames) == max(table(seminar_01_surnames))]

table(seminar_02_surnames)[table(seminar_02_surnames) == max(table(seminar_02_surnames))]
```

</details>
</details>

In [161]:
table(seminar_01_surnames)[table(seminar_01_surnames) == max(table(seminar_01_surnames))]
table(seminar_02_surnames)[table(seminar_02_surnames) == max(table(seminar_02_surnames))]

Novák
    2

Novák
    2

<div class="alert alert-block alert-success">

Kolik různých příjmení se objevuje pouze v první seminární skupině?

<details>
<summary></summary>

23

<details>
<summary></summary>

```r
length(setdiff(unique(seminar_01_surnames), unique(seminar_02_surnames)))
```

</details>
</details>

In [162]:
length(setdiff(unique(seminar_01_surnames), unique(seminar_02_surnames)))

[1] 23

<div class="alert alert-block alert-success">
    
Jaké je nejčastější jméno v každé seminářní skupině a kolikrát se vyskytuje?

<details>
<summary></summary>

seminář 1: Adéla, Jan, Marek - 2

seminář 2: Jan, Pavel - 2

<details>
<summary></summary>

```r
table(seminar_01_names)[table(seminar_01_names) == max(table(seminar_01_names))]

table(seminar_02_names)[table(seminar_02_names) == max(table(seminar_02_names))]
```

</details>
</details>

In [163]:
table(seminar_01_names)[table(seminar_01_names) == max(table(seminar_01_names))]
table(seminar_02_names)[table(seminar_02_names) == max(table(seminar_02_names))]

seminar_01_names
Adéla   Jan Marek
    2     2     2

seminar_02_names
  Jan Pavel
    2     2

<div class="alert alert-block alert-success">
    
Jsou ve dvou různých seminárních skupinách studenti se stejným jménem i příjmením? Pokud ano, kteří to jsou?

<details>
<summary></summary>

Jan Novák, Adéla Svobodová

<details>
<summary></summary>

```r
seminar_01_full_names = paste(seminar_01_names, seminar_01_surnames)
seminar_02_full_names = paste(seminar_02_names, seminar_02_surnames)

intersect(seminar_01_full_names, seminar_02_full_names)
```

*Alternativa:*

```r
seminar_01_full_names = paste(seminar_01_names, seminar_01_surnames)
seminar_02_full_names = paste(seminar_02_names, seminar_02_surnames)

seminar_01_full_names[seminar_01_full_names %in% seminar_02_full_names]
```

</details>
</details>

In [164]:
seminar_01_full_names <- paste(seminar_01_names, seminar_01_surnames)
seminar_02_full_names <- paste(seminar_02_names, seminar_02_surnames)

intersect(seminar_01_full_names, seminar_02_full_names)

[1] "Jan Novák"       "Adéla Svobodová"

<div class="alert alert-block alert-success">
    
Která jména se opakují v obou seminárních skupinách? Vypište je oddělena čárkou. Hodit se Vám může funkce `paste()` s vhodnými argumenty.

<details>
<summary></summary>
Jan, Adéla, Tomáš, Martin, Lucie, Ondřej, David, Petra, Jakub, Filip, Anna, Michal, Barbora, Kristýna, Vojtěch, Nikola, Roman, Monika, Jiří, Kateřina, Adam, Eliška, Josef, Hana, Radek, Patrik, Lenka

27

<details>
<summary></summary>

```r
paste(intersect(seminar_01_names, seminar_02_names), collapse = ", ")

length(intersect(seminar_01_names, seminar_02_names))
```

</details>
</details>

In [165]:
paste(intersect(seminar_01_names, seminar_02_names), collapse = ", ")
length(intersect(seminar_01_names, seminar_02_names))

[1] "Jan, Adéla, Tomáš, Martin, Lucie, Ondřej, David, Petra, Jakub, Filip, Anna, Michal, Barbora, Kristýna, Vojtěch, Nikola, Roman, Monika, Jiří, Kateřina, Adam, Eliška, Josef, Hana, Radek, Patrik, Lenka"

[1] 27

<div class="alert alert-block alert-success">
    
Kolik různých jmen se objevuje napříč seminárními skupinami?

<details>
<summary></summary>

48

<details>
<summary></summary>

```r
length(union(seminar_01_names, seminar_02_names))
```

</details>
</details>

In [166]:
length(unique(union(seminar_01_names, seminar_02_names)))

[1] 48

In [167]:
students = paste(seminar_01_names, seminar_01_surnames)

points = c(
    8, 10, 6, 9, 7,
    5, 10, 8, 6, 9,
    7, 8, 5, 10, 9,
    6, 8, 9, 7, 10,
    8, 9, 6, 7, 8,
    10, 9, 5, 8, 7,
    6, 9, 10, 8, 7,
    5, 8, 9, 10, 6
)

set.seed(1)

attendance = matrix(
    sample(c(TRUE, FALSE), 40 * 13, replace = TRUE, prob = c(0.9, 0.1)),
    nrow = 40
)

<div class="alert alert-block alert-success">

Jaké je bodové rozložení, resp. kolik studentů získalo jednotlivé počty bodů?

<details>
<summary></summary>

5 bodů - 4

6 bodů - 6

7 bodů - 6

8 bodů - 9

9 bodů - 8

10 bodů - 7

<details>
<summary></summary>

```r
table(points)
```

</details>
</details>

In [168]:
table(points)

points
 5  6  7  8  9 10
 4  6  6  9  8  7

<div class="alert alert-block alert-success">

Jaký podíl studentů získal jednotlivé počty bodů? Použijte funkci `prop.table()`.

<details>
<summary></summary>

5 bodů - 10 %

6 bodů - 15 %

7 bodů - 15 %

8 bodů - 22.5%

9 bodů = 20%

10 bodů = 17.5%

<details>
<summary></summary>

```r
prop.table(table(points))
```

</details>
</details>

In [169]:
prop.table(table(points))

points
    5     6     7     8     9    10
0.100 0.150 0.150 0.225 0.200 0.175

<div class="alert alert-block alert-success">

Vypište základní statistiky počtu bodů.


<details>
<summary></summary>

```r
summary(points)
```

</details>

In [170]:
summary(points)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   5.00    6.75    8.00    7.80    9.00   10.00

## Logické operátory a indexování matic

<div class="alert alert-block alert-success">

Vytvořte matici **student_matrix**, která bude mít dva sloupce: jméno studenta a počet bodů.

<details>
<summary></summary>

```r
student_matrix = cbind(students, points)
```

</details>

In [171]:
student_matrix <- cbind(students, points)
student_matrix

      students               points
 [1,] Jan Novák              8
 [2,] Adéla Svobodová        10
 [3,] Mojmír Dvořák          6
 [4,] Karel Černý            9
 [5,] Ladislav Procházka     7
 [6,] Marek Kučera           5
 [7,] Adéla Veselá           10
 [8,] Karolína Horáková      8
 [9,] Přemysl Němec          6
[10,] Tomáš Pospíšil         9
[11,] Martin Hájek           7
[12,] Lucie Jelínková        8
[13,] Ondřej Král            5
[14,] Tereza Růžičková       10
[15,] David Beneš            9
[16,] Petra Fialová          6
[17,] Jakub Sedláček         8
[18,] Veronika Navrátilová   9
[19,] Filip Pokorný          7
[20,] Anna Mareková          10
[21,] Michal Novotný         8
[22,] Barbora Krejčová       9
[23,] Dominik Šimek          6
[24,] Kristýna Kratochvílová 7
[25,] Jan Novák              8
[26,] Vojtěch Malý           10
[27,] Nikola Urbanová        9
[28,] Roman Blažek           5
[29,] Monika Křížová         8
[30,] Jiří Doležal           7
[31,] Kateřina Zemanová      6
[32,] Adam Kolář             9
[33,] Eliška Kopecká         10
[34,] Josef Vaněk            8
[35,] Hana Čermáková         7
[36,] Radek Holub            5
[37,] Alena Bartošová        8
[38,] Patrik Soukup          9
[39,] Lenka Dušková          10
[40,] Marek Horák            6

<div class="alert alert-block alert-success">

Jaký je datový typ proměnné **student_matrix**?

<details>
<summary></summary>

```r
character
```

</details>

In [172]:
typeof(student_matrix)

[1] "character"

<div class="alert alert-block alert-success">

Vypište prvních osm řádků matice **student_matrix**.

<details>
<summary></summary>

```r
student_matrix[1:8, ]
```

</details>

In [173]:
student_matrix[1:8, ]

     students           points
[1,] Jan Novák          8
[2,] Adéla Svobodová    10
[3,] Mojmír Dvořák      6
[4,] Karel Černý        9
[5,] Ladislav Procházka 7
[6,] Marek Kučera       5
[7,] Adéla Veselá       10
[8,] Karolína Horáková  8

<div class="alert alert-block alert-success">

Vypište pouze jména studentů, kteří získali alespoň 9 bodů.

<details>
<summary></summary>

Adéla Svobodová, Karel Černý, Adéla Veselá, Tomáš Pospíšil, Tereza Růžičková, David Beneš, Veronika Navrátilová, Anna Mareková, Barbora Krejčová, Vojtěch Malý, Nikola Urbanová, Adam Kolář, Eliška Kopecká, Patrik Soukup, Lenka Dušková

<details>
<summary></summary>

```r
students[points >= 9]
```

*Alternativa:*

```r
student_matrix[points >= 9, 1]
```

</details>
</details>

In [174]:
students[points >= 9]

 [1] "Adéla Svobodová"      "Karel Černý"          "Adéla Veselá"
 [4] "Tomáš Pospíšil"       "Tereza Růžičková"     "David Beneš"
 [7] "Veronika Navrátilová" "Anna Mareková"        "Barbora Krejčová"
[10] "Vojtěch Malý"         "Nikola Urbanová"      "Adam Kolář"
[13] "Eliška Kopecká"       "Patrik Soukup"        "Lenka Dušková"

<div class="alert alert-block alert-success">

Kolik studentů získalo přesně 8 bodů?

<details>
<summary></summary>

9

<details>
<summary></summary>

```r
sum(points == 8)
```

</details>
</details>

In [175]:
length(students[points == 8])

[1] 9

<div class="alert alert-block alert-success">

Který student získal nejméně bodů?

<details>
<summary></summary>

Marek Kučera, Ondřej Král, Roman Blažek, Radek Holub

<details>
<summary></summary>


```r
students[points == min(points)]
```

*pozor, časté špatné řešení!*

students[which.min(points)]

students[points == which.min(points)]
</details>
</details>

In [176]:
students[points == min(points)]

[1] "Marek Kučera" "Ondřej Král"  "Roman Blažek" "Radek Holub"

<div class="alert alert-block alert-success">

Kolik studentů získalo nadprůměrný počet bodů?

<details>
<summary></summary>

24

<details>
<summary></summary>

```r
sum(points > mean(points))
```

</details>
</details>

In [177]:
mean(points)
length(students[points > mean(points)])

[1] 7.8

[1] 24

<div class="alert alert-block alert-success">

Jaký je nejčastější počet bodů?

<details>
<summary></summary>

8

<details>
<summary></summary>

```r
names(table(points)[table(points) == max(table(points))])
```

</details>
</details>

In [178]:
names(table(points)[table(points) == max(table(points))])

[1] "8"

<div class="alert alert-block alert-success">

Na kterých pozicích se nacházejí studenti, kteří získali méně než 6 bodů?

<details>
<summary></summary>

6, 13, 28, 36

<details>
<summary></summary>

```r
which(points < 6)
```

</details>
</details>

In [179]:
which(points < 6)

[1]  6 13 28 36

<div class="alert alert-block alert-success">

Pojmenujte řádky matice **attendance** jmény studentů.


<details>
<summary></summary>

```r
rownames(attendance) = students
```

</details>

In [180]:
rownames(attendance) <- students
attendance

                       [,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]
Jan Novák               TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
Adéla Svobodová         TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Mojmír Dvořák           TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE
Karel Černý            FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
Ladislav Procházka      TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Marek Kučera            TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
Adéla Veselá           FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Karolína Horáková       TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Přemysl Němec           TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Tomáš Pospíšil          TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE
Martin Hájek            TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE FALSE
Lucie Jelínková         TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE
Ondřej Král             TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE
Tereza Růžičková        TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
David Beneš             TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
Petra Fialová           TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Jakub Sedláček          TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Veronika Navrátilová   FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
Filip Pokorný           TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE
Anna Mareková           TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE FALSE FALSE
Michal Novotný         FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
Barbora Krejčová        TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Dominik Šimek           TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Kristýna Kratochvílová  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Jan Novák               TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
Vojtěch Malý            TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE
Nikola Urbanová         TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Roman Blažek            TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Monika Křížová          TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE
Jiří Doležal            TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Kateřina Zemanová       TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Adam Kolář              TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Eliška Kopecká          TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Josef Vaněk             TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE
Hana Čermáková          TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
Radek Holub             TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Alena Bartošová         TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Patrik Soukup           TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Lenka Dušková           TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE
Marek Horák             TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
                       [,10] [,11] [,12] [,13]
Jan Novák               TRUE  TRUE  TRUE  TRUE
Adéla Svobodová         TRUE  TRUE  TRUE  TRUE
Mojmír Dvořák           TRUE FALSE  TRUE  TRUE
Karel Černý             TRUE  TRUE  TRUE FALSE
Ladislav Procházka      TRUE FALSE  TRUE  TRUE
Marek Kučera            TRUE  TRUE  TRUE  TRUE
Adéla Veselá            TRUE  TRUE  TRUE  TRUE
Karolína Horáková       TRUE  TRUE FALSE  TRUE
Přemysl Němec           TRUE  TRUE  TRUE  TRUE
Tomáš Pospíšil          TRUE FALSE  TRUE  TRUE
Martin Hájek            TRUE FALSE FALSE  TRUE
Lucie Jelínková         TRUE  TRUE  TRUE FALSE
Ondřej Král            FALSE  TRUE  TRUE  TRUE
Tereza Růžičková        TRUE  TRUE  TRUE  TRUE
David Beneš             TRUE  TRUE  TRUE  TRUE
Petra Fialová           TRUE  TRUE  TRUE  TRUE
Jakub Sedláček          TRUE  TRUE  TRUE  TRUE
Veronika Navrátilová    TRUE  TRUE FALSE  TRUE
Filip Pokorný           TRUE  TRUE  TRUE  TRUE
Anna Mareková           TRUE  TRUE  TRUE  TRUE
Michal Novotný          TRUE  TRUE  TRUE  TRUE
Barbora Krejčová        TRUE  TRUE  TRUE  TRUE
Dominik Šimek           TRUE  TRUE  TRUE  TRUE
Kristýna Kratochvílová FALSE  TRUE  TRUE  TRUE
Jan Novák               TRUE  TRUE  TRUE  TRUE
Vojtěch Malý            TRUE  TRUE FALSE FALSE
Nikola Urbanová         TRUE  TRUE  TRUE  TRUE
Roman Blažek            TRUE FALSE  TRUE  TRUE
Monika Křížová          TRUE  TRUE  TRUE  TRUE
Jiří Doležal           FALSE  TRUE  TRUE  TRUE
Kateřina Zemanová       TRUE FALSE  TRUE  TRUE
Adam Kolář              TRUE  TRUE FALSE  TRUE
Eliška Kopecká         FALSE  TRUE  TRUE  TRUE
Josef Vaněk             TRUE  TRUE  TRUE  TRUE
Hana Čermáková          TRUE  TRUE  TRUE  TRUE
Radek Holub             TRUE  TRUE  TRUE  TRUE
Alena Bartošová         TRUE  TRUE  TRUE  TRUE
Patrik Soukup           TRUE  TRUE  TRUE  TRUE
Lenka Dušková           TRUE  TRUE  TRUE  TRUE
Marek Horák             TRUE FALSE  TRUE  TRUE

<div class="alert alert-block alert-success">

Pojmenujte sloupce matice **attendance** názvy `"Week1"` až `"Week13"`.

<details>
<summary></summary>

```r
colnames(attendance) = paste("Week", 1:13, sep = "")
```

</details>

In [181]:
colnames(attendance) <- paste("Week", 1:13, sep = "")
attendance

                       Week1 Week2 Week3 Week4 Week5 Week6 Week7 Week8 Week9
Jan Novák               TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
Adéla Svobodová         TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Mojmír Dvořák           TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE
Karel Černý            FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
Ladislav Procházka      TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Marek Kučera            TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
Adéla Veselá           FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Karolína Horáková       TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Přemysl Němec           TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Tomáš Pospíšil          TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE
Martin Hájek            TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE FALSE
Lucie Jelínková         TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE
Ondřej Král             TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE
Tereza Růžičková        TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
David Beneš             TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
Petra Fialová           TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Jakub Sedláček          TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Veronika Navrátilová   FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
Filip Pokorný           TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE
Anna Mareková           TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE FALSE FALSE
Michal Novotný         FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
Barbora Krejčová        TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Dominik Šimek           TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Kristýna Kratochvílová  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Jan Novák               TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
Vojtěch Malý            TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE
Nikola Urbanová         TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Roman Blažek            TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Monika Křížová          TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE
Jiří Doležal            TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Kateřina Zemanová       TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Adam Kolář              TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Eliška Kopecká          TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Josef Vaněk             TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE
Hana Čermáková          TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
Radek Holub             TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Alena Bartošová         TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Patrik Soukup           TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
Lenka Dušková           TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE
Marek Horák             TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
                       Week10 Week11 Week12 Week13
Jan Novák               TRUE   TRUE   TRUE   TRUE
Adéla Svobodová         TRUE   TRUE   TRUE   TRUE
Mojmír Dvořák           TRUE  FALSE   TRUE   TRUE
Karel Černý             TRUE   TRUE   TRUE  FALSE
Ladislav Procházka      TRUE  FALSE   TRUE   TRUE
Marek Kučera            TRUE   TRUE   TRUE   TRUE
Adéla Veselá            TRUE   TRUE   TRUE   TRUE
Karolína Horáková       TRUE   TRUE  FALSE   TRUE
Přemysl Němec           TRUE   TRUE   TRUE   TRUE
Tomáš Pospíšil          TRUE  FALSE   TRUE   TRUE
Martin Hájek            TRUE  FALSE  FALSE   TRUE
Lucie Jelínková         TRUE   TRUE   TRUE  FALSE
Ondřej Král            FALSE   TRUE   TRUE   TRUE
Tereza Růžičková        TRUE   TRUE   TRUE   TRUE
David Beneš             TRUE   TRUE   TRUE   TRUE
Petra Fialová           TRUE   TRUE   TRUE   TRUE
Jakub Sedláček          TRUE   TRUE   TRUE   TRUE
Veronika Navrátilová    TRUE   TRUE  FALSE   TRUE
Filip Pokorný           TRUE   TRUE   TRUE   TRUE
Anna Mareková           TRUE   TRUE   TRUE   TRUE
Michal Novotný          TRUE   TRUE   TRUE   TRUE
Barbora Krejčová        TRUE   TRUE   TRUE   TRUE
Dominik Šimek           TRUE   TRUE   TRUE   TRUE
Kristýna Kratochvílová FALSE   TRUE   TRUE   TRUE
Jan Novák               TRUE   TRUE   TRUE   TRUE
Vojtěch Malý            TRUE   TRUE  FALSE  FALSE
Nikola Urbanová         TRUE   TRUE   TRUE   TRUE
Roman Blažek            TRUE  FALSE   TRUE   TRUE
Monika Křížová          TRUE   TRUE   TRUE   TRUE
Jiří Doležal           FALSE   TRUE   TRUE   TRUE
Kateřina Zemanová       TRUE  FALSE   TRUE   TRUE
Adam Kolář              TRUE   TRUE  FALSE   TRUE
Eliška Kopecká         FALSE   TRUE   TRUE   TRUE
Josef Vaněk             TRUE   TRUE   TRUE   TRUE
Hana Čermáková          TRUE   TRUE   TRUE   TRUE
Radek Holub             TRUE   TRUE   TRUE   TRUE
Alena Bartošová         TRUE   TRUE   TRUE   TRUE
Patrik Soukup           TRUE   TRUE   TRUE   TRUE
Lenka Dušková           TRUE   TRUE   TRUE   TRUE
Marek Horák             TRUE  FALSE   TRUE   TRUE

<div class="alert alert-block alert-success">

Vypište docházku prvních pěti studentů.

<details>
<summary></summary>

```r
attendance[1:5, ]
```

</details>

In [182]:
attendance[1:5, ]

                   Week1 Week2 Week3 Week4 Week5 Week6 Week7 Week8 Week9 Week10
Jan Novák           TRUE TRUE  TRUE  FALSE TRUE  TRUE   TRUE TRUE   TRUE TRUE
Adéla Svobodová     TRUE TRUE  TRUE   TRUE TRUE  TRUE   TRUE TRUE   TRUE TRUE
Mojmír Dvořák       TRUE TRUE  TRUE   TRUE TRUE  TRUE  FALSE TRUE   TRUE TRUE
Karel Černý        FALSE TRUE  TRUE   TRUE TRUE  TRUE   TRUE TRUE  FALSE TRUE
Ladislav Procházka  TRUE TRUE  TRUE   TRUE TRUE  TRUE   TRUE TRUE   TRUE TRUE
                   Week11 Week12 Week13
Jan Novák           TRUE  TRUE    TRUE
Adéla Svobodová     TRUE  TRUE    TRUE
Mojmír Dvořák      FALSE  TRUE    TRUE
Karel Černý         TRUE  TRUE   FALSE
Ladislav Procházka FALSE  TRUE    TRUE

<div class="alert alert-block alert-success">

Kolik studentů bylo přítomno na prvním cvičení?

<details>
<summary></summary>

36

<details>
<summary></summary>

```r
sum(attendance[, 1])
```

</details>
</details>

In [183]:
sum(attendance[, 1])

[1] 36

<div class="alert alert-block alert-success">

Na kterém cvičení byla nejvyšší účast?

<details>
<summary></summary>

2


<details>
<summary></summary>

```r
colnames(attendance)[colSums(attendance) == max(colSums(attendance))]
```

</details>
</details>

In [184]:
colnames(attendance)[colSums(attendance) == max(colSums(attendance))]

[1] "Week2"

<div class="alert alert-block alert-success">

Jaký podíl studentů má docházku na všech cvičeních?

<details>
<summary></summary>

25 %

<details>
<summary></summary>

```r
prop.table(table(rowSums(attendance) == ncol(attendance)))
```

*Alternativa:*

```r
mean(rowMeans(attendance) == 1)
```

*Alternativa:*

```r
mean(rowSums(attendance) == ncol(attendance))
```

</details>
</details>

In [185]:
prop.table(table(rowSums(attendance) == ncol(attendance)))

FALSE  TRUE
 0.75  0.25

<div class="alert alert-block alert-success">

Kolik studentů chybělo na třetím cvičení?

<details>
<summary></summary>

3

<details>
<summary></summary>

```r
sum(!attendance[, 3])
```

</details>
</details>

In [186]:
sum(!attendance[ , 3])

[1] 3

<div class="alert alert-block alert-success">

Kolik cvičení navštívili všichni studenti?

<details>
<summary></summary>

0

<details>
<summary></summary>

```r
sum(colSums(attendance) == nrow(attendance))
```

</details>
</details>

In [187]:
sum(colSums(attendance) == 40)

[1] 0

<div class="alert alert-block alert-success">

Vypište jména studentů, kteří byli přítomni na všech cvičeních.

<details>
<summary></summary>

Adéla Svobodová, Přemysl Němec, Petra Fialová, Jakub Sedláček, Barbora Krejčová, Dominik Šimek, Nikola Urbanová, Radek Holub, Alena Bartošová, Patrik Soukup

<details>
<summary></summary>

```r
students[rowSums(attendance) == ncol(attendance)]
```

*Alternativa:*

```r
students[rowMeans(attendance) == 1]
```

</details>
</details>

In [188]:
students[rowSums(attendance) == ncol(attendance)]

 [1] "Adéla Svobodová"  "Přemysl Němec"    "Petra Fialová"    "Jakub Sedláček"
 [5] "Barbora Krejčová" "Dominik Šimek"    "Nikola Urbanová"  "Radek Holub"
 [9] "Alena Bartošová"  "Patrik Soukup"

<div class="alert alert-block alert-success">

Jaká byla průměrná účast na jednotlivých cvičeních?

<details>
<summary></summary>

0.9, 0.95, 0.925, 0.925, 0.925, 0.875, 0.9, 0.9, 0.85, 0.9, 0.825, 0.875, 0.925

<details>
<summary></summary>

```r
colMeans(attendance)
```

</details>
</details>

In [189]:
colMeans(attendance)

 Week1  Week2  Week3  Week4  Week5  Week6  Week7  Week8  Week9 Week10 Week11
 0.900  0.950  0.925  0.925  0.925  0.875  0.900  0.900  0.850  0.900  0.825
Week12 Week13
 0.875  0.925

<div class="alert alert-block alert-success">

Vypište jména studentů, kteří chyběli více než dvakrát.

<details>
<summary></summary>

Karel Černý, Martin Hájek, Veronika Navrátilová, Anna Mareková, Michal Novotný, Vojtěch Malý

<details>
<summary></summary>

```r
students[rowSums(!attendance) > 2]
```

</details>
</details>

In [190]:
students[rowSums(attendance) < (ncol(attendance) - 2)]

[1] "Karel Černý"          "Martin Hájek"         "Veronika Navrátilová"
[4] "Anna Mareková"        "Michal Novotný"       "Vojtěch Malý"

<div class="alert alert-block alert-success">

Kolik studentů získalo alespoň 8 bodů a zároveň byli přítomni na všech cvičeních?

<details>
<summary></summary>

6

<details>
<summary></summary>

```r
sum(points >= 8 & rowSums(attendance) == ncol(attendance))
```

</details>
</details>

In [191]:
sum(points >= 8 & rowSums(attendance) == ncol(attendance))

[1] 6

<div class="alert alert-block alert-success">

Vytvořte matici **summary_matrix** se dvěma řádky: první řádek budou body, druhý řádek počet navštívených cvičení.

<details>
<summary></summary>

```r
summary_matrix = rbind(points, rowSums(attendance))
```

</details>

In [192]:
summary_matrix <- rbind(points, rowSums(attendance))
summary_matrix

       Jan Novák Adéla Svobodová Mojmír Dvořák Karel Černý Ladislav Procházka
points  8        10               6             9           7
       12        13              11            10          12
       Marek Kučera Adéla Veselá Karolína Horáková Přemysl Němec Tomáš Pospíšil
points  5           10            8                 6             9
       12           12           12                13            11
       ⋯ Kateřina Zemanová Adam Kolář Eliška Kopecká Josef Vaněk Hana Čermáková
points ⋯  6                 9         10              8           7
       ⋯ 11                12         12             12          12
       Radek Holub Alena Bartošová Patrik Soukup Lenka Dušková Marek Horák
points  5           8               9            10             6
       13          13              13            12            11

<div class="alert alert-block alert-success">

Kolik studentů získalo přesně 10 bodů a zároveň navštívilo alespoň 10 cvičení?

<details>
<summary></summary>

6

<details>
<summary></summary>

```r
sum(points == 10 & rowSums(attendance) >= 10)
```

</details>
</details>

In [193]:
sum(points == 10 & rowSums(attendance) >= 10)

[1] 6

## Faktory

In [194]:
movie_ratings = c("G", "G", "PG", "G", "PG-13", "PG-13", "R", "G", "R", "R", "PG-13", "G", "G", "R", "PG")

<div class="alert alert-block alert-success">
    
Zjistěte datový typ proměnné **movie_ratings**.

<details>
<summary></summary>

```r
typeof(movie_ratings)

class(movie_ratings)

str(movie_ratings)
```

</details>

In [195]:
typeof(movie_ratings)

[1] "character"

<div class="alert alert-block alert-success">
    
Vytvořte z proměnné faktor pomocí funkce `factor().` Nové proměnné přidejte nový název, původní proměnnou zachovejte.

<details>
<summary></summary>

```r
movie_ratings_factor <- factor(movie_ratings)
```

</details>

In [196]:
movie_ratings_factor <- factor(movie_ratings)

<div class="alert alert-block alert-success">
    
Zobrazte atributy obou proměnných pomocí funkce `attributes()`.

<details>
<summary></summary>

```r
attributes(movie_ratings)

attributes(movie_ratings_factor)
```

</details>

In [197]:
attributes(movie_ratings)
attributes(movie_ratings_factor)

NULL

$levels
[1] "G"     "PG"    "PG-13" "R"

$class
[1] "factor"

<div class="alert alert-block alert-success">
    
Atributy proměnné **movie_ratings_factor** se dají zobrazit přímým použitím funkcí `levels()` a `class()`. Vyzkoušejte obě funkce na proměnné **movie_ratings_factor** i **movie_ratings**.

<details>
<summary></summary>

```r
class(movie_ratings_factor)

levels(movie_ratings_factor)
```

</details>

In [198]:
levels(movie_ratings)
levels(movie_ratings_factor)

class(movie_ratings)
class(movie_ratings_factor)

NULL

[1] "G"     "PG"    "PG-13" "R"

[1] "character"

[1] "factor"

<div class="alert alert-block alert-success">
    
Funkce `levels()` zobrazí veškeré kategorie faktoru. Podobný výsledek dává i funkce `unique()`. Vyzkoušejte obě funkce. Je nějaký rozdíl ve výstupu?

<details>
<summary></summary>

```r
levels(movie_ratings_factor)

unique(movie_ratings_factor)

class(levels(movie_ratings_factor))

class(unique(movie_ratings_factor))

typeof(levels(movie_ratings_factor))

typeof(unique(movie_ratings_factor))
```

</details>

In [199]:
unique(movie_ratings_factor)

[1] G     PG    PG-13 R
Levels: G PG PG-13 R

<div class="alert alert-block alert-success">
    
Ve filmových kategoriích chybí film s ratingem NC-17. I když záznam o takovém filmu ve vektoru **movie_ratings** (resp. **movie_ratings_factor**) zatím nemáme, vložme kategorii do levels.

<details>
<summary></summary>

```r
levels(movie_ratings_factor) <- c(levels(movie_ratings_factor), "NC-17")
```

</details>

In [200]:
levels(movie_ratings_factor)[5] <- "NC-17"

<div class="alert alert-block alert-success">
    
Zkontrolujte, zda přiřazení levels proběhlo v pořádku opětovným použitím funkce `levels()` a `unique()`.

<details>
<summary></summary>

```r
levels(movie_ratings_factor)

unique(movie_ratings_factor)
```

</details>

In [201]:
levels(movie_ratings_factor)
unique(movie_ratings_factor)

[1] "G"     "PG"    "PG-13" "R"     "NC-17"

[1] G     PG    PG-13 R
Levels: G PG PG-13 R NC-17

<div class="alert alert-block alert-success">
    
Pomocí vhodného logického operátoru zjistěte, které filmy (na kterých pozicích), jsou vhodné pro všechny diváky (G - general audiences).

<details>
<summary></summary>

```r
movie_ratings == "G"

movie_ratings_factor == "G"

which(movie_ratings == "G")

which(movie_ratings_factor == "G")
```

</details>

In [202]:
which(movie_ratings_factor == "G")
movie_ratings_factor == "G"

[1]  1  2  4  8 12 13

 [1]  TRUE  TRUE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE
[13]  TRUE FALSE FALSE

<div class="alert alert-block alert-success">
    
Vyzkoušejte logický operátor > (větší než) namísto == (rovná se).

<details>
<summary></summary>

```r
movie_ratings > "G"
movie_ratings_factor > "G"
```

</details>

In [203]:
which(movie_ratings_factor > "G")
movie_ratings_factor > "G"

Warning message in Ops.factor(movie_ratings_factor, "G"):
"'>' not meaningful for factors"

integer(0)

Warning message in Ops.factor(movie_ratings_factor, "G"):
"'>' not meaningful for factors"

 [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA

<div class="alert alert-block alert-warning">
    
Jak se výsledek chová?

<details>
<summary></summary>
Operátory >, <, apod. nejsou validní faktory, jelikož faktory neuznávají uspořádání elementů jak alfabetické, tak numerické.

Porovnávání textového vektoru s > "G" indikuje, které elementy jsou abecedně seřazeny až po "G".
</details>

In [204]:
#nedava smysl

<div class="alert alert-block alert-success">
    
Seřaďte vektory **movie_ratings** a **movie_ratings_factor** abecedně pomocí funkce `sort()`.

<details>
<summary></summary>

```r
sort(movie_ratings)
sort(movie_ratings_factor)
```

</details>

In [205]:
sort(movie_ratings_factor)
sort(movie_ratings_factor)

 [1] G     G     G     G     G     G     PG    PG    PG-13 PG-13 PG-13 R
[13] R     R     R
Levels: G PG PG-13 R NC-17

 [1] G     G     G     G     G     G     PG    PG    PG-13 PG-13 PG-13 R
[13] R     R     R
Levels: G PG PG-13 R NC-17

<div class="alert alert-block alert-success">
    
Použite na oba vektory funkci `order()`. Jaký je její výstup?

<details>
<summary></summary>

```r
order(movie_ratings)
order(movie_ratings_factor)
```

</details>

In [206]:
order(movie_ratings)
order(movie_ratings_factor)

 [1]  1  2  4  8 12 13  3 15  5  6 11  7  9 10 14

 [1]  1  2  4  8 12 13  3 15  5  6 11  7  9 10 14

<div class="alert alert-block alert-success">
    
Použite výstup funkce `order()` pro seřazení vektorů. Nepoužívejte funkci `sort()`.

<details>
<summary></summary>

```r
movie_ratings[order(movie_ratings)]
movie_ratings_factor[order(movie_ratings_factor)]
```

</details>

In [207]:
movie_ratings[order(movie_ratings)]
movie_ratings_factor[order(movie_ratings_factor)]

 [1] "G"     "G"     "G"     "G"     "G"     "G"     "PG"    "PG"    "PG-13"
[10] "PG-13" "PG-13" "R"     "R"     "R"     "R"

 [1] G     G     G     G     G     G     PG    PG    PG-13 PG-13 PG-13 R
[13] R     R     R
Levels: G PG PG-13 R NC-17

<div class="alert alert-block alert-success">
    
Na základě proměnné **movie_ratings_factor** vytvořte ordered factor funkcí `ordered()`.

<details>
<summary></summary>

```r
movie_ratings_ordered_factor <- ordered(movie_ratings_factor)
```

</details>

In [208]:
movie_ratings_ordered_factor <- ordered(movie_ratings_factor)
movie_ratings_ordered_factor

 [1] G     G     PG    G     PG-13 PG-13 R     G     R     R     PG-13 G
[13] G     R     PG
Levels: G < PG < PG-13 < R

<div class="alert alert-block alert-success">
    
Jaké jsou levels nové proměnné?

<details>
<summary></summary>

```r
levels(movie_ratings_ordered_factor)
```

</details>

In [209]:
levels(movie_ratings_ordered_factor)

[1] "G"     "PG"    "PG-13" "R"

<div class="alert alert-block alert-success">
    
Vytvořte ordered factor tak, aby byly zachovány všechny původní levels.

<details>
<summary></summary>

```r
movie_ratings_ordered_factor <- ordered(movie_ratings_factor, levels = levels(movie_ratings_factor))
```

</details>

In [211]:
movie_ratings_ordered_factor <- ordered(movie_ratings_factor, levels = levels(movie_ratings_factor))

<div class="alert alert-block alert-success">
    
Nyní zkuste znovu najít takové elementy vektoru **movie_ratings_ordered_factor**, které jsou větší než "G".

<details>
<summary></summary>

```r
movie_ratings_ordered_factor > "G"
```

</details>

In [213]:
movie_ratings_ordered_factor > "G"
which(movie_ratings_ordered_factor > "G")

 [1] FALSE FALSE  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE
[13] FALSE  TRUE  TRUE

[1]  3  5  6  7  9 10 11 14 15

<div class="alert alert-block alert-success">
    
Zkontrolujte, zda je vektor seřazený.

<details>
<summary></summary>

```r
class(movie_ratings_ordered_factor)

str(movie_ratings_ordered_factor)

attributes(movie_ratings_ordered_factor)
```

</details>

In [214]:
attributes(movie_ratings_ordered_factor)

$levels
[1] "G"     "PG"    "PG-13" "R"     "NC-17"

$class
[1] "ordered" "factor"

<div class="alert alert-block alert-success">

# Shrnutí

Tvorba matice: `matrix()`, `cbind()`, `rbind()`, `runif()`

Rozměry matice: `dim()`, `nrow()`, `ncol()`, `length()`

Názvy řádků a sloupců: `rownames()`, `colnames()`

Transpozice matice: `t()`

Součty a průměry po řádcích a sloupcích: `rowSums()`, `colSums()`, `rowMeans()`, `colMeans()`

Faktory: `levels()`, `attributes()`

Manipulace s vektory: `order()`, `sort()`, `which()`, `which.min()`, `which.max()`, `intersect()`, `union()`, `setdiff()`, `table()`, `prop.table()`

Indexování:

```r
x[řádek, sloupec]
x[řádky, ]
x[, sloupce]

# Příklady k procvičení

<div class="alert alert-block alert-success">

Ze studentů, kteří chyběli alespoň na dvou cvičeních, najděte studenta nebo studenty s nejvyšším počtem bodů.

<details>
<summary></summary>

Anna Mareková, Vojtěch Malý

</details>

</div>

In [234]:
names(points) <- students
students_two <- students[rowSums(attendance) <= (ncol(attendance) - 2)]
students_two[which(points[students_two] == max(points[students_two]))]

[1] "Anna Mareková" "Vojtěch Malý"

<div class="alert alert-block alert-success">

Zjistěte, které cvičení navštívilo nejméně studentů a kolik studentů na něm bylo přítomno.

<details>
<summary></summary>

seminář 11, 33 studentů

</details>

</div>

In [236]:
which.min(colSums(attendance))
min(colSums(attendance))

Week11
    11

[1] 33

<div class="alert alert-block alert-success">

Kolik studentů získalo **nadprůměrný počet bodů** a zároveň navštívili **nadprůměrný počet cvičení**?

<details>
<summary></summary>

16

</details>

</div>

In [ ]:
sum(points > mean(points) & rowSums(attendance) > mean(rowSums(attendance)))

[1] 7.8

[1] 16

<div class="alert alert-block alert-success">

Pro získání zápočtu musí student získat **alespoň 8 bodů** a zároveň absolvovat **alespoň 10 cvičení**. Mezi studenty, kteří podmínky pro zápočet splnili, najděte toho nebo ty, kteří získali **nejmenší počet bodů**.

<details>
<summary></summary>

Jan Novák, Karolína Horáková, Lucie Jelínková, Jakub Sedláček, Michal Novotný, Jan Novák, Monika Křížová, Josef Vaněk, Alena Bartošová

</details>

</div>

In [249]:
students_ok <- students[points >= 8 & rowSums(attendance) >= (ncol(attendance) - 3)]
students_ok[points[students_ok] == min(points[students_ok])]

[1] "Jan Novák"         "Karolína Horáková" "Lucie Jelínková"
[4] "Jakub Sedláček"    "Michal Novotný"    "Jan Novák"
[7] "Monika Křížová"    "Josef Vaněk"       "Alena Bartošová"

# Bonus

<div class="alert alert-block alert-success">

Studenti během semestru absolvovali 10 cvičných testů. Každý test mohli psát dvakrát a do hodnocení se jim započítává **lepší pokus**.

Za každý test získá student podle svého lepšího pokusu:

* méně než 50 bodů → **0 bodů**,
* 50 až 75 bodů včetně → **0,5 bodu**,
* 76 až 100 bodů → **1 bod**.

**Zjistěte, kolik bonusových bodů získal každý student celkem.**

</div>

In [ ]:
set.seed(2)
practice_tests <- matrix(
    sample(0:100, size = 26 * 20, replace = TRUE),
    nrow = 26,
    ncol = 20
)

rownames(practice_tests) <- paste("student", 1:26)
colnames(practice_tests) <- paste(
    rep(paste("test", 1:10), each = 2),
    "attempt",
    1:2
)

head(practice_tests, 3)

          test 1 attempt 1 test 1 attempt 2 test 2 attempt 1 test 2 attempt 2
student 1 84               39               36               37
student 2 78               15               97                8
student 3 69               44               20               52
          test 3 attempt 1 test 3 attempt 2 test 4 attempt 1 test 4 attempt 2
student 1 87                2               50               46
student 2 56               37               71               95
student 3 92                0               25               34
          test 5 attempt 1 test 5 attempt 2 test 6 attempt 1 test 6 attempt 2
student 1 15               12               47               84
student 2  5               55               11               24
student 3 87               25               60                0
          test 7 attempt 1 test 7 attempt 2 test 8 attempt 1 test 8 attempt 2
student 1 30               43               57               81
student 2 36               75               85               51
student 3 18               34               45               54
          test 9 attempt 1 test 9 attempt 2 test 10 attempt 1 test 10 attempt 2
student 1 52               31               53                49
student 2 34               95               34                79
student 3 44               68               24                 7

In [263]:
first_attempts <- practice_tests[, seq(from = 1, to = 20, by = 2)]
second_attempts <- practice_tests[, seq(from = 2, to = 20, by = 2)]

better_attempts <- first_attempts
better_attempts[second_attempts > first_attempts] <- second_attempts[second_attempts > first_attempts] 

better_attempt[best < 50] <- 0
better_attempt[best >= 50 & best <= 75] <- 0.5
better_attempt[best > 75] <- 1
better_attempt

bonus_total <- rowSums(better_attempt)
print(bonus_total)

           [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
student 1  1.0  0.0  1.0  0.5  0.0  1.0  0.0  1.0  0.5  0.5
student 2  1.0  1.0  0.5  1.0  0.5  0.0  0.5  1.0  1.0  1.0
student 3  0.5  0.5  1.0  0.0  1.0  0.5  0.0  0.5  0.5  0.0
student 4  1.0  1.0  0.0  0.5  0.5  1.0  0.5  0.5  0.0  1.0
student 5  0.0  0.5  1.0  1.0  1.0  0.5  0.5  0.5  1.0  1.0
student 6  1.0  0.5  0.5  0.5  0.5  0.5  1.0  1.0  0.5  0.5
student 7  0.0  0.5  0.5  1.0  0.5  1.0  0.5  1.0  0.5  1.0
student 8  1.0  1.0  1.0  0.0  0.0  1.0  0.0  1.0  1.0  1.0
student 9  1.0  0.0  0.5  1.0  1.0  1.0  0.5  1.0  0.0  1.0
student 10 0.5  0.5  1.0  1.0  0.5  0.5  1.0  0.0  0.0  0.5
student 11 1.0  0.5  1.0  0.5  0.5  1.0  0.5  0.5  1.0  1.0
student 12 0.0  1.0  1.0  1.0  0.5  0.5  0.0  1.0  0.5  1.0
student 13 1.0  1.0  0.5  1.0  0.5  0.0  0.5  1.0  1.0  1.0
student 14 0.5  1.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  1.0
student 15 0.0  0.5  0.5  0.0  1.0  1.0  0.0  0.5  0.5  1.0
student 16 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.5
student 17 1.0  0.5  1.0  0.5  0.5  0.5  1.0  1.0  1.0  1.0
student 18 0.0  0.5  1.0  1.0  1.0  0.0  0.5  0.5  0.5  1.0
student 19 0.5  0.0  1.0  1.0  1.0  1.0  0.5  0.5  0.0  1.0
student 20 0.5  1.0  1.0  1.0  1.0  0.0  0.5  0.5  1.0  0.5
student 21 1.0  0.5  1.0  1.0  0.5  1.0  0.0  0.5  0.5  0.0
student 22 0.0  0.5  0.0  0.5  0.5  1.0  0.5  0.0  0.5  0.5
student 23 0.5  1.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0
student 24 1.0  1.0  1.0  1.0  0.0  0.0  0.5  0.5  1.0  0.5
student 25 0.0  1.0  0.5  0.0  1.0  1.0  1.0  0.0  0.5  1.0
student 26 1.0  1.0  0.0  0.0  0.5  1.0  0.5  1.0  0.0  0.5

 student 1  student 2  student 3  student 4  student 5  student 6  student 7
       5.5        7.5        4.5        6.0        7.0        6.5        6.5
 student 8  student 9 student 10 student 11 student 12 student 13 student 14
       7.0        7.0        5.5        7.5        6.5        7.5        5.5
student 15 student 16 student 17 student 18 student 19 student 20 student 21
       5.0        9.5        8.0        6.0        6.5        7.0        6.0
student 22 student 23 student 24 student 25 student 26
       4.0        4.5        6.5        6.0        5.5