# Cvičení 3

## Pole

<div class="alert alert-block alert-success">

Data **fitness**, se kterými budeme dnes pracovat, obsahují výsledky fyzických testů 12 armádních kandidátů. Dimenze datového pole jsou následující:

1. číslo kandidáta (1-6)
2. disciplína (kliky, sedy-lehy, běh)
3. pohlaví

Pole **limits** obsahuje bodové hranice pro hodnocení fyzických testů. Struktura je:

1. počet bodů (1-5)
2. disciplína (kliky, sedy-lehy, běh)
3. pohlaví

In [88]:
fitness <- array(
    c(
        # MEN - push-ups
        58, 44, 35, 50, 28, 62,
        # MEN - sit-ups
        52, 46, 39, 41, 35, 55,
        # MEN - 2 km run in minutes
        8.6, 9.4, 10.2, 9.0, 11.1, 8.3,
        # WOMEN - push-ups
        42, 31, 37, 25, 46, 34,
        # WOMEN - sit-ups
        50, 45, 48, 36, 54, 44,
        # WOMEN - 2 km run in minutes
        9.2, 10.0, 9.6, 10.8, 8.9, 9.7
    ),
    dim = c(6, 3, 2),
    dimnames = list(
        candidate = paste0("candidate_", 1:6),
        discipline = c("push_ups", "sit_ups", "run_2km"),
        group = c("men", "women")
    )
)
print(fitness)

, , group = men

             discipline
candidate     push_ups sit_ups run_2km
  candidate_1       58      52     8.6
  candidate_2       44      46     9.4
  candidate_3       35      39    10.2
  candidate_4       50      41     9.0
  candidate_5       28      35    11.1
  candidate_6       62      55     8.3

, , group = women

             discipline
candidate     push_ups sit_ups run_2km
  candidate_1       42      50     9.2
  candidate_2       31      45    10.0
  candidate_3       37      48     9.6
  candidate_4       25      36    10.8
  candidate_5       46      54     8.9
  candidate_6       34      44     9.7

In [89]:
limits <- array(c(
        # MEN - push-ups
        25, 32, 40, 48, 55,
        # MEN - sit-ups
        30, 36, 42, 48, 54,
        # MEN - run
        12, 11, 10, 9, 8.5,
        # WOMEN - push-ups
        15, 22, 28, 35, 42,
        # WOMEN - sit-ups
        28, 34, 40, 46, 52,
        # WOMEN - run
        12.5, 11.5, 10.5, 9.5, 9
    ),
    dim = c(5, 3, 2),
    dimnames = list(
        points = 1:5,
        discipline = c("push_ups", "sit_ups", "run_2km"),
        group = c("men", "women")
    )
)
print(limits)

, , group = men

      discipline
points push_ups sit_ups run_2km
     1       25      30    12.0
     2       32      36    11.0
     3       40      42    10.0
     4       48      48     9.0
     5       55      54     8.5

, , group = women

      discipline
points push_ups sit_ups run_2km
     1       15      28    12.5
     2       22      34    11.5
     3       28      40    10.5
     4       35      46     9.5
     5       42      52     9.0

<div class="alert alert-block alert-success">

Jaké jsou dimenze pole **fitness**?

<details>
<summary></summary>

6, 3, 2

<details>
<summary></summary>

```r
dim(fitness)
```

</details>
</details>

In [90]:
dim(fitness)

[1] 6 3 2

<div class="alert alert-block alert-success">

Vypište všechny výsledky mužů.

<details>
<summary></summary>

 - | push_ups	| sit_ups	| run_2km
--- | --- | --- | ---
candidate_1	|58	|52|	8.6
candidate_2|	44|	46	|9.4
candidate_3	|35	|39|	10.2
candidate_4|	50|	41	|9.0
candidate_5|	28|	35	|11.1
candidate_6	|62	|55|	8.3

<details>
<summary></summary>

```r
fitness[, , "men"]
```

Kód `fitness[, , 1]` nepoužíváme, jelikož číslo 1 čtenáři nevysvětlí, jaká data byla vybrána.

</details>
</details>

In [91]:
fitness[, , "men"]

             discipline
candidate     push_ups sit_ups run_2km
  candidate_1 58       52       8.6
  candidate_2 44       46       9.4
  candidate_3 35       39      10.2
  candidate_4 50       41       9.0
  candidate_5 28       35      11.1
  candidate_6 62       55       8.3

<div class="alert alert-block alert-success">

Vypište počet kliků všech kandidátek.

<details>
<summary></summary>

candidate_1: 42

candidate_2: 31

candidate_3: 37

candidate_4: 25

candidate_5: 46

candidate_6: 34

<details>
<summary></summary>

```r
fitness[, "push_ups", "women"]
```

</details>
</details>

In [92]:
fitness[, "push_ups", "women"]

candidate_1 candidate_2 candidate_3 candidate_4 candidate_5 candidate_6
         42          31          37          25          46          34

<div class="alert alert-block alert-success">

Vypište výsledky třetího kandidáta (muže).

<details>
<summary></summary>

push_ups: 35

sit_ups: 39

run_2km: 10.2

<details>
<summary></summary>

```r
fitness["candidate_3", , "men"]
```

</details>
</details>

In [93]:
fitness["candidate_3", , "men"]

push_ups  sit_ups  run_2km
    35.0     39.0     10.2

<div class="alert alert-block alert-success">

Za kolik minut musí kandidátka uběhnout 2 km aby získala 4 body? Výsledek najdete v poli **limits**.

<details>
<summary></summary>

9.5 minut

<details>
<summary></summary>

```r
limits[4, "run_2km", "women"]
```

</details>
</details>

In [94]:
limits["4", "run_2km", "women"]

[1] 9.5

<div class="alert alert-block alert-success">

Kolik kliků musí kandidát zvládnout, aby získal 4 body?

<details>
<summary></summary>

48

<details>
<summary></summary>

```r
limits[4, "push_ups", "men"]
```

</details>
</details>

In [95]:
limits["4", "push_ups", "men"]

[1] 48

<div class="alert alert-block alert-success">

Kolik kliků musí kandidát zvládnout, aby získal 1, 3 a 5 bodů?

<details>
<summary></summary>

1 bod: 25

3 body: 40

5 bodů: 55

<details>
<summary></summary>

```r
limits[
    c(1, 3, 5),
    "push_ups",
    "men"
]
```

</details>
</details>

In [96]:
limits[c(1, 3, 5), "push_ups", "men"]

 1  3  5
25 40 55

<div class="alert alert-block alert-success">

Jaký byl nejlepší výsledek mužů v každé disciplíně?

<details>
<summary></summary>

push ups: 62

sit ups: 55

run 2 km: 8.3

<details>
<summary></summary>

```r
max(fitness[, "push_ups", "men"])

max(fitness[, "sit_ups", "men"])

min(fitness[, "run_2km", "men"])
```

</details>
</details>

In [97]:
max(fitness[ , "push_ups", "men"])
max(fitness[ , "sit_ups", "men"])
min(fitness[ , "run_2km", "men"])

[1] 62

[1] 55

[1] 8.3

<div class="alert alert-block alert-success">

Který kandidát získal nejlepší výsledek v každé disciplíně?

<details>
<summary></summary>

kandidát 6 ve všech třech disciplínách

<details>
<summary></summary>

```r
male_pushups <- fitness[, "push_ups", "men"]
male_pushups[male_pushups == max(male_pushups)]

male_situps <- fitness[, "sit_ups", "men"]
male_situps[male_situps == max(male_situps)]

male_run2km <- fitness[, "run_2km", "men"]
male_run2km[male_run2km == min(male_run2km)]
```

</details>
</details>

In [98]:
which.max(fitness[ , "push_ups", "men"])
which.max(fitness[ , "sit_ups", "men"])
which.min(fitness[ , "run_2km", "men"])

candidate_6
          6

candidate_6
          6

candidate_6
          6

<div class="alert alert-block alert-success">

Jaký je průměrný čas běhu na 2 km pro kandidáty a kandidátky? 

<details>
<summary></summary>

kandidáti: 9.43

kandidátky: 9.7

<details>
<summary></summary>

```r
mean(fitness[, "run_2km", "men"])

mean(fitness[, "run_2km", "women"])
```

</details>
</details>

In [99]:
mean(fitness[ , "run_2km", "men"])
mean(fitness[ , "run_2km", "women"])

[1] 9.433333

[1] 9.7

<div class="alert alert-block alert-success">

Kolik bodů získají kandidáti za kliky?

<details>
<summary></summary>

candidate_1: 5

candidate_2: 3

candidate_3: 2

candidate_4: 4

candidate_5: 1

candidate_6: 5

<details>
<summary></summary>

```r
male_pushups <- fitness[, "push_ups", "men"]

male_pushup_points <-
    (male_pushups >= limits[1, "push_ups", "men"]) +
    (male_pushups >= limits[2, "push_ups", "men"]) +
    (male_pushups >= limits[3, "push_ups", "men"]) +
    (male_pushups >= limits[4, "push_ups", "men"]) +
    (male_pushups >= limits[5, "push_ups", "men"])

male_pushup_points
```

</details>
</details>

In [100]:
male_push_ups <- fitness[, "push_ups", "men"]

male_push_ups_points <- ((male_push_ups >= limits[1, "push_ups", "men"]) 
    + (male_push_ups >= limits[2, "push_ups", "men"])
    + (male_push_ups >= limits[3, "push_ups", "men"])
    + (male_push_ups >= limits[4, "push_ups", "men"])
    + (male_push_ups >= limits[5, "push_ups", "men"]))

male_push_ups_points

candidate_1 candidate_2 candidate_3 candidate_4 candidate_5 candidate_6
          5           3           2           4           1           5

<div class="alert alert-block alert-success">

Kolik bodů získají kandidáti za běh na 2km?

<details>
<summary></summary>

candidate_1: 4

candidate_2: 3

candidate_3: 2

candidate_4: 4

candidate_5: 1

candidate_6: 5

<details>
<summary></summary>

```r
male_run <- fitness[, "run_2km", "men"]

male_run_points <-
    (male_run <= limits[1, "run_2km", "men"]) +
    (male_run <= limits[2, "run_2km", "men"]) +
    (male_run <= limits[3, "run_2km", "men"]) +
    (male_run <= limits[4, "run_2km", "men"]) +
    (male_run <= limits[5, "run_2km", "men"])

male_run_points
```

</details>
</details>

In [101]:
male_run_2km <- fitness[, "run_2km", "men"]

male_run_2km_points <- ((male_run_2km <= limits[1, "run_2km", "men"]) 
    + (male_run_2km <= limits[2, "run_2km", "men"])
    + (male_run_2km <= limits[3, "run_2km", "men"])
    + (male_run_2km <= limits[4, "run_2km", "men"])
    + (male_run_2km <= limits[5, "run_2km", "men"]))

male_run_2km_points

candidate_1 candidate_2 candidate_3 candidate_4 candidate_5 candidate_6
          4           3           2           4           1           5

<div class="alert alert-block alert-success">

Vytvořte pole **points** pro počet bodů. Použijte argumenty `dim` a `dimnames`.

<details>
<summary></summary>

```r
points <- array(
    0,
    dim = dim(fitness),
    dimnames = dimnames(fitness)
)
```

</details>

In [102]:
points <- array(0, dim = dim(fitness), dimnames = dimnames(fitness))
print(points)

, , group = men

             discipline
candidate     push_ups sit_ups run_2km
  candidate_1        0       0       0
  candidate_2        0       0       0
  candidate_3        0       0       0
  candidate_4        0       0       0
  candidate_5        0       0       0
  candidate_6        0       0       0

, , group = women

             discipline
candidate     push_ups sit_ups run_2km
  candidate_1        0       0       0
  candidate_2        0       0       0
  candidate_3        0       0       0
  candidate_4        0       0       0
  candidate_5        0       0       0
  candidate_6        0       0       0

<div class="alert alert-block alert-success">

Do pole **points** vložte data pro kandidáty.

<details>
<summary></summary>

```r
points[, "push_ups", "men"] <- male_pushup_points
points[, "run_2km", "men"] <- male_run_points

male_situps <- fitness[, "sit_ups", "men"]

points[, "sit_ups", "men"] <- (male_situps >= limits[1, "sit_ups", "men"]) +
    (male_situps >= limits[2, "sit_ups", "men"]) +
    (male_situps >= limits[3, "sit_ups", "men"]) +
    (male_situps >= limits[4, "sit_ups", "men"]) +
    (male_situps >= limits[5, "sit_ups", "men"])
```

</details>

In [103]:
points[ , "push_ups", "men"] <- male_push_ups_points
points[ , "run_2km", "men"] <- male_run_2km_points

male_sit_ups <- fitness[, "sit_ups", "men"]

male_sit_ups_points <- ((male_sit_ups >= limits[1, "sit_ups", "men"]) 
    + (male_sit_ups >= limits[2, "sit_ups", "men"])
    + (male_sit_ups >= limits[3, "sit_ups", "men"])
    + (male_sit_ups >= limits[4, "sit_ups", "men"])
    + (male_sit_ups >= limits[5, "sit_ups", "men"]))

points[ , "sit_ups", "men"] <- male_sit_ups_points

print(points)

, , group = men

             discipline
candidate     push_ups sit_ups run_2km
  candidate_1        5       4       4
  candidate_2        3       3       3
  candidate_3        2       2       2
  candidate_4        4       2       4
  candidate_5        1       1       1
  candidate_6        5       5       5

, , group = women

             discipline
candidate     push_ups sit_ups run_2km
  candidate_1        0       0       0
  candidate_2        0       0       0
  candidate_3        0       0       0
  candidate_4        0       0       0
  candidate_5        0       0       0
  candidate_6        0       0       0

<div class="alert alert-block alert-success">

Do pole **points** vložte data pro kandidátky:

```r
matrix(
    c(5, 4, 4, 3, 3, 3, 4, 4, 3, 2, 2, 2, 5, 5, 5, 3, 3, 3), 
    ncol = 3,
    byrow = TRUE
)
```

<details>
<summary></summary>

```r
points[, , "women"] <- matrix(
    c(5, 4, 4, 3, 3, 3, 4, 4, 3, 2, 2, 2, 5, 5, 5, 3, 3, 3), 
    ncol = 3,
    byrow = TRUE
)
```

</details>

In [104]:
points[ , , "women"] <- matrix(c(5,4,4,3,3,3,4,4,3,2,2,2,5,5,5,3,3,3), ncol = 3, byrow = TRUE)
print(points)

, , group = men

             discipline
candidate     push_ups sit_ups run_2km
  candidate_1        5       4       4
  candidate_2        3       3       3
  candidate_3        2       2       2
  candidate_4        4       2       4
  candidate_5        1       1       1
  candidate_6        5       5       5

, , group = women

             discipline
candidate     push_ups sit_ups run_2km
  candidate_1        5       4       4
  candidate_2        3       3       3
  candidate_3        4       4       3
  candidate_4        2       2       2
  candidate_5        5       5       5
  candidate_6        3       3       3

<div class="alert alert-block alert-success">

Jakých celkových skóre (tj. suma napříč všemi disciplínami) dosáhly kandidátky?

<details>
<summary></summary>

candidate_1: 13
candidate_2: 9
candidate_3: 11
candidate_4: 6
candidate_5: 15
candidate_6: 9

<details>
<summary></summary>

```r
rowSums(points[, , "women"])
```

</details>
</details>

In [105]:
rowSums(points[, , "women"])

candidate_1 candidate_2 candidate_3 candidate_4 candidate_5 candidate_6
         13           9          11           6          15           9

<div class="alert alert-block alert-success">

Kolik kandidátů a kandidátek prošlo testem? Hranice pro absolvování je získání alespoň 9 bodů.

<details>
<summary></summary>

kandidátky: 1, 2, 3, 5, 6

kandidáti: 1, 2, 4, 6

<details>
<summary></summary>

```r
which(rowSums(points[, , "women"]) >= 9)

which(rowSums(points[, , "men"]) >= 9)
```

</details>
</details>

In [106]:
sum(rowSums(points[, , "women"]) >= 9)
sum(rowSums(points[, , "men"]) >= 9)

which(rowSums(points[, , "women"]) >= 9)
which(rowSums(points[, , "men"]) >= 9)

[1] 5

[1] 4

candidate_1 candidate_2 candidate_3 candidate_5 candidate_6
          1           2           3           5           6

candidate_1 candidate_2 candidate_4 candidate_6
          1           2           4           6

<div class="alert alert-block alert-success">

Jaké procento kandidátů a kandidátek prošlo testem?

<details>
<summary></summary>

kandidátky: 83 %

kandidáti: 67 %

<details>
<summary></summary>

```r
mean(rowSums(points[, , "women"]) >= 9) * 100

mean(rowSums(points[, , "men"]) >= 9) * 100
```

</details>
</details>

In [107]:
sum(rowSums(points[, , "women"]) >= 9) / 6
sum(rowSums(points[, , "men"]) >= 9) / 6

[1] 0.8333333

[1] 0.6666667

<div class="alert alert-block alert-success">

Která disciplína měla nejnižší průměrný počet bodů?

<details>
<summary></summary>

sit_ups

<details>
<summary></summary>

```r
mean(points[, "push_ups", ])

mean(points[, "sit_ups", ])

mean(points[, "run_2km", ])
```

</details>
</details>

In [108]:
which.min(rowSums(colSums(points) / 6))

sit_ups
      2

<div class="alert alert-block alert-success">

Kteří kandidáti nebo kandidátky dosáhli excelentních výsledků (5 bodů) v alespoň jedné disciplíně?

<details>
<summary></summary>

kandidáti: 1, 6

kandidátky: 1, 5

<details>
<summary></summary>

```r
which(rowSums(points[, , "men"] == 5) > 0)

which(rowSums(points[, , "women"] == 5) > 0)
```

</details>
</details>

In [109]:
which(rowSums(points[, , "men"] == 5) >= 1)
which(rowSums(points[, , "women"] == 5) >= 1)

candidate_1 candidate_6
          1           6

candidate_1 candidate_5
          1           5

## Datové tabulky

In [110]:
student_data <- read.csv("american_student_data.csv")

<div class="alert alert-block alert-success">

Tabulku prozkoumejte. Zjistěte dimenze, strukturu a vypište si několik řádků.

<details>
<summary></summary>

```r
dim(student_data)

nrow(student_data)

ncol(student_data)

str(student_data)

head(student_data)

tail(student_data)

summary(student_data)
```

</details>

In [111]:
dim(student_data)
str(student_data)
summary(student_data)
head(student_data)
tail(student_data)

[1] 178  13

'data.frame':	178 obs. of  13 variables:
 $ name           : chr  "Sophia" "Olivia" "Sarah" "Sophia" ...
 $ surname        : chr  "Smith" "Miller" "Jones" "Miller" ...
 $ city           : chr  "Houston" "San Jose" "Houston" "Los Angeles" ...
 $ gender         : chr  "Female" "Female" "Non-binary" "Male" ...
 $ height         : num  194 158 173 158 176 ...
 $ is_smoker      : chr  "True" "True" "False" "False" ...
 $ is_student     : chr  "False" "True" "False" "False" ...
 $ study_programme: chr  "History" "Medicine" "Medicine" "Business" ...
 $ is_working     : chr  "True" "True" "False" "False" ...
 $ favourite_game : chr  "League of Legends" "Fortnite" "League of Legends" "GTA V" ...
 $ wakes_up       : chr  "early" "early" "early" "late" ...
 $ gpa_average    : num  3.69 2.43 3.52 3.37 3.32 2.47 3.66 3.07 2.07 3.45 ...
 $ sport          : chr  "" "Tennis" "Basketball" "Swimming" ...

        name          surname           city           gender
 Length   :178   Length   :178   Length   :178   Length   :178
 N.unique : 10   N.unique : 10   N.unique : 10   N.unique :  3
 N.blank  :  0   N.blank  :  0   N.blank  :  0   N.blank  :  0
 Min.nchar:  4   Min.nchar:  5   Min.nchar:  6   Min.nchar:  4
 Max.nchar:  7   Max.nchar:  9   Max.nchar: 12   Max.nchar: 10

     height          is_smoker       is_student   study_programme
 Min.   :150.1   Length   :178   Length   :178   Length   :178
 1st Qu.:162.4   N.unique :  2   N.unique :  2   N.unique :  8
 Median :171.2   N.blank  :  0   N.blank  :  0   N.blank  :  0
 Mean   :174.2   Min.nchar:  4   Min.nchar:  4   Min.nchar:  3
 3rd Qu.:187.5   Max.nchar:  5   Max.nchar:  5   Max.nchar: 11
 Max.   :199.9
     is_working    favourite_game      wakes_up    gpa_average
 Length   :178   Length   :178    Length   :178   Min.   :2.000
 N.unique :  2   N.unique :  8    N.unique :  2   1st Qu.:2.612
 N.blank  :  0   N.blank  :  0    N.blank  :  0   Median :3.065
 Min.nchar:  4   Min.nchar:  5    Min.nchar:  4   Mean   :3.052
 Max.nchar:  5   Max.nchar: 17    Max.nchar:  5   3rd Qu.:3.530
                                                  Max.   :4.000
       sport
 Length   :178
 N.unique :  8
 N.blank  : 20
 Min.nchar:  0
 Max.nchar: 10

  name    surname city         gender     height is_smoker is_student
1 Sophia  Smith   Houston      Female     194.1  True      False
2 Olivia  Miller  San Jose     Female     157.9  True      True
3 Sarah   Jones   Houston      Non-binary 173.4  False     False
4 Sophia  Miller  Los Angeles  Male       157.9  False     False
5 John    Brown   Chicago      Non-binary 175.6  False     False
6 Jessica Smith   Philadelphia Non-binary 161.9  False     True
  study_programme is_working favourite_game    wakes_up gpa_average sport
1 History         True       League of Legends early    3.69
2 Medicine        True       Fortnite          early    2.43        Tennis
3 Medicine        False      League of Legends early    3.52        Basketball
4 Business        False      GTA V             late     3.37        Swimming
5 Art             False      Among Us          early    3.32        Tennis
6 Science         True       Among Us          early    2.47        Tennis

    name    surname  city        gender     height is_smoker is_student
173 Sarah   Martinez New York    Non-binary 187.5  False     True
174 John    Davis    San Diego   Non-binary 158.6  True      False
175 Jessica Garcia   Houston     Female     178.6  True      True
176 Jessica Miller   Los Angeles Male       151.8  True      True
177 James   Johnson  Houston     Non-binary 199.2  False     False
178 Sarah   Smith    Los Angeles Male       154.6  False     False
    study_programme is_working favourite_game    wakes_up gpa_average
173 Business        False      Among Us          early    3.22
174 Science         True       League of Legends late     2.88
175 Science         True       Call of Duty      early    2.28
176 History         False      Among Us          late     3.71
177 Science         True       Fortnite          early    2.70
178 Medicine        True       Call of Duty      early    2.91
    sport
173 Swimming
174 Yoga
175 Basketball
176 Baseball
177 Baseball
178

<div class="alert alert-block alert-success">

Vypište výšku všech osob. Indexovat datové tabulky můžete stejně jako matice, nebo pomocí $.

`data_frame[row_indexes, column_indexes]`

`data_frame$column_name`

<details>
<summary></summary>

```r
student_data$height
```

*Alternativa:*

```r
student_data[, "height"]
```

</details>

In [112]:
student_data$height

  [1] 194.1 157.9 173.4 157.9 175.6 161.9 191.8 186.1 184.9 164.1 169.2 192.9
 [13] 172.6 188.0 199.2 158.3 179.2 199.1 188.9 174.4 154.7 150.7 158.0 183.6
 [25] 152.5 158.6 174.4 169.9 162.6 192.8 182.4 174.5 169.5 166.0 185.6 194.0
 [37] 167.5 197.0 192.8 182.6 153.1 189.0 187.3 151.7 199.5 190.5 150.1 197.8
 [49] 182.9 195.8 171.3 186.9 168.0 169.9 170.6 189.5 162.7 195.6 177.7 151.4
 [61] 197.7 190.8 177.1 194.0 182.2 167.0 194.5 158.1 162.4 154.0 168.7 182.5
 [73] 198.8 160.7 189.8 171.2 198.1 163.2 194.7 165.2 163.0 158.4 168.8 167.2
 [85] 175.7 186.9 163.6 157.3 199.4 181.1 167.4 170.9 171.6 163.8 199.4 187.8
 [97] 188.5 163.0 157.9 157.7 184.4 192.9 170.3 160.3 193.7 162.4 180.1 190.1
[109] 153.8 161.9 161.0 155.4 162.4 167.1 154.5 190.9 174.7 159.4 164.1 153.3
[121] 186.2 157.3 190.2 165.6 197.1 184.3 166.1 152.3 187.5 178.7 155.0 178.2
[133] 166.2 163.2 199.9 163.9 160.9 198.6 175.1 189.2 162.1 166.5 185.7 174.2
[145] 176.4 168.7 173.8 178.2 156.9 193.4 192.3 165.6 151.2 164.8 167.9 162.3
[157] 196.8 184.6 182.8 170.8 157.3 164.7 156.1 171.8 180.6 168.9 151.2 162.6
[169] 159.0 155.8 171.2 188.0 187.5 158.6 178.6 151.8 199.2 154.6

<div class="alert alert-block alert-success">

Vypište zárověň sloupce s jménem, příjmením a městem. Můžete využít funkce `select()`.

<details>
<summary></summary>

```r
subset(student_data, select = c("name", "surname", "city"))
```

*Alternativa:*

```r
student_data[, c("name", "surname", "city")]
```

</details>

In [113]:
student_data[, c("name", "surname", "city")]
subset(student_data, select = c("name", "surname", "city"))

    name    surname   city
1   Sophia  Smith     Houston
2   Olivia  Miller    San Jose
3   Sarah   Jones     Houston
4   Sophia  Miller    Los Angeles
5   John    Brown     Chicago
6   Jessica Smith     Philadelphia
7   Jessica Williams  San Diego
8   Emily   Davis     San Diego
9   Sophia  Garcia    San Jose
10  Michael Brown     New York
11  David   Davis     Phoenix
12  Sarah   Williams  San Antonio
13  Sarah   Davis     Philadelphia
14  John    Smith     Los Angeles
15  Sarah   Smith     San Antonio
16  John    Davis     Dallas
17  David   Martinez  San Antonio
18  John    Brown     San Diego
19  Sarah   Brown     San Diego
20  Sarah   Jones     San Antonio
21  Olivia  Brown     Philadelphia
22  Michael Martinez  Phoenix
23  James   Jones     Houston
24  Emily   Williams  Philadelphia
25  Olivia  Jones     Los Angeles
26  Olivia  Miller    Chicago
27  David   Rodriguez New York
28  Olivia  Miller    Chicago
29  Sarah   Smith     San Antonio
30  David   Brown     Los Angeles
⋮   ⋮       ⋮         ⋮
149 Sophia  Jones     Houston
150 Sophia  Brown     Phoenix
151 Michael Miller    Chicago
152 James   Garcia    Chicago
153 Sarah   Davis     Philadelphia
154 Robert  Garcia    New York
155 Jessica Garcia    San Diego
156 Sophia  Brown     San Jose
157 John    Williams  Phoenix
158 Michael Garcia    Houston
159 Michael Davis     San Jose
160 Michael Garcia    Dallas
161 Michael Williams  Houston
162 Emily   Williams  New York
163 John    Miller    San Antonio
164 Robert  Garcia    New York
165 Sophia  Smith     San Diego
166 James   Rodriguez Houston
167 John    Rodriguez San Jose
168 Olivia  Martinez  Dallas
169 Jessica Williams  San Diego
170 David   Brown     Dallas
171 David   Davis     San Antonio
172 James   Jones     Chicago
173 Sarah   Martinez  New York
174 John    Davis     San Diego
175 Jessica Garcia    Houston
176 Jessica Miller    Los Angeles
177 James   Johnson   Houston
178 Sarah   Smith     Los Angeles

    name    surname   city
1   Sophia  Smith     Houston
2   Olivia  Miller    San Jose
3   Sarah   Jones     Houston
4   Sophia  Miller    Los Angeles
5   John    Brown     Chicago
6   Jessica Smith     Philadelphia
7   Jessica Williams  San Diego
8   Emily   Davis     San Diego
9   Sophia  Garcia    San Jose
10  Michael Brown     New York
11  David   Davis     Phoenix
12  Sarah   Williams  San Antonio
13  Sarah   Davis     Philadelphia
14  John    Smith     Los Angeles
15  Sarah   Smith     San Antonio
16  John    Davis     Dallas
17  David   Martinez  San Antonio
18  John    Brown     San Diego
19  Sarah   Brown     San Diego
20  Sarah   Jones     San Antonio
21  Olivia  Brown     Philadelphia
22  Michael Martinez  Phoenix
23  James   Jones     Houston
24  Emily   Williams  Philadelphia
25  Olivia  Jones     Los Angeles
26  Olivia  Miller    Chicago
27  David   Rodriguez New York
28  Olivia  Miller    Chicago
29  Sarah   Smith     San Antonio
30  David   Brown     Los Angeles
⋮   ⋮       ⋮         ⋮
149 Sophia  Jones     Houston
150 Sophia  Brown     Phoenix
151 Michael Miller    Chicago
152 James   Garcia    Chicago
153 Sarah   Davis     Philadelphia
154 Robert  Garcia    New York
155 Jessica Garcia    San Diego
156 Sophia  Brown     San Jose
157 John    Williams  Phoenix
158 Michael Garcia    Houston
159 Michael Davis     San Jose
160 Michael Garcia    Dallas
161 Michael Williams  Houston
162 Emily   Williams  New York
163 John    Miller    San Antonio
164 Robert  Garcia    New York
165 Sophia  Smith     San Diego
166 James   Rodriguez Houston
167 John    Rodriguez San Jose
168 Olivia  Martinez  Dallas
169 Jessica Williams  San Diego
170 David   Brown     Dallas
171 David   Davis     San Antonio
172 James   Jones     Chicago
173 Sarah   Martinez  New York
174 John    Davis     San Diego
175 Jessica Garcia    Houston
176 Jessica Miller    Los Angeles
177 James   Johnson   Houston
178 Sarah   Smith     Los Angeles

<div class="alert alert-block alert-success">

Změňte kódování sloupce pohlaví na **M** pro muže, **F** pro ženy, a **O** nebinární.

<details>
<summary></summary>

```r
student_data$gender <- factor(student_data$gender)
levels(student_data$gender) 
levels(student_data$gender) = c("F", "M", "O")
```

</details>

In [114]:

student_data$gender <- factor(student_data$gender)
levels(student_data$gender) = c("F", "M", "O")
student_data$gender

  [1] F F O M O O O F M O F O F M M O F M M M O O O F M O O O O O M O O O M F F
 [38] M O M M M M M F F F M F O F F O O O F F F M M F F O F F O F O F F M O O O
 [75] M O F M F M O F O F O F F F O O M M M F O F M O O O M O M M F F O F F O F
[112] M O M F M M F O O O O F F O F F M O F F O O M M F O M O F F F O M F M M F
[149] O O F O M O F M F M F M O O M F M M M F O M F M O O F M O M
Levels: F M O

<div class="alert alert-block alert-success">

Vypište všechny údaje o studentech s jménem **Sarah**.

<details>
<summary></summary>

```r
student_data[student_data$name == "Sarah", ]
```

</details>

In [115]:
student_data[student_data$name == "Sarah", ]

    name  surname   city         gender height is_smoker is_student
3   Sarah Jones     Houston      O      173.4  False     False
12  Sarah Williams  San Antonio  O      192.9  False     False
13  Sarah Davis     Philadelphia F      172.6  False     False
15  Sarah Smith     San Antonio  M      199.2  False     False
19  Sarah Brown     San Diego    M      188.9  False     True
20  Sarah Jones     San Antonio  M      174.4  False     True
29  Sarah Smith     San Antonio  O      162.6  True      False
57  Sarah Garcia    Dallas       F      162.7  False     False
60  Sarah Smith     Phoenix      M      151.4  False     False
64  Sarah Johnson   Houston      F      194.0  True      False
69  Sarah Davis     Houston      F      162.4  True      False
75  Sarah Rodriguez Los Angeles  M      189.8  False     True
95  Sarah Johnson   Philadelphia O      199.4  True      False
97  Sarah Davis     Phoenix      M      188.5  False     True
111 Sarah Johnson   San Jose     F      161.0  True      True
130 Sarah Rodriguez Philadelphia F      178.7  True      True
132 Sarah Davis     Los Angeles  O      178.2  True      True
140 Sarah Miller    New York     F      189.2  False     False
141 Sarah Brown     Chicago      F      162.1  False     False
146 Sarah Davis     Philadelphia M      168.7  False     False
153 Sarah Davis     Philadelphia M      151.2  True      True
173 Sarah Martinez  New York     O      187.5  False     True
178 Sarah Smith     Los Angeles  M      154.6  False     False
    study_programme is_working favourite_game    wakes_up gpa_average
3   Medicine        False      League of Legends early    3.52
12  Psychology      False      League of Legends early    2.92
13  Law             True       Minecraft         late     2.35
15  Business        True       Roblox            late     2.23
19  Art             False      The Sims          early    3.78
20  Psychology      False      Call of Duty      late     3.43
29  Art             True       Minecraft         early    3.59
57  History         True       Roblox            early    2.61
60  Art             False      Fortnite          late     2.87
64  Art             True       GTA V             late     3.39
69  Law             False      GTA V             late     3.02
75  Business        False      GTA V             early    2.65
95  Law             True       League of Legends early    2.68
97  Art             True       The Sims          late     3.76
111 Medicine        False      Among Us          late     2.13
130 Art             False      Among Us          early    2.27
132 Engineering     True       The Sims          late     3.88
140 History         False      Call of Duty      late     2.54
141 Art             False      League of Legends early    2.72
146 History         False      League of Legends early    3.08
153 Engineering     True       Minecraft         early    3.06
173 Business        False      Among Us          early    3.22
178 Medicine        True       Call of Duty      early    2.91
    sport
3   Basketball
12  Tennis
13  Tennis
15  Swimming
19  Baseball
20
29  Tennis
57  Soccer
60
64  Running
69  Yoga
75  Soccer
95  Soccer
97  Yoga
111 Baseball
130
132
140 Swimming
141 Running
146 Baseball
153
173 Swimming
178

<div class="alert alert-block alert-success">

Kolik z nich je žen?

<details>
<summary></summary>

8

<details>
<summary></summary>

```r
student_data[student_data$name == "Sarah" & student_data$gender == "F", ] |> nrow()
```

</details>
</details>

In [116]:
nrow(student_data[student_data$gender == "F" & student_data$name == "Sarah", ])

[1] 8

<div class="alert alert-block alert-success">

Jaké je jejich průměrné GPA?

<details>
<summary></summary>

2.62875

<details>
<summary></summary>

```r
student_data[student_data$name == "Sarah" & student_data$gender == "F", "gpa_average"] |> mean()
```

</details>
</details>

In [117]:
mean(student_data[student_data$gender == "F" & student_data$name == "Sarah", "gpa_average"])

[1] 2.62875

<div class="alert alert-block alert-success">

Která osoba je nejvyšší a která nejnižší? Vypište jejich jméno a příjmení.

<details>
<summary></summary>

Robert Jones, Sophia Rodriguez

<details>
<summary></summary>

```r
student_data[student_data$height == min(student_data$height), c("name", "surname")]
student_data[student_data$height == max(student_data$height), c("name", "surname")]
```

</details>
</details>

In [118]:
student_data[student_data$height == max(student_data$height), c("name", "surname")]
student_data[student_data$height == min(student_data$height), c("name", "surname")]

    name   surname
135 Sophia Rodriguez

   name   surname
47 Robert Jones

<div class="alert alert-block alert-success">

Vypište GPA všech studentů medicíny a práva spolu s jejich bydlištěm.

<details>
<summary></summary>

```r
subset(
    x = student_data,
    subset = study_programme %in%  c("Medicine", "Law"),
    select = c(gpa_average, city)
)
```

</details>

In [119]:
subset(x = student_data, subset = study_programme %in% c("Medicine", "Law"), select = c(gpa_average, city))
student_data[student_data$study_programme %in% c("Medicine", "Law"), c("gpa_average", "city")]

    gpa_average city
2   2.43        San Jose
3   3.52        Houston
13  2.35        Philadelphia
17  2.02        San Antonio
21  2.19        Philadelphia
22  3.85        Phoenix
28  2.61        Chicago
30  3.93        Los Angeles
32  2.72        Chicago
35  3.55        New York
46  2.61        Houston
47  2.49        Phoenix
48  3.81        Houston
54  2.73        San Diego
63  3.72        New York
69  3.02        Houston
70  3.56        San Jose
74  2.10        Philadelphia
83  2.76        Phoenix
86  2.35        San Antonio
87  3.74        Chicago
90  2.81        San Jose
95  2.68        Philadelphia
96  3.93        Phoenix
100 3.12        Los Angeles
104 2.77        Dallas
105 3.06        Philadelphia
109 2.26        Los Angeles
110 3.18        San Antonio
111 2.13        San Jose
128 3.36        Houston
134 3.12        Dallas
139 3.53        Houston
142 3.88        New York
143 2.92        Houston
144 3.00        New York
148 2.05        San Diego
151 2.33        Chicago
152 3.33        Chicago
154 2.27        New York
159 3.32        San Jose
162 3.29        New York
163 3.90        San Antonio
168 2.47        Dallas
171 3.18        San Antonio
178 2.91        Los Angeles

    gpa_average city
2   2.43        San Jose
3   3.52        Houston
13  2.35        Philadelphia
17  2.02        San Antonio
21  2.19        Philadelphia
22  3.85        Phoenix
28  2.61        Chicago
30  3.93        Los Angeles
32  2.72        Chicago
35  3.55        New York
46  2.61        Houston
47  2.49        Phoenix
48  3.81        Houston
54  2.73        San Diego
63  3.72        New York
69  3.02        Houston
70  3.56        San Jose
74  2.10        Philadelphia
83  2.76        Phoenix
86  2.35        San Antonio
87  3.74        Chicago
90  2.81        San Jose
95  2.68        Philadelphia
96  3.93        Phoenix
100 3.12        Los Angeles
104 2.77        Dallas
105 3.06        Philadelphia
109 2.26        Los Angeles
110 3.18        San Antonio
111 2.13        San Jose
128 3.36        Houston
134 3.12        Dallas
139 3.53        Houston
142 3.88        New York
143 2.92        Houston
144 3.00        New York
148 2.05        San Diego
151 2.33        Chicago
152 3.33        Chicago
154 2.27        New York
159 3.32        San Jose
162 3.29        New York
163 3.90        San Antonio
168 2.47        Dallas
171 3.18        San Antonio
178 2.91        Los Angeles

<div class="alert alert-block alert-success">

Vytvořte nový vektor **scholarship**. Vektor bude obsahovat honoty **awarded** pro studenty s GPA větším nebo rovném 3.5 a **not** pro ostatní. Vektor poté přidejte do tabulky jako nový sloupec. Použijte funkci `ifelse()`. Její použití nastudujte v nápovědě.

`?ifelse`

`help(ifelse)`

<details>
<summary></summary>

```r
student_data$scholarship <- ifelse(
    student_data$gpa_average >= 3.5,
    yes = "awarded", 
    no = "not"
)
```

</details>

In [120]:
student_data$scholarship <- ifelse(student_data$gpa_average >= 3.5, yes = "awarded", no = "not")
student_data

    name    surname   city         gender height is_smoker is_student
1   Sophia  Smith     Houston      F      194.1  True      False
2   Olivia  Miller    San Jose     F      157.9  True      True
3   Sarah   Jones     Houston      O      173.4  False     False
4   Sophia  Miller    Los Angeles  M      157.9  False     False
5   John    Brown     Chicago      O      175.6  False     False
6   Jessica Smith     Philadelphia O      161.9  False     True
7   Jessica Williams  San Diego    O      191.8  False     False
8   Emily   Davis     San Diego    F      186.1  True      False
9   Sophia  Garcia    San Jose     M      184.9  False     False
10  Michael Brown     New York     O      164.1  True      True
11  David   Davis     Phoenix      F      169.2  True      False
12  Sarah   Williams  San Antonio  O      192.9  False     False
13  Sarah   Davis     Philadelphia F      172.6  False     False
14  John    Smith     Los Angeles  M      188.0  True      True
15  Sarah   Smith     San Antonio  M      199.2  False     False
16  John    Davis     Dallas       O      158.3  False     False
17  David   Martinez  San Antonio  F      179.2  False     False
18  John    Brown     San Diego    M      199.1  True      True
19  Sarah   Brown     San Diego    M      188.9  False     True
20  Sarah   Jones     San Antonio  M      174.4  False     True
21  Olivia  Brown     Philadelphia O      154.7  False     False
22  Michael Martinez  Phoenix      O      150.7  False     False
23  James   Jones     Houston      O      158.0  True      True
24  Emily   Williams  Philadelphia F      183.6  True      True
25  Olivia  Jones     Los Angeles  M      152.5  True      True
26  Olivia  Miller    Chicago      O      158.6  True      True
27  David   Rodriguez New York     O      174.4  False     True
28  Olivia  Miller    Chicago      O      169.9  False     False
29  Sarah   Smith     San Antonio  O      162.6  True      False
30  David   Brown     Los Angeles  O      192.8  True      True
⋮   ⋮       ⋮         ⋮            ⋮      ⋮      ⋮         ⋮
149 Sophia  Jones     Houston      O      156.9  False     False
150 Sophia  Brown     Phoenix      O      193.4  True      False
151 Michael Miller    Chicago      F      192.3  True      True
152 James   Garcia    Chicago      O      165.6  False     False
153 Sarah   Davis     Philadelphia M      151.2  True      True
154 Robert  Garcia    New York     O      164.8  False     False
155 Jessica Garcia    San Diego    F      167.9  True      False
156 Sophia  Brown     San Jose     M      162.3  False     True
157 John    Williams  Phoenix      F      196.8  True      True
158 Michael Garcia    Houston      M      184.6  False     True
159 Michael Davis     San Jose     F      182.8  False     True
160 Michael Garcia    Dallas       M      170.8  True      True
161 Michael Williams  Houston      O      157.3  True      False
162 Emily   Williams  New York     O      164.7  False     False
163 John    Miller    San Antonio  M      156.1  True      True
164 Robert  Garcia    New York     F      171.8  False     False
165 Sophia  Smith     San Diego    M      180.6  False     True
166 James   Rodriguez Houston      M      168.9  True      True
167 John    Rodriguez San Jose     M      151.2  False     True
168 Olivia  Martinez  Dallas       F      162.6  True      True
169 Jessica Williams  San Diego    O      159.0  False     True
170 David   Brown     Dallas       M      155.8  False     True
171 David   Davis     San Antonio  F      171.2  True      True
172 James   Jones     Chicago      M      188.0  True      False
173 Sarah   Martinez  New York     O      187.5  False     True
174 John    Davis     San Diego    O      158.6  True      False
175 Jessica Garcia    Houston      F      178.6  True      True
176 Jessica Miller    Los Angeles  M      151.8  True      True
177 James   Johnson   Houston      O      199.2  False     False
178 Sarah   Smith     Los Angeles  M      154.6  False     False
    study_programme is_working favourite_game    wakes_up gpa_average
1   History         True       League of Legends early    3.69
2   Medicine        True       Fortnite          early    2.43
3   Medicine        False      League of Legends early    3.52
4   Business        False      GTA V             late     3.37
5   Art             False      Among Us          early    3.32
6   Science         True       Among Us          early    2.47
7   Psychology      True       Call of Duty      early    3.66
8   Science         True       Roblox            early    3.07
9   Business        True       League of Legends late     2.07
10  Psychology      True       Fortnite          early    3.45
11  Business        True       Roblox            late     3.12
12  Psychology      False      League of Legends early    2.92
13  Law             True       Minecraft         late     2.35
14  Science         False      League of Legends early    2.80
15  Business        True       Roblox            late     2.23
16  History         True       GTA V             late     4.00
17  Law             False      Among Us          late     2.02
18  Psychology      False      GTA V             late     3.25
19  Art             False      The Sims          early    3.78
20  Psychology      False      Call of Duty      late     3.43
21  Law             False      Among Us          early    2.19
22  Law             True       Fortnite          late     3.85
23  History         True       Fortnite          early    3.61
24  Engineering     True       Among Us          late     3.62
25  Art             True       Call of Duty      early    3.36
26  Engineering     True       Roblox            late     2.86
27  Art             True       The Sims          early    2.61
28  Medicine        False      GTA V             late     2.61
29  Art             True       Minecraft         early    3.59
30  Law             True       Minecraft         early    3.93
⋮   ⋮               ⋮          ⋮                 ⋮        ⋮
149 Psychology      False      League of Legends late     3.75
150 Science         True       League of Legends late     3.00
151 Medicine        True       Fortnite          late     2.33
152 Law             True       GTA V             early    3.33
153 Engineering     True       Minecraft         early    3.06
154 Medicine        True       The Sims          late     2.27
155 Science         True       League of Legends early    2.87
156 Business        False      Roblox            late     2.25
157 Science         True       Minecraft         late     3.51
158 History         True       The Sims          late     3.06
159 Medicine        False      GTA V             early    3.32
160 Art             True       League of Legends late     3.51
161 Psychology      True       Call of Duty      late     2.91
162 Medicine        True       Minecraft         late     3.29
163 Law             False      League of Legends early    3.90
164 Science         True       Minecraft         late     3.08
165 Business        False      The Sims          late     2.48
166 Business        True       Fortnite          late     2.47
167 Art             False      Minecraft         early    2.39
168 Law             False      Fortnite          early    2.47
169 Psychology      True       GTA V             late     2.62
170 History         True       Fortnite          late     3.03
171 Law             False      GTA V             late     3.18
172 Science         False      Roblox            early    3.53
173 Business        False      Among Us          early    3.22
174 Science         True       League of Legends late     2.88
175 Science         True       Call of Duty      early    2.28
176 History         False      Among Us          late     3.71
177 Science         True       Fortnite          early    2.70
178 Medicine        True       Call of Duty      early    2.91
    sport      scholarship
1              awarded
2   Tennis     not
3   Basketball awarded
4   Swimming   not
5   Tennis     not
6   Tennis     not
7   Running    awarded
8   Basketball not
9   Baseball   not
10  Soccer     not
11  Swimming   not
12  Tennis     not
13  Tennis     not
14  Running    not
15  Swimming   not
16  Baseball   awarded
17  Yoga       not
18  Soccer     not
19  Baseball   awarded
20             not
21  Soccer     not
22  Baseball   awarded
23  Basketball awarded
24  Baseball   awarded
25  Yoga       not
26  Soccer     not
27  Baseball   not
28  Soccer     not
29  Tennis     awarded
30             awarded
⋮   ⋮          ⋮
149 Soccer     awarded
150 Baseball   not
151 Tennis     not
152 Tennis     not
153            not
154 Running    not
155 Running    not
156 Swimming   not
157 Baseball   awarded
158 Yoga       not
159 Baseball   not
160 Soccer     awarded
161 Running    not
162 Soccer     not
163            awarded
164 Tennis     not
165 Running    not
166 Baseball   not
167 Soccer     not
168 Yoga       not
169 Running    not
170            not
171 Tennis     not
172 Tennis     awarded
173 Swimming   not
174 Yoga       not
175 Basketball not
176 Baseball   awarded
177 Baseball   not
178            not

<div class="alert alert-block alert-success">

Sloupec **city** přejmenujte na **home_city**. Použijte funkci `names()`.

<details>
<summary></summary>

```r
names(student_data)[names(student_data) == "city"] <- "home_city"
```

</details>

In [121]:
names(student_data)[names(student_data) == "city"] <- "home_city"

<div class="alert alert-block alert-success">

Vypište tabulku seřazenou nejdříve dle pohlaví a poté dle jména. Použijte funkci `order()`.

<details>
<summary></summary>

```r
student_data[order(student_data$gender, student_data$name), ]
```

</details>

In [122]:
student_data[order(student_data$gender, student_data$name), ]

    name    surname   home_city    gender height is_smoker is_student
11  David   Davis     Phoenix      F      169.2  True      False
17  David   Martinez  San Antonio  F      179.2  False     False
94  David   Brown     Dallas       F      163.8  False     False
115 David   Garcia    New York     F      154.5  False     True
118 David   Garcia    Philadelphia F      159.4  True      True
148 David   Johnson   San Diego    F      178.2  False     False
171 David   Davis     San Antonio  F      171.2  True      True
8   Emily   Davis     San Diego    F      186.1  True      False
24  Emily   Williams  Philadelphia F      183.6  True      True
45  Emily   Martinez  Chicago      F      199.5  True      False
61  James   Johnson   San Antonio  F      197.7  True      True
124 James   Rodriguez Dallas       F      165.6  True      False
127 James   Davis     Houston      F      166.1  True      False
131 James   Brown     Philadelphia F      155.0  True      True
46  Jessica Jones     Houston      F      190.5  False     False
52  Jessica Jones     Chicago      F      186.9  True      True
77  Jessica Miller    Houston      F      198.1  True      False
88  Jessica Miller    New York     F      157.3  True      True
106 Jessica Williams  Phoenix      F      162.4  True      False
108 Jessica Brown     Phoenix      F      190.1  False     True
155 Jessica Garcia    San Diego    F      167.9  True      False
175 Jessica Garcia    Houston      F      178.6  True      True
51  John    Martinez  San Jose     F      171.3  False     False
65  John    Martinez  Houston      F      182.2  False     False
79  John    Williams  Philadelphia F      194.7  False     True
84  John    Miller    Houston      F      167.2  False     False
105 John    Williams  Philadelphia F      193.7  True      True
157 John    Williams  Phoenix      F      196.8  True      True
67  Michael Rodriguez Dallas       F      194.5  False     True
86  Michael Garcia    San Antonio  F      186.9  False     True
⋮   ⋮       ⋮         ⋮            ⋮      ⋮      ⋮         ⋮
125 Michael Smith     New York     O      197.1  False     True
139 Michael Miller    Houston      O      175.1  True      False
161 Michael Williams  Houston      O      157.3  True      False
21  Olivia  Brown     Philadelphia O      154.7  False     False
26  Olivia  Miller    Chicago      O      158.6  True      True
28  Olivia  Miller    Chicago      O      169.9  False     False
32  Olivia  Rodriguez Chicago      O      174.5  True      True
50  Olivia  Brown     Los Angeles  O      195.8  True      True
55  Olivia  Davis     Phoenix      O      170.6  False     False
68  Olivia  Jones     New York     O      158.1  True      True
90  Olivia  Miller    San Jose     O      181.1  False     False
99  Olivia  Rodriguez Phoenix      O      157.9  True      False
121 Olivia  Rodriguez Houston      O      186.2  False     True
129 Olivia  Brown     New York     O      187.5  False     True
66  Robert  Williams  Philadelphia O      167.0  True      True
113 Robert  Davis     Dallas       O      162.4  False     True
122 Robert  Johnson   Dallas       O      157.3  True      True
137 Robert  Rodriguez New York     O      160.9  False     False
154 Robert  Garcia    New York     O      164.8  False     False
3   Sarah   Jones     Houston      O      173.4  False     False
12  Sarah   Williams  San Antonio  O      192.9  False     False
29  Sarah   Smith     San Antonio  O      162.6  True      False
95  Sarah   Johnson   Philadelphia O      199.4  True      False
132 Sarah   Davis     Los Angeles  O      178.2  True      True
173 Sarah   Martinez  New York     O      187.5  False     True
53  Sophia  Johnson   Philadelphia O      168.0  False     True
63  Sophia  Brown     New York     O      177.1  False     True
110 Sophia  Rodriguez San Antonio  O      161.9  True      False
149 Sophia  Jones     Houston      O      156.9  False     False
150 Sophia  Brown     Phoenix      O      193.4  True      False
    study_programme is_working favourite_game    wakes_up gpa_average
11  Business        True       Roblox            late     3.12
17  Law             False      Among Us          late     2.02
94  Business        False      Call of Duty      late     3.77
115 History         False      Roblox            late     2.74
118 Art             False      The Sims          late     3.50
148 Law             False      Fortnite          early    2.05
171 Law             False      GTA V             late     3.18
8   Science         True       Roblox            early    3.07
24  Engineering     True       Among Us          late     3.62
45  Engineering     False      Among Us          early    3.33
61  History         False      Among Us          early    3.44
124 Business        False      Roblox            late     3.87
127 History         False      League of Legends late     3.26
131 History         True       Among Us          late     3.94
46  Law             False      Call of Duty      early    2.61
52  History         True       Minecraft         early    2.11
77  Engineering     True       Among Us          late     3.44
88  Engineering     True       Fortnite          early    2.82
106 Science         False      Call of Duty      early    3.35
108 Science         True       GTA V             early    2.63
155 Science         True       League of Legends early    2.87
175 Science         True       Call of Duty      early    2.28
51  History         False      Among Us          late     3.27
65  Science         True       Roblox            late     2.96
79  Psychology      False      The Sims          early    3.19
84  History         True       Call of Duty      late     2.68
105 Medicine        False      Among Us          early    3.06
157 Science         True       Minecraft         late     3.51
67  Psychology      False      Call of Duty      early    3.77
86  Law             True       Fortnite          late     2.35
⋮   ⋮               ⋮          ⋮                 ⋮        ⋮
125 Engineering     True       League of Legends late     3.75
139 Medicine        True       Roblox            early    3.53
161 Psychology      True       Call of Duty      late     2.91
21  Law             False      Among Us          early    2.19
26  Engineering     True       Roblox            late     2.86
28  Medicine        False      GTA V             late     2.61
32  Medicine        False      League of Legends early    2.72
50  Psychology      True       GTA V             late     2.90
55  Science         False      Roblox            late     3.63
68  Art             True       Minecraft         late     2.78
90  Medicine        False      Among Us          early    2.81
99  Science         False      League of Legends late     3.54
121 History         False      League of Legends early    3.95
129 Psychology      True       The Sims          late     3.61
66  Science         False      League of Legends early    3.79
113 Business        False      League of Legends early    2.18
122 Business        False      League of Legends early    3.08
137 Art             True       League of Legends early    3.67
154 Medicine        True       The Sims          late     2.27
3   Medicine        False      League of Legends early    3.52
12  Psychology      False      League of Legends early    2.92
29  Art             True       Minecraft         early    3.59
95  Law             True       League of Legends early    2.68
132 Engineering     True       The Sims          late     3.88
173 Business        False      Among Us          early    3.22
53  History         True       Among Us          late     3.12
63  Medicine        True       Roblox            early    3.72
110 Medicine        True       GTA V             late     3.18
149 Psychology      False      League of Legends late     3.75
150 Science         True       League of Legends late     3.00
    sport      scholarship
11  Swimming   not
17  Yoga       not
94             awarded
115 Running    not
118 Tennis     awarded
148 Running    not
171 Tennis     not
8   Basketball not
24  Baseball   awarded
45  Running    not
61  Baseball   not
124 Swimming   awarded
127 Basketball not
131 Yoga       awarded
46  Running    not
52  Baseball   not
77  Running    not
88  Running    not
106 Swimming   not
108 Yoga       not
155 Running    not
175 Basketball not
51  Yoga       not
65  Tennis     not
79  Baseball   not
84             not
105 Baseball   not
157 Baseball   awarded
67  Yoga       awarded
86  Yoga       not
⋮   ⋮          ⋮
125 Baseball   awarded
139 Baseball   awarded
161 Running    not
21  Soccer     not
26  Soccer     not
28  Soccer     not
32  Baseball   not
50  Running    not
55             awarded
68  Running    not
90  Baseball   not
99  Running    awarded
121 Running    awarded
129 Basketball awarded
66  Tennis     awarded
113 Running    not
122 Tennis     not
137 Running    awarded
154 Running    not
3   Basketball awarded
12  Tennis     not
29  Tennis     awarded
95  Soccer     not
132            awarded
173 Swimming   not
53  Swimming   not
63  Running    awarded
110 Yoga       not
149 Soccer     awarded
150 Baseball   not

<div class="alert alert-block alert-success">

Spočítejte průměrnou výšku dle **gender**. Můžete využít funkci `aggregate()`.

<details>
<summary></summary>

Female: 176.4213

Male: 173.5

Non-binary: 172.5641

<details>
<summary></summary>

```r
aggregate(height ~ gender, x = student_data, FUN = mean)
```

</details>
</details>

In [123]:
aggregate(height ~ gender, x = student_data, FUN = mean)

  gender height
1 F      176.4213
2 M      173.5000
3 O      172.5641

<div class="alert alert-block alert-success">

Vypočítejte průměrnou výšku mužů hrajících **League of Legends** a porovnejte ji s průměrnou výškou mužů hrajících **Call of Duty**.

<details>
<summary></summary>

LoL: 177

CoD: 168

<details>
<summary></summary>

```r
mean(student_data$height[
    student_data$favourite_game == "League of Legends" &
    student_data$gender == "M"
])

mean(student_data$height[
    student_data$favourite_game == "Call of Duty" &
    student_data$gender == "M"
])
```

</details>
</details>

In [124]:
mean(student_data$height[student_data$favourite_game == "League of Legends" & student_data$gender == "M"])
mean(student_data$height[student_data$favourite_game == "Call of Duty" & student_data$gender == "M"])

[1] 176.7333

[1] 167.95

<div class="alert alert-block alert-success">

Zobrazte frekvenční tabulku četností osob z různých měst.

<details>
<summary></summary>

Chicago: 15

Dallas: 19     

Houston: 27

Los Angeles: 17

New York : 21

Philadelphia: 21

Phoenix: 18

San Antonio: 14

San Diego: 14

San Jose: 12

<details>
<summary></summary>

```r
table(student_data$home_city)
```

</details>
</details>

In [125]:
table(student_data$home_city)

      Dallas      Houston      Chicago  Los Angeles     New York Philadelphia
          19           27           15           17           21           21
     Phoenix  San Antonio    San Diego     San Jose
          18           14           14           12

<div class="alert alert-block alert-success">

Spočítejte kolik studentů hraje jednotlivé hry, rozdělte četnosti i dle pohlaví.

<details>
<summary></summary>

| Game | Female | Male | Non-binary |
|---|---:|---:|---:|
| Among Us | 13 | 4 | 8 |
| Call of Duty | 10 | 8 | 3 |
| Fortnite | 7 | 3 | 6 |
| GTA V | 6 | 5 | 7 |
| League of Legends | 7 | 15 | 17 |
| Minecraft | 7 | 7 | 7 |
| Roblox | 9 | 4 | 6 |
| The Sims | 2 | 7 | 10|

<details>
<summary></summary>

```r
table(student_data$favourite_game, student_data$gender)
```

</details>
</details>

In [126]:
table(student_data$favourite_game, student_data$gender)

                     F  M  O
  Among Us          13  4  8
  Call of Duty      10  8  3
  Fortnite           7  3  6
  GTA V              6  5  7
  League of Legends  7 15 17
  Minecraft          7  7  7
  Roblox             9  4  6
  The Sims           2  7 10

# Příklady k procvičení

In [142]:
flights <- read.csv("flights.csv")
head(flights)
dim(flights)

  year month day_of_month day_of_week dep_time arr_time unique_carrier
1 2011 1     1            6           1400     1500     AA
2 2011 1     2            7           1401     1501     AA
3 2011 1     3            1           1352     1502     AA
4 2011 1     4            2           1403     1513     AA
5 2011 1     5            3           1405     1507     AA
6 2011 1     6            4           1359     1503     AA
  flight_num tail_num actual_elapsed_time air_time arr_delay dep_delay origin
1 428        N576AA   60                  40       -10        0        IAH
2 428        N557AA   60                  45        -9        1        IAH
3 428        N541AA   70                  48        -8       -8        IAH
4 428        N403AA   70                  39         3        3        IAH
5 428        N492AA   62                  44        -3        5        IAH
6 428        N262AA   64                  45        -7       -1        IAH
  dest distance taxi_in taxi_out
1 DFW  224      7       13
2 DFW  224      6        9
3 DFW  224      5       17
4 DFW  224      9       22
5 DFW  224      9        9
6 DFW  224      6       13

[1] 227496     18

<div class="alert alert-block alert-success">

Najděte nejdelší let v datech flights. Vypište jeho letiště odletu, cílové letiště a vzdálenost.

<details>
<summary></summary>

IAH → HNL, 3904 mil

</details>

In [143]:
#max(flights$air_time)
subset(flights, air_time == max(air_time, na.rm = TRUE), select = c("origin", "dest", "distance"))
#flights[flights$air_time == max(flights$air_time), c("origin", "dest", "distance")]
flights$air_time

      origin dest distance
23332 IAH    HNL  3904

    [1]  40  45  48  39  44  45  43  40  41  45  42  41  44  47  44  41  48  42
   [19]  46  42  47  44  40  43  40  40  40  46  46  39  39  41  43  46  46  44
   [37]  44  42  40  51  44  44  42  49  47  49  45  54  46  51  44  40  47  42
   [55]  42  40  44  44  44  43  44  40  44  48  42  44  41  44  44  43  44  39
   [73]  44  45  42  44  44  44  45  45  39  41  44  39  40  42  43  38  37  46
   [91]  47  43  43  43  43  45  50  41  41  44  45  47  48  42  51  45  46  41
  [109]  47  47  44  43  41  41  43  44  47  39  41 113 112 112 108 107 106 107
  [127] 107 110 107 111 117 110 110 111 113 117 114 110 111 110 109 107 113 129
  [145] 111 106 108 105 108 104  44  43  40  42  40  45  42  41  45  45  49  42
  [163]  45  42  50  42  38  44  46  44  44 117 112 111 109 108 105 107 106 110
  [181] 132 115 113 108 110 114 118 113 118 114 107 110 112 108  NA 112 110 108
  [199] 104 108 106 100  39  47  46  41  44  41  43  39  NA  43  42  41  46  49
  [217]  52  42  49  43  44  44  44  50  39  43  40  46  43  47  44  41  42  45
  [235]  43  41  41  44  47  45  44  46 113 115 111 115 111 107 108 105 111 111
  [253]  NA 112 109 112 114 112 143 112 124 110 114 118 110 111 111 112 112 111
  [271] 107 111 106 255 257 260 268 273 278 274 269 253 315  NA 284 273 270 287
  [289] 291 310 276 265 284 288 269 269 251 255 255 262 256 246 264 259 181 188
  [307] 172 176 166 165 168 175 167 166 175 172 175 162 163 196 166 170 161  NA
  [325] 177 178 185 189 173 166 176 168 173 162 164  NA 161 164 173 161 162 164
  [343] 156 156 162 167 165  NA 172 196 180 175 176 172 169 492  42  40  42  32
  [361] 199 201 116 165 163 175 162  49 199 114 189 142 225 107 172 128  91 256
  [379] 166 215 161 161 165  27 121 121 145 263 228 122  45 195 190 119 254 164
  [397] 159  44 143 177 146 229  39 188 182 109 194 146 143 170 138 231  41 143
  [415] 169  NA 117 117 149 276  43 190 187 127  NA 183  60 161 178 125 174 136
  [433] 116 143 202 236 188 102 179 124 131  90 139  44 154 166 116 128 195 249
  [451] 180 105 191  92 245  44 157 194 193  32 125 114 189  89  42 255 224 237
  [469] 155 105 132 198 133 168 158  89 161 106 107 149 231  40 100 127 201 192
  [487] 121  31 238 126  42 113 108 201  98 158  37 121 195 181 138  89 203  30
  [505]  30 128 114 106 101  87  32 103 189 106  29 207 163  58  42 198 161  55
  [523] 217 116 106  97 109 159  39 128 192 105 212  56  NA 235 120 194 202 117
  [541] 108  85 266 142  35 154  41 105 200 199  42 103 172 153 128 121 104 101
  [559] 140 228 493  43  38  43  32 203 201 120 171 164 171 167  40 185 119 188
  [577] 147 230 107 162 119  93 244 169 212 153 153 172  31 136 126 241 227 121
  [595]  39 175 119 239 161 152  43 144 127 139 233  36 190 179 103 190 135 144
  [613] 180 145 231  40 151 171  64 142 144 249  37 185 170 114 113 172  53 159
  [631] 163 143 155 135 127 146 232 198  99 178 118 118  93 145  42 169 131 144
  [649] 147 239 228 194 101 177 255  43 170 190 185  30 128 120 167  90 197  43
  [667] 247 231 229 107 138 204 121 175 150  93 171 126 111 145 224  39 100 128
  [685] 203 176 122  30 234 138  43 111 201 187  34 141 194 174  89 204  31 134
  [703] 125 109  30 106  96  31 101 195 107 151 198 153  55  42 218 172 220 115
  [721] 112  99 108 154  40 155 201 109 211  55  59 124 195 193  27 115 107  88
  [739] 237 156  34 138  38 109 203 200  44 105 173 167 127 123 108 108 137 228
  [757] 459  40  45  29 197 121 177 170 171 174 196 125 196 241 105 168 119  89
  [775] 249 180 210 149 151  34 130 124 156 242 237 123  43 203 164 120 240 159
  [793] 146  46 156 173 125 138 231  37 195 174 154  NA 146 233  40 136 171 111
  [811] 125 150 243  39 186 163 119 106 170  58 148 175 132 160 138 121 135 187
  [829] 217 177  98 166 117 118  88 139 153 172 130 147 139 237 182  97 172  95
  [847] 233  43 168 178 177  33 133 125 167  85  45 251 228 228  98 132 192 120
  [865] 164  88 170 115 230  37 101 138 188 165  29 234 131  41 113 109  96 162
  [883]  42 189  90  NA 135 118 107 103  89  32  97 186 106  33 194 139  57  48
  [901] 217 125  32 107 100 102  39 185 105 196  55  55 222 109 183  40 125 187
  [919] 123 107 242 154  41 137  46 104 190 189  45 103 164 123 102  99 138 222
  [937] 463  46  37  50  29 194 190 119 183 179 180 185 178 128 180  NA 230 109
  [955] 163 122  94 250 192 222 138 161 182  30 154 132 145 247 225 122  35 201
  [973] 163 115 251 174 138  47 153 177 152 212  35 202 168 119 174 153 161 174
  [991] 158 221  43 148 187  69 125 137 153 254  35 212 163 123 113 183  55 144
 [1009] 182 157 150 151 125  NA 224 204  98 164 115 120  93 142  45 154 192 142
 [1027] 147 137 250 220 201 102 161  92 245  51 192 167 169  28 148 126 160  90
 [1045] 175  45 260 252 225 164 103 156 181 118 170 143  97 182 127 110 142 217
 [1063]  38 105 154 181 158 125  30 220 150  42 114 113 178 102 172  42 146 178
 [1081] 162  90 179  30  27 152 140 112 151 104  96  28 107 177 113  30 184 143
 [1099]  54  52 177 206  53 219 131 115 105 101 167  33 145 174 107 180  56  62
 [1117] 217 105 172 175 135 110  95 254 171  34 130  43 112 183 187  46 109 179
 [1135] 195 152 137 111  99 141 209 455  45  38  46  29 180 184 118 158 167  NA
 [1153] 161  47 180 137 179 142 212 109 157 125  92 234 168 218 151 148 162  30
 [1171] 141 113  NA 253 214 126  35 188 163 126 244 180 150  45 144 163 129 141
 [1189] 208  36 182 158 111 174 148 141  NA 135 203  41 144 162  69 128 131 139
 [1207] 257  36 188 163 124 124 182  52 145 175 135 166 137 128 143 210 187 100
 [1225] 153 119 122  89 158  50 150 175 142 140 143 251 205 189 101 161  94 237
 [1243]  46 160 167 175  30 138 134 162  84 183  46 251 212 215 147  98 143 182
 [1261] 121 176 145  94 171 140 111 140 210  36  93 144 179 168 121  26 211 144
 [1279]  45 108 115 180 100 151  39 143 183 168 139  87 186  31  31 134 136 113
 [1297] 106 102  32  94 178 114  30 183 147  56  43 184 166  57 212 131 114  94
 [1315] 100 170  38 148 179 109 186  56  61 233 109 171 182 124 108  85 253 160
 [1333]  35 142  48 113 176 179  42 109 156 164 131 117 113  97 140 210 471  41
 [1351]  37  43  27 190 189 137  NA 161 184 176  47 194 128 196  NA 221 105 124
 [1369]  96 243  NA 239 153 165  27 132 127 140 118 185 123 259  NA 149  43 157
 [1387] 184 147 215  40 178 104 143 176 188  NA 216  42  NA 177  61 124 134 158
 [1405] 249  40 200 182 105 190  55 151 180 137 164 136 130  NA 198 214 185 102
 [1423] 173 124 122  92 140  49 159  NA 138  NA 143 262 223 188 180  93 246  NA
 [1441] 183 128 135 156  86  46 256 212 221 156 103 195 123 185 148  NA 117 112
 [1459]  NA 216  40 102 134 182 176 124  29 220 138  43 118 195  38 130 195 176
 [1477]  91 190  29  31 135 136 118  30 109  95  30  99 185 115  NA  56  44 188
 [1495]  NA 228 126 117  97 107 162  37 135 181 194  56  64 217 122 181 188 125
 [1513] 116  99 255  NA  37  41 114 186 201 110  NA 160 127 124 105 102 153 217
 [1531] 473  44  41  46  32 192 125 165 158 164 163  44 194 124 182 136 224 114
 [1549] 117 106 255 162 248 147 161  29 131 123 125 126 193 122 239 156 146  48
 [1567] 136 177 135 227  41 176  97 129 132 173 136 224  47 142  74 119 125 134
 [1585] 256  39 181 181 104 182  52 145 167 124 164 131 129 133 226 172 106 180
 [1603] 120 118 118 143  48 143 172 126 139 145 254 172 177 100 240 160 181 121
 [1621] 123 169  87 180  47 251 228 226 152 124 189 114 157 146 160 119 116 129
 [1639] 228  38 112 135 189 172 130  32 222 133  48 111 181  35 128 193 100 190
 [1657]  28  29 126 135 128 194 140 117 101  29 107 183 116  31  58  41 186 156
 [1675] 218 118 117 104 102 156  41 129 178 194  53  62 220 120 183 186 119 122
 [1693]  99 261 154  36  42 115 185 187 165 164 159 126 124 110 112 146 227 464
 [1711]  47  35  47  30 187 188 114 154 166 159 164  41 186 124 177 134 228 112
 [1729] 174 121  98 250 161 210 150 138 161  28 129 118 134 259 219 119  44 178
 [1747] 171 115 251 152 144  47 139 156 130 229  43 178 167  99 179 137 132 165
 [1765] 130 227  46 133 161  58 112 121 138 246  35 180 169 117 103 175  58 146
 [1783] 176 124 161 127 121 130 190 228 176 101 159 115 120  97 131  45 142 171
 [1801] 120 130 137 245 184 107 169  95 248  42 162 178 174  29 128 123 158  82
 [1819]  43 251 223 225 156 106 136 186 119 161 142  91 157 110 112 134 225  37
 [1837] 102 135 189 178 121  28 232 126  45 107 112 185 102 148  34 126 182 171
 [1855] 130  93 190  27  28 131 119 109 106  86  28 108 176 108  29 184 149  61
 [1873]  40 183 168  58 219 133 112  98 102 149  43 129 194 112 188  54  56 221
 [1891] 113 175 185 117 115  83 265 158  40 139  41 112 182 191  43 111 161 161
 [1909] 129 118 105 104 139 214 466  38  43  42  33 190 188 124 159 155 165 164
 [1927]  41 189 111 178 138 215 108 169 118  95 266 157 213 145 139 161  30 126
 [1945] 115 259 229 121  41 174 122 255 154 146  43 136 132 137 231  40 172 178
 [1963]  99 181 136 142 164 136 230  42 137 158  64 117 132 255  33 182 163 120
 [1981] 101 164  54 149 163 127 168 128 115 130 223 174 100 166 122 122  91 133
 [1999]  43 166 118 134 142 255 226 175 100 173 262  41 162 181 181  28 123 110
 [2017] 174  84 193  41 269 228 226 104 128 191 123 162 141  94 153 116 116 134
 [2035] 227  42 104 131 188 184 129  31 233 125  43 110 182 150  38 129 189 178
 [2053]  90 194  29 126 113 108  30  98  96  30  98 178 119 139 193 149  56  42
 [2071] 188 165 240 118 110  97  98 156  41 131 174 109 198  57  62 115 178 181
 [2089]  29 118 112  94 255 150  36 139  42 107 190 193  43 106 165 155 120 119
 [2107] 108 108 141 229 465  41  43  30 186 129 165 162 159 181 196 132 192 240
 [2125] 107 186 134  91 255 163 211 143 164  28 136 124 140 270 244 128  40 187
 [2143] 177 121 263 158 150  42 146 160  NA 138 234  40 188 182 142 159 146 226
 [2161]  43 147 170 118 133 143 261  39 186 173 132 110 162  52 147 163 139 179
 [2179] 144 144 146 196 230 183  96 181 133 142  91 141 139 164 129 134 147 267
 [2197] 188  95 178  93 242  45 181 185 183  30 136 131 166  84  44 258 237 228
 [2215]  98 148 186 120 159  89 161 115 231  37  96 152 195 185  31 229 138  42
 [2233] 113 118 108 161  37 196  87  29 139 120 115 102  97  29 101 177 118  29
 [2251] 194 146  50  45 233 137  30 112  98 100  35 184 116 188  54  63 235 112
 [2269] 178  40 144 190 148 112 274 154  39 138  49 109 196 190  45 109 167 120
 [2287] 109  98 155 225 461  40  39  40  32 188 196 133 199 152 161 166 191 129
 [2305] 191 140 230 108 174 129  97 273 154 218 148 148 164  28 133 120 137 268
 [2323] 241 128  38 205 184 128 263 156 151  44 142 169 138 226  38 189 176 108
 [2341] 188 142 141 159 142 224  40 136 174  68 118 125 144 270  38 198 175 126
 [2359]  99 158  51 149 172 130 182 140 118 141 231 178  96 179 126 128  95 140
 [2377]  41 144 193 125 136 150 288 222 200  98 178  92 281  42 186 172 175  28
 [2395] 136 122 179  88 184  40 282 234 227 152 101 136 195 125 186 151  91 165
 [2413] 121 114 144 233  42  99 137 194 171 133  32 224 137  40 111 173 189 104
 [2431] 163  38 128 183 174  89 193  32  29 140 117 115 140 105 100  31  97 175
 [2449] 111  31 191 144  58  43 180 190  58 231 121 115  94 114 154  35 135 175
 [2467] 117 192  53  66 230 122 183 177 122 108  84 290 147  39 131  46 112 186
 [2485] 193  41 108 182 163 137 118 114  98 158 229 469  44  38  44  31 182 186
 [2503] 126 163 158 152 167  47 181 118 188 127 222 109 167 120  95 269 160 212
 [2521] 145 137 161  29 128 116 138 280 220 128  40 177 170 122 272 156 141  NA
 [2539] 133 158 137 131 226  43 183 178 102 175 129 128 158 127 216  44 142 157
 [2557]  62 115 123 146 295  35 182 174 130 107 160  60 144 154 119 168 131 115
 [2575] 146 219 178 103 168 123 126  97 142  44 138 173 128 136 145 270 220 177
 [2593] 106 174  92 250  43  NA 172 181  30 124 120 187  84 191  46 280 222 232
 [2611] 151 101 128 182 119 158 141  92 154 118 110 137 224  37 101 126 180 177
 [2629] 127  31 226 126  43 104 112 183 100 146  36 131 184 166 141  94 177  29
 [2647]  31 119 128 110  97  95  31 104 167 104  30 188 151  62  42 188 169  58
 [2665] 203 111 107 102  94 146  39 126 175 109 189  61  60 228 115 168 186 112
 [2683] 109  93 276 143  36 137  46 109 197 182  40 106 163 156 126 122 108 103
 [2701] 150 220 475  41  38  44  32 197 184 124 170 180 169 173  41 191 118 182
 [2719] 140 239 106 126  96 253 171 220 150 175  28 132 124 144 130 187 121 255
 [2737] 160 151  42 144 166 150 230  37 179 112 144 144 184 138 227  42 143 169
 [2755]  60 116 133 143 259  37 193 179 108 180  58 151 180 133 174 137 120 151
 [2773] 193 223 181 102 179 131 131  92 134  41 152 186 126 139 156 266 227 197
 [2791] 177  98 261 164 190 127 119 170  88  43 263 226 238 167 105 196 125 174
 [2809] 145 156 114 117 134 222  34 100 139 181 181 126  28 236 132  44 115 183
 [2827]  39 128 197 183 139 199  29  28 129 116 121  30 106  91  29  97 186 118
 [2845] 140  56  43 204 160 223 119 119  98 107 157  39 136 183 197  53  61 233
 [2863] 120 181 189 129 119  95 266 161  42  42 116 193 193 117 179 171 130 128
 [2881] 107 105 153 232  NA  39  39  52  30 193 135 175 164 159  NA  41 195 125
 [2899] 180 144 237 114 138  95 257 163 215 153 176  30 139 122 141 138 183 134
 [2917] 287 155 149  39 144 203 149 232  41 177  99 139 143 195 141 229  43 143
 [2935]  69 133 131 140 275  35 179 174 113 193  51 146 183 131 190 138 130 139
 [2953] 234 178 106 173 138 142  94 153  46 147 185 133 135 158 291 204 180  99
 [2971] 270 161 186 137 139 177  82 205  67 292 237 239 155 101 191 140 201 142
 [2989] 150 129 120 146 226  38 105 137 193 176 135  30 236 146  42 110 191  36
 [3007] 129 192  90 194  31  29 136 138 125 194 143 104  96  32 104 181 110  29
 [3025]  55  41 197 161 220 127 118 101  99 156  41 139 173 195  53  65 228 119
 [3043] 179 191 125 120  84 295 163  36  43 112 183 197 110 162 159 135 117 115
 [3061] 105 172 235 478  46  39  44  28 198 197 141 182 165 169 165  44 190 129
 [3079] 184 148 221 112 164 136  98 286 173 234 146 160 173  28 141 127 142 291
 [3097] 242 141  40 185 178 139 275 158 146  45 154 168 154 228  38 186 183 116
 [3115] 185 151 154 168 156 230  41 156 170  73 121 166 148 283  39 185 170 138
 [3133] 117 173  49 150 187 131 199 145 132 175 180 230 185 140 176 136 152  97
 [3151] 143  46 160 178 125 146 158 292 189 108 182 110 283  44 190 181 178  28
 [3169] 135 134 199  93  47 285 232 239 158 112 143 192 139 158 155 101 163 123
 [3187] 117 149 235  42 110 136 195 172 135  30 230 139  43 119 117 194 139 166
 [3205]  40 138 186 180 147  95 197  32  30 143 128 147 110 102  31 101 181 116
 [3223]  30 194 147  55  45 195 174  57 236 129 117  98  98 179  39 139 187 114
 [3241] 194  52  61 231 122 186 187 182 114  92 295 163  39 137  58 116 192 196
 [3259]  44 111 164 170 137 128 118 112 174 235 481  46  36  44  37 184 192 120
 [3277] 164 159 171 165  45 176 114 172 151 222 115 163 123  99 277 166 217 143
 [3295] 138 168  32 129 119 280 216 125  39 167 127 275 162 143  46 146 136 143
 [3313] 217  40 185 170 100 170 149 142 158 142 219  48 148 164  65 120 145 293
 [3331]  38 183 171 122 102 163  48 139 163 124 177 130 114 142 210 176 106 162
 [3349] 125 127 101 154  46 171 127 142 144 285 221 190 106 165 272  46 181 168
 [3367] 169  31 126 121 176  86 183  46 278 212 236 107 128 178 125 155 138 102
 [3385] 168 125 115 146 223  34 106 123 180 171 131  31 236 132  48 117 174 162
 [3403]  33 141 179 170  98 172  30 129 122 114  28 104  98  30 110 170 112 138
 [3421] 173 142  55  46 177 175 219 114 117 104  98 164  39 139 169 114 179  51
 [3439]  58 108 168 174  28 117 117  91 282 156  38 136  40 113 170 185  46 115
 [3457] 160 161 125 128 115 110 161 227 472  45  44  37 182 121 177 169 168 179
 [3475] 178 127 169 218 112 164 121  98 260 171 224 133 146  31 134 126 157 277
 [3493] 226 131  42 199 165 117 262 157 135  45 140 185 126 141 225  38 191 172
 [3511] 140 177 150 217  43 149 184 115 132 140 285  38 195 163 115 112 177  55
 [3529] 133 187 138 175 151 128 149 178 215 191 113 171 124 126 100 137 152 185
 [3547] 136 136 146 258 191 110 168 100 263  45 179 167 168  30 141 127 171  88
 [3565]  44 273 216 226 105 141 180 120 162  96 167 111 216  40 110 145 182 164
 [3583]  27 220 138  43 118 120 111 166  39 183  96  31 142 118 114 108  92  29
 [3601] 110 173 116  27 178 135  59  44 224 118  28 127 104  90  37 179 115 184
 [3619]  55  60 223 105 169  45 140 176 131 116 262 159  39 129  50 115 175 180
 [3637]  42 117 173 130 103 108 150 225 452  44  42  44  35 182 181 124 217 173
 [3655] 192 186 182 131 172 150 218 116 171 125 102 266 178 230 146 158 180  34
 [3673] 141 122 155 269 218 121  41 198 170 120 259 157 142  43 150 184 150 217
 [3691]  42 190 168 112 178 159 149 177 135 214  45 145 175  64 128 137 155 259
 [3709]  42 194 169 123 110 171  58 141 179 143 170 152 133 142 214 189 112 158
 [3727] 124 127  98 146  54 159 180 128 137 140 259 214 192 104 168 100 255  43
 [3745] 180 172 175  33 133 127 168  90 196  45 253 218 227 173 105 146 185 122
 [3763] 168 137 107 172 121 111 156 214  39 105 146 182 169 124  30 225 136  44
 [3781] 122 114 171 105 174  40 136 190 165  96 181  33  32 153 137 113 152 104
 [3799]  90  33 107 174 117  36 187 144  58  47 188 182  53 225 128 115 103  88
 [3817] 174  37 138 169 112 186  51  60 222 112 169 178 129 115  94 274 158  43
 [3835] 135  48 114 180 177  43 115 181 170 139 132 108 105 150 230 478  46  37
 [3853]  49  30 177 187 131 173 176 156 175  48 188 135 180 154 239 112 167 128
 [3871]  94 262 174 223 138 151 167  28 148 138 143 262 228 136  34 193 170 126
 [3889] 262 173 137  50 147 168 143 149 231  40 193 173 121 172 149 155 165 155
 [3907] 226  46 156 169  67 133 134 149 264  37 200 168 129 117 163  52 142 172
 [3925] 146 172 141 134 154 247 198 101 174 127 133  97 158  47 153 177 140 155
 [3943] 132 259 238 206 101 170  93 258  45 177 172 168  28 145 139 176  93 172
 [3961]  49 271 229 227 160 103 158 183 131 162 139  93 173 127 113 157 230  35
 [3979] 106 150 188 162 130  28 224 152  45 115 112 182 102 169  37 142 176 173
 [3997] 152  96 187  28  28 150 145 116 100  98  29 102 175 112  28 179 140  51
 [4015]  44 181 180  67 223 137 118 103  95 169  36 153 173 110 183  56  69 223
 [4033] 119 174 176 132 110  90 278 165  35 126  44 111 181 188  43 111 174 173
 [4051] 145 130 114 101 153 220 482  47  40  42  30 191 183 123  NA 205  NA 161
 [4069]  43 190 127 183 143 228 108 130  94 267  NA 222 155  NA  33 138 126 139
 [4087] 124  NA 127 273 159 149  45 147 160 141 230  38 165 114 138 138 181 142
 [4105] 225  45 142 174  65 118 128 138 269  35  NA 178 115  NA  56 151  NA 137
 [4123] 175 143 127 150 194 228  NA 104 172 111 128  94 148  46 148 183 141 144
 [4141] 152 262 223  NA 179  97 264 162 184 144 128 172  88  43 270 218 240 157
 [4159]  98 194 125 171 142 159 120 125 138 231  44 103 134 175 180 122  31 229
 [4177] 137  45 109 186  35 140 197 176  95 192  31  32 138 125 116  29 101  94
 [4195]  32 102 183 113 141  54  45 193 169 224 129 117 101  97 160  36 139 175
 [4213] 193  55  62 232 116 175 193 124 117  91 272 152  37  41 114 182 196 114
 [4231]  NA 165 132 123 111 101 160 229 497  46  39  47  30 195 140 164  NA 159
 [4249] 168  47 195 130 191 131 239 114 136 104 266 160 226 155 159  28 133 128
 [4267] 134 136 167 133 266 144 146  46  NA 165 133 228  38 179 102 133 139 173
 [4285] 136 231  49 140  63 128 158 139 281  39 181 173 107 164  53 151 155 119
 [4303] 181 120  NA 136 232  NA 100 177 135 132  94 135  50 142 167 133 189 162
 [4321] 278 171 174  95 245  NA 183 117 128 196  86 196  47 269 232 235 144 102
 [4339] 190 138 160 148  NA 123 115 139 240  38 101 131 183 185 124  29 235 137
 [4357]  43 106 191  40 131 183  99 198  29  30 120 124 114 199 136 102  96  31
 [4375] 100 182 133  33  56  49 203  NA 225 131 114 105 103 148  41 134 181 190
 [4393]  59  65 245 120 185 195 128 112  97 277  73  NA  45  44 110 181 191 109
 [4411] 169 153 125 133 113 104 156 232  73 486  43  41  39  32 195 191 137 184
 [4429] 161 168 182  45 196 111 197 141 255 112 179 135 107  NA 182 235 159 150
 [4447] 182  32 125  NA 137 277 248 138  42 186 209 129 269 157 152  45 147 165
 [4465] 150 255  42 192 187  99 200 144 136 175 138 234  42 142 178  66 114 116
 [4483] 146 265  41 187 192 129 103 183  54 157 177 135 187 140 116 139 200 242

<div class="alert alert-block alert-success">

Najděte lety, které odletěly se zpožděním alespoň 30 minut, ale přiletěly se zpožděním menším než 15 minut. Kolik takových letů bylo?

<details>
<summary></summary>

487

</details>

In [144]:
sum(flights$dep_delay >= 30 & flights$arr_delay < 15, na.rm = TRUE)

[1] 487

<div class="alert alert-block alert-success">

Zjistěte, do kterého cílového letiště směřovalo nejvíce letů. Kolik letů tam směřovalo?

<details>
<summary></summary>

DAL, 9820 letů

</details>

In [157]:
table(flights$dest)[table(flights$dest) == max(table(flights$dest))]

 DAL
9820

<div class="alert alert-block alert-success">

Vypočítejte průměrné zpoždění při příletu pro jednotlivé dny v týdnu. Výsledek seřaďte od nejvyššího průměrného zpoždění po nejnižší.

<details>
<summary></summary>

čtvrtek, pondělí, pátek, neděle, sobota, úterý, středa

</details>

In [177]:
result <- aggregate(arr_delay ~ day_of_week, x = flights, FUN = mean)
result[order(result$arr_delay, decreasing = TRUE), ]

  day_of_week arr_delay
4 4           9.797332
1 1           8.255831
5 5           7.291188
7 7           6.950572
6 6           5.746582
2 2           5.551781
3 3           5.533013

<div class="alert alert-block alert-success">

# Shrnutí

Pole: `array()`

Rozměry objektu: `dim()`, `nrow()`, `ncol()`

Indexování: `objekt[první_dimenze, druhá_dimenze, třetí_dimenze]`

Náhled dat: `str()`, `summary()`, `head()`, `tail()`

Načtení dat: `read.csv()`

Seřazení: `sort()`, `order()`

# Bonus

<div class="alert alert-block alert-success">

Zjistěte, která trasa je nejpopulárnější. Směr letu nerozlišujte, tj. například HOU → ARI považujte za stejnou trasu jako ARI → HOU. Jaká celková vzdálenost byla na této trase během sledovaného období nalétána a které letadlo ji absolvovalo nejčastěji?

> Každé letadlo je v datech jednoznačně identifikováno pomocí **tail_num**.

> Trasa je daná sloupci **origin** a **dest**.

> Délka letu je zaznamenaná ve sloupci **distance**.

In [194]:
trasa <- ifelse(
  flights$origin < flights$dest,
  paste(flights$origin, flights$dest, sep = "-"),
  paste(flights$dest, flights$origin, sep = "-")
)

pocty <- sort(table(trasa), decreasing = TRUE)
nej_trasa <- names(pocty)[1]
lety <- flights[trasa == nej_trasa, ]

nej_trasa
sum(lety$distance)
sort(table(lety$tail_num), decreasing = TRUE)[1]

[1] "DAL-HOU"

[1] 1970077

N510SW
    38